/* Copyright 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "virtualscene_image_provider.h"

#include "absl/log/check.h"

#define FAILURE_DEBUG_PREFIX "VirtualsceneImageProvider"

#include <glm/gtc/matrix_transform.hpp>
#include <vulkan/vulkan.h>

#include <numeric>

#include "absl/log/log.h"

#include "goldfish/debug.h"
#include "goldfish/gvk/device_dispatch.h"
#include "goldfish/gvk/goldfish/gvk/util/staging_buffers.h"
#include "goldfish/gvk/instance_dispatch.h"
#include "goldfish/gvk/system_meta_loader.h"
#include "goldfish/gvk/util/select_physical_device.h"
#include "goldfish/imaging/query_info.h"
#include "goldfish/imaging/to_vk_format.h"
#include "libyuv/convert_from_argb.h"
// #include "tiny_obj_loader.h"

namespace goldfish::camera_image_providers::virtualscene {
namespace {
struct Vertex {
    float pos[3];
    float color[3];
};

struct UniformBufferData {
    glm::mat4 transformationMatrix;
};

const Vertex kTriangeVertices[] = {
    {{-0.5f, -0.5f, 0.0f}, {1.0f, 0.0f, 0.0f}},
    {{-0.5f, 0.5f, 0.0f}, {0.0f, 1.0f, 0.0f}},
    {{0.5f, 0.5f, 0.0f}, {0.0f, 0.0f, 1.0f}},
};

const uint32_t kTriangeIndices[] = {0, 1, 2};

const VkVertexInputBindingDescription kVertexBindingDescription = {
    .binding = 0,
    .stride = sizeof(Vertex),
    .inputRate = VK_VERTEX_INPUT_RATE_VERTEX,
};

const VkVertexInputAttributeDescription kVertexAttributeDescriptions[] = {
    {
        .location = 0,
        .binding = 0,
        .format = VK_FORMAT_R32G32B32_SFLOAT,
        .offset = offsetof(Vertex, pos),
    },
    {
        .location = 1,
        .binding = 0,
        .format = VK_FORMAT_R32G32B32_SFLOAT,
        .offset = offsetof(Vertex, color),
    },
};

/*
 * `kVertexShaderSpvBits` and `kFragmentShaderSpvBits` are prebuilts of Vulkan shaders.
 *
 * They are generated by `glslc`:
 *
 * glslc source.txt -o output.bin
 *
 * which produces a binary file (`output.bin`) which you can translate into
 * a C array by `xxd`:
 *
 *  xxd output.bin
 */

#if 0
#version 450

layout(location = 0) in vec3 inPosition;
layout(location = 1) in vec3 inColor;

layout(location = 0) out vec3 fragColor;

layout(binding = 0) uniform UniformBufferObject {
    mat4 transform;
} ubo;

void main() {
    gl_Position = ubo.transform * vec4(inPosition, 1.0);
    fragColor = inColor;
}
#endif

// SPIR-V binary for the vertex shader code above.
alignas(4) static const uint8_t kVertexShaderSpvBits[] = {
    0x03, 0x02, 0x23, 0x07, 0x00, 0x00, 0x01, 0x00, 0x0b, 0x00, 0x0d, 0x00, 0x27, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x11, 0x00, 0x02, 0x00, 0x01, 0x00, 0x00, 0x00, 0x0b, 0x00, 0x06, 0x00,
    0x01, 0x00, 0x00, 0x00, 0x47, 0x4c, 0x53, 0x4c, 0x2e, 0x73, 0x74, 0x64, 0x2e, 0x34, 0x35, 0x30,
    0x00, 0x00, 0x00, 0x00, 0x0e, 0x00, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
    0x0f, 0x00, 0x09, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x6d, 0x61, 0x69, 0x6e,
    0x00, 0x00, 0x00, 0x00, 0x0d, 0x00, 0x00, 0x00, 0x19, 0x00, 0x00, 0x00, 0x24, 0x00, 0x00, 0x00,
    0x25, 0x00, 0x00, 0x00, 0x03, 0x00, 0x03, 0x00, 0x02, 0x00, 0x00, 0x00, 0xc2, 0x01, 0x00, 0x00,
    0x04, 0x00, 0x0a, 0x00, 0x47, 0x4c, 0x5f, 0x47, 0x4f, 0x4f, 0x47, 0x4c, 0x45, 0x5f, 0x63, 0x70,
    0x70, 0x5f, 0x73, 0x74, 0x79, 0x6c, 0x65, 0x5f, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x64, 0x69, 0x72,
    0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x00, 0x00, 0x04, 0x00, 0x08, 0x00, 0x47, 0x4c, 0x5f, 0x47,
    0x4f, 0x4f, 0x47, 0x4c, 0x45, 0x5f, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x5f, 0x64, 0x69,
    0x72, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x00, 0x05, 0x00, 0x04, 0x00, 0x04, 0x00, 0x00, 0x00,
    0x6d, 0x61, 0x69, 0x6e, 0x00, 0x00, 0x00, 0x00, 0x05, 0x00, 0x06, 0x00, 0x0b, 0x00, 0x00, 0x00,
    0x67, 0x6c, 0x5f, 0x50, 0x65, 0x72, 0x56, 0x65, 0x72, 0x74, 0x65, 0x78, 0x00, 0x00, 0x00, 0x00,
    0x06, 0x00, 0x06, 0x00, 0x0b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x67, 0x6c, 0x5f, 0x50,
    0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x00, 0x06, 0x00, 0x07, 0x00, 0x0b, 0x00, 0x00, 0x00,
    0x01, 0x00, 0x00, 0x00, 0x67, 0x6c, 0x5f, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x53, 0x69, 0x7a, 0x65,
    0x00, 0x00, 0x00, 0x00, 0x06, 0x00, 0x07, 0x00, 0x0b, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00,
    0x67, 0x6c, 0x5f, 0x43, 0x6c, 0x69, 0x70, 0x44, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x00,
    0x06, 0x00, 0x07, 0x00, 0x0b, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x67, 0x6c, 0x5f, 0x43,
    0x75, 0x6c, 0x6c, 0x44, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x00, 0x05, 0x00, 0x03, 0x00,
    0x0d, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x05, 0x00, 0x07, 0x00, 0x11, 0x00, 0x00, 0x00,
    0x55, 0x6e, 0x69, 0x66, 0x6f, 0x72, 0x6d, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x4f, 0x62, 0x6a,
    0x65, 0x63, 0x74, 0x00, 0x06, 0x00, 0x06, 0x00, 0x11, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x00, 0x00, 0x00, 0x05, 0x00, 0x03, 0x00,
    0x13, 0x00, 0x00, 0x00, 0x75, 0x62, 0x6f, 0x00, 0x05, 0x00, 0x05, 0x00, 0x19, 0x00, 0x00, 0x00,
    0x69, 0x6e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x00, 0x00, 0x05, 0x00, 0x05, 0x00,
    0x24, 0x00, 0x00, 0x00, 0x66, 0x72, 0x61, 0x67, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x00, 0x00, 0x00,
    0x05, 0x00, 0x04, 0x00, 0x25, 0x00, 0x00, 0x00, 0x69, 0x6e, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x00,
    0x47, 0x00, 0x03, 0x00, 0x0b, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x48, 0x00, 0x05, 0x00,
    0x0b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x48, 0x00, 0x05, 0x00, 0x0b, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x0b, 0x00, 0x00, 0x00,
    0x01, 0x00, 0x00, 0x00, 0x48, 0x00, 0x05, 0x00, 0x0b, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00,
    0x0b, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x48, 0x00, 0x05, 0x00, 0x0b, 0x00, 0x00, 0x00,
    0x03, 0x00, 0x00, 0x00, 0x0b, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x47, 0x00, 0x03, 0x00,
    0x11, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x48, 0x00, 0x04, 0x00, 0x11, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x05, 0x00, 0x00, 0x00, 0x48, 0x00, 0x05, 0x00, 0x11, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x07, 0x00, 0x00, 0x00, 0x10, 0x00, 0x00, 0x00, 0x48, 0x00, 0x05, 0x00,
    0x11, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x23, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x47, 0x00, 0x04, 0x00, 0x13, 0x00, 0x00, 0x00, 0x21, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x47, 0x00, 0x04, 0x00, 0x13, 0x00, 0x00, 0x00, 0x22, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x47, 0x00, 0x04, 0x00, 0x19, 0x00, 0x00, 0x00, 0x1e, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x47, 0x00, 0x04, 0x00, 0x24, 0x00, 0x00, 0x00, 0x1e, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x47, 0x00, 0x04, 0x00, 0x25, 0x00, 0x00, 0x00, 0x1e, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
    0x13, 0x00, 0x02, 0x00, 0x02, 0x00, 0x00, 0x00, 0x21, 0x00, 0x03, 0x00, 0x03, 0x00, 0x00, 0x00,
    0x02, 0x00, 0x00, 0x00, 0x16, 0x00, 0x03, 0x00, 0x06, 0x00, 0x00, 0x00, 0x20, 0x00, 0x00, 0x00,
    0x17, 0x00, 0x04, 0x00, 0x07, 0x00, 0x00, 0x00, 0x06, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00,
    0x15, 0x00, 0x04, 0x00, 0x08, 0x00, 0x00, 0x00, 0x20, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x2b, 0x00, 0x04, 0x00, 0x08, 0x00, 0x00, 0x00, 0x09, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
    0x1c, 0x00, 0x04, 0x00, 0x0a, 0x00, 0x00, 0x00, 0x06, 0x00, 0x00, 0x00, 0x09, 0x00, 0x00, 0x00,
    0x1e, 0x00, 0x06, 0x00, 0x0b, 0x00, 0x00, 0x00, 0x07, 0x00, 0x00, 0x00, 0x06, 0x00, 0x00, 0x00,
    0x0a, 0x00, 0x00, 0x00, 0x0a, 0x00, 0x00, 0x00, 0x20, 0x00, 0x04, 0x00, 0x0c, 0x00, 0x00, 0x00,
    0x03, 0x00, 0x00, 0x00, 0x0b, 0x00, 0x00, 0x00, 0x3b, 0x00, 0x04, 0x00, 0x0c, 0x00, 0x00, 0x00,
    0x0d, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x15, 0x00, 0x04, 0x00, 0x0e, 0x00, 0x00, 0x00,
    0x20, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x2b, 0x00, 0x04, 0x00, 0x0e, 0x00, 0x00, 0x00,
    0x0f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x18, 0x00, 0x04, 0x00, 0x10, 0x00, 0x00, 0x00,
    0x07, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x1e, 0x00, 0x03, 0x00, 0x11, 0x00, 0x00, 0x00,
    0x10, 0x00, 0x00, 0x00, 0x20, 0x00, 0x04, 0x00, 0x12, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00,
    0x11, 0x00, 0x00, 0x00, 0x3b, 0x00, 0x04, 0x00, 0x12, 0x00, 0x00, 0x00, 0x13, 0x00, 0x00, 0x00,
    0x02, 0x00, 0x00, 0x00, 0x20, 0x00, 0x04, 0x00, 0x14, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00,
    0x10, 0x00, 0x00, 0x00, 0x17, 0x00, 0x04, 0x00, 0x17, 0x00, 0x00, 0x00, 0x06, 0x00, 0x00, 0x00,
    0x03, 0x00, 0x00, 0x00, 0x20, 0x00, 0x04, 0x00, 0x18, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
    0x17, 0x00, 0x00, 0x00, 0x3b, 0x00, 0x04, 0x00, 0x18, 0x00, 0x00, 0x00, 0x19, 0x00, 0x00, 0x00,
    0x01, 0x00, 0x00, 0x00, 0x2b, 0x00, 0x04, 0x00, 0x06, 0x00, 0x00, 0x00, 0x1b, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x80, 0x3f, 0x20, 0x00, 0x04, 0x00, 0x21, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00,
    0x07, 0x00, 0x00, 0x00, 0x20, 0x00, 0x04, 0x00, 0x23, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00,
    0x17, 0x00, 0x00, 0x00, 0x3b, 0x00, 0x04, 0x00, 0x23, 0x00, 0x00, 0x00, 0x24, 0x00, 0x00, 0x00,
    0x03, 0x00, 0x00, 0x00, 0x3b, 0x00, 0x04, 0x00, 0x18, 0x00, 0x00, 0x00, 0x25, 0x00, 0x00, 0x00,
    0x01, 0x00, 0x00, 0x00, 0x36, 0x00, 0x05, 0x00, 0x02, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0xf8, 0x00, 0x02, 0x00, 0x05, 0x00, 0x00, 0x00,
    0x41, 0x00, 0x05, 0x00, 0x14, 0x00, 0x00, 0x00, 0x15, 0x00, 0x00, 0x00, 0x13, 0x00, 0x00, 0x00,
    0x0f, 0x00, 0x00, 0x00, 0x3d, 0x00, 0x04, 0x00, 0x10, 0x00, 0x00, 0x00, 0x16, 0x00, 0x00, 0x00,
    0x15, 0x00, 0x00, 0x00, 0x3d, 0x00, 0x04, 0x00, 0x17, 0x00, 0x00, 0x00, 0x1a, 0x00, 0x00, 0x00,
    0x19, 0x00, 0x00, 0x00, 0x51, 0x00, 0x05, 0x00, 0x06, 0x00, 0x00, 0x00, 0x1c, 0x00, 0x00, 0x00,
    0x1a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x51, 0x00, 0x05, 0x00, 0x06, 0x00, 0x00, 0x00,
    0x1d, 0x00, 0x00, 0x00, 0x1a, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x51, 0x00, 0x05, 0x00,
    0x06, 0x00, 0x00, 0x00, 0x1e, 0x00, 0x00, 0x00, 0x1a, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00,
    0x50, 0x00, 0x07, 0x00, 0x07, 0x00, 0x00, 0x00, 0x1f, 0x00, 0x00, 0x00, 0x1c, 0x00, 0x00, 0x00,
    0x1d, 0x00, 0x00, 0x00, 0x1e, 0x00, 0x00, 0x00, 0x1b, 0x00, 0x00, 0x00, 0x91, 0x00, 0x05, 0x00,
    0x07, 0x00, 0x00, 0x00, 0x20, 0x00, 0x00, 0x00, 0x16, 0x00, 0x00, 0x00, 0x1f, 0x00, 0x00, 0x00,
    0x41, 0x00, 0x05, 0x00, 0x21, 0x00, 0x00, 0x00, 0x22, 0x00, 0x00, 0x00, 0x0d, 0x00, 0x00, 0x00,
    0x0f, 0x00, 0x00, 0x00, 0x3e, 0x00, 0x03, 0x00, 0x22, 0x00, 0x00, 0x00, 0x20, 0x00, 0x00, 0x00,
    0x3d, 0x00, 0x04, 0x00, 0x17, 0x00, 0x00, 0x00, 0x26, 0x00, 0x00, 0x00, 0x25, 0x00, 0x00, 0x00,
    0x3e, 0x00, 0x03, 0x00, 0x24, 0x00, 0x00, 0x00, 0x26, 0x00, 0x00, 0x00, 0xfd, 0x00, 0x01, 0x00,
    0x38, 0x00, 0x01, 0x00};

#if 0
#version 450

layout(location = 0) in vec3 fragColor;
layout(location = 0) out vec4 outColor;

void main() {
    outColor = vec4(fragColor, 1.0);
}
#endif

// SPIR-V binary for the fragment shader code above.
alignas(4) static const uint8_t kFragmentShaderSpvBits[] = {
    0x03, 0x02, 0x23, 0x07, 0x00, 0x00, 0x01, 0x00, 0x0b, 0x00, 0x0d, 0x00, 0x13, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x11, 0x00, 0x02, 0x00, 0x01, 0x00, 0x00, 0x00, 0x0b, 0x00, 0x06, 0x00,
    0x01, 0x00, 0x00, 0x00, 0x47, 0x4c, 0x53, 0x4c, 0x2e, 0x73, 0x74, 0x64, 0x2e, 0x34, 0x35, 0x30,
    0x00, 0x00, 0x00, 0x00, 0x0e, 0x00, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
    0x0f, 0x00, 0x07, 0x00, 0x04, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x6d, 0x61, 0x69, 0x6e,
    0x00, 0x00, 0x00, 0x00, 0x09, 0x00, 0x00, 0x00, 0x0c, 0x00, 0x00, 0x00, 0x10, 0x00, 0x03, 0x00,
    0x04, 0x00, 0x00, 0x00, 0x07, 0x00, 0x00, 0x00, 0x03, 0x00, 0x03, 0x00, 0x02, 0x00, 0x00, 0x00,
    0xc2, 0x01, 0x00, 0x00, 0x04, 0x00, 0x0a, 0x00, 0x47, 0x4c, 0x5f, 0x47, 0x4f, 0x4f, 0x47, 0x4c,
    0x45, 0x5f, 0x63, 0x70, 0x70, 0x5f, 0x73, 0x74, 0x79, 0x6c, 0x65, 0x5f, 0x6c, 0x69, 0x6e, 0x65,
    0x5f, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x00, 0x00, 0x04, 0x00, 0x08, 0x00,
    0x47, 0x4c, 0x5f, 0x47, 0x4f, 0x4f, 0x47, 0x4c, 0x45, 0x5f, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64,
    0x65, 0x5f, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x00, 0x05, 0x00, 0x04, 0x00,
    0x04, 0x00, 0x00, 0x00, 0x6d, 0x61, 0x69, 0x6e, 0x00, 0x00, 0x00, 0x00, 0x05, 0x00, 0x05, 0x00,
    0x09, 0x00, 0x00, 0x00, 0x6f, 0x75, 0x74, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x00, 0x00, 0x00, 0x00,
    0x05, 0x00, 0x05, 0x00, 0x0c, 0x00, 0x00, 0x00, 0x66, 0x72, 0x61, 0x67, 0x43, 0x6f, 0x6c, 0x6f,
    0x72, 0x00, 0x00, 0x00, 0x47, 0x00, 0x04, 0x00, 0x09, 0x00, 0x00, 0x00, 0x1e, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x47, 0x00, 0x04, 0x00, 0x0c, 0x00, 0x00, 0x00, 0x1e, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x13, 0x00, 0x02, 0x00, 0x02, 0x00, 0x00, 0x00, 0x21, 0x00, 0x03, 0x00,
    0x03, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x16, 0x00, 0x03, 0x00, 0x06, 0x00, 0x00, 0x00,
    0x20, 0x00, 0x00, 0x00, 0x17, 0x00, 0x04, 0x00, 0x07, 0x00, 0x00, 0x00, 0x06, 0x00, 0x00, 0x00,
    0x04, 0x00, 0x00, 0x00, 0x20, 0x00, 0x04, 0x00, 0x08, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00,
    0x07, 0x00, 0x00, 0x00, 0x3b, 0x00, 0x04, 0x00, 0x08, 0x00, 0x00, 0x00, 0x09, 0x00, 0x00, 0x00,
    0x03, 0x00, 0x00, 0x00, 0x17, 0x00, 0x04, 0x00, 0x0a, 0x00, 0x00, 0x00, 0x06, 0x00, 0x00, 0x00,
    0x03, 0x00, 0x00, 0x00, 0x20, 0x00, 0x04, 0x00, 0x0b, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
    0x0a, 0x00, 0x00, 0x00, 0x3b, 0x00, 0x04, 0x00, 0x0b, 0x00, 0x00, 0x00, 0x0c, 0x00, 0x00, 0x00,
    0x01, 0x00, 0x00, 0x00, 0x2b, 0x00, 0x04, 0x00, 0x06, 0x00, 0x00, 0x00, 0x0e, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x80, 0x3f, 0x36, 0x00, 0x05, 0x00, 0x02, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0xf8, 0x00, 0x02, 0x00, 0x05, 0x00, 0x00, 0x00,
    0x3d, 0x00, 0x04, 0x00, 0x0a, 0x00, 0x00, 0x00, 0x0d, 0x00, 0x00, 0x00, 0x0c, 0x00, 0x00, 0x00,
    0x51, 0x00, 0x05, 0x00, 0x06, 0x00, 0x00, 0x00, 0x0f, 0x00, 0x00, 0x00, 0x0d, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x51, 0x00, 0x05, 0x00, 0x06, 0x00, 0x00, 0x00, 0x10, 0x00, 0x00, 0x00,
    0x0d, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x51, 0x00, 0x05, 0x00, 0x06, 0x00, 0x00, 0x00,
    0x11, 0x00, 0x00, 0x00, 0x0d, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x50, 0x00, 0x07, 0x00,
    0x07, 0x00, 0x00, 0x00, 0x12, 0x00, 0x00, 0x00, 0x0f, 0x00, 0x00, 0x00, 0x10, 0x00, 0x00, 0x00,
    0x11, 0x00, 0x00, 0x00, 0x0e, 0x00, 0x00, 0x00, 0x3e, 0x00, 0x03, 0x00, 0x09, 0x00, 0x00, 0x00,
    0x12, 0x00, 0x00, 0x00, 0xfd, 0x00, 0x01, 0x00, 0x38, 0x00, 0x01, 0x00};

}  // namespace

const char* VirtualsceneImageProvider::getId() const {
    return "virtualscene";
}

int VirtualsceneImageProvider::start(const CameraImageProviderStreamConfig* const streamConfigs,
                                     const unsigned streamConfigsSize) {
    const RenderOutputConfig roc = getRenderOutputConfig(streamConfigs, streamConfigsSize);
    if (!roc.size.width || !roc.size.height) {
        return FAILURE_STR("render output size size is zero", -1);
    }

    const VkFormat framebufferFormat = ToVkFormat(roc.getFormat());
    if (framebufferFormat == VK_FORMAT_UNDEFINED) {
        return FAILURE(-1);
    }

    std::vector<CaptureStreamBuffers> captureStreamBuffers(streamConfigsSize);
    std::vector<VkImageMemoryBarrier> changeImageLayoutBarriers;
    changeImageLayoutBarriers.reserve(streamConfigsSize + 1);
    size_t maxYuvConversionBufferSize = 0;
    for (unsigned i = 0; i < streamConfigsSize; ++i) {
        const CameraImageProviderStreamConfig& cfg = streamConfigs[i];
        if (!cfg.size.width || !cfg.size.height) {
            return FAILURE_STR("stream size is zero", -1);
        }

        const imaging::ImageFormat streamFormat = static_cast<imaging::ImageFormat>(cfg.format);
        switch (streamFormat) {
        case imaging::ImageFormat::kNone:
        case imaging::ImageFormat::kRgba8888:
            break;

        case imaging::ImageFormat::kYuV4203P:
        case imaging::ImageFormat::kYuV420NV12:
            if ((cfg.size.width | cfg.size.height) & 1U) {
                return FAILURE_STR("YUV stream with odd size", -1);
            }
            break;
        }

        const imaging::ImageFormat stagingFormat = getStagingFormat(streamFormat);
        const VkFormat stagingGpuFormat = ToVkFormat(stagingFormat);
        if (stagingGpuFormat == VK_FORMAT_UNDEFINED) {
            return FAILURE_STR("stagingGpuFormat", -1);
        }

        const uint32_t dstBufferSize =
                imaging::GetDataSize(stagingFormat, cfg.size.width, cfg.size.height);
        if (!dstBufferSize) {
            return FAILURE_STR("dstBufferSize", -1);
        }

        CaptureStreamBuffers& bufs = captureStreamBuffers[i];
        gvk::DeviceMemory gpuImageMemory;
        gvk::Image gpuImage;

        if ((framebufferFormat != stagingGpuFormat) || (roc.size.width != cfg.size.width) ||
            (roc.size.height != cfg.size.height)) {
            const VkImageCreateInfo gpuImageCreateInfo = {
                .sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO,
                .pNext = nullptr,
                .flags = 0,
                .imageType = VK_IMAGE_TYPE_2D,
                .format = stagingGpuFormat,
                .extent = {cfg.size.width, cfg.size.height, 1},
                .mipLevels = 1,
                .arrayLayers = 1,
                .samples = VK_SAMPLE_COUNT_1_BIT,
                .tiling = VK_IMAGE_TILING_OPTIMAL,
                .usage = VK_IMAGE_USAGE_TRANSFER_SRC_BIT | VK_IMAGE_USAGE_TRANSFER_DST_BIT,
                .sharingMode = VK_SHARING_MODE_EXCLUSIVE,
                .queueFamilyIndexCount = 0,
                .pQueueFamilyIndices = nullptr,
                .initialLayout = VK_IMAGE_LAYOUT_UNDEFINED,
            };

            std::tie(gpuImageMemory, gpuImage) = gvk::util::allocateImage(
                    *mDeviceDispatch, mMemoryProperties, gpuImageCreateInfo,
                    VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
            if (!gpuImageMemory || !gpuImage) {
                return FAILURE_STR("!gpuImageMemory || !gpuImage", -1);
            }

            changeImageLayoutBarriers.push_back({
                .sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER,
                .pNext = nullptr,
                .srcAccessMask = 0,
                .dstAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT,
                .oldLayout = gpuImageCreateInfo.initialLayout,
                .newLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
                .srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED,
                .dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED,
                .image = gpuImage.get(),
                .subresourceRange =
                        {
                            .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                            .baseMipLevel = 0,
                            .levelCount = 1,
                            .baseArrayLayer = 0,
                            .layerCount = 1,
                        },
            });
        }

        auto [dstBufferMemory, dstBuffer] = gvk::util::allocateBuffer(
                *mDeviceDispatch, mMemoryProperties, dstBufferSize,
                VK_BUFFER_USAGE_TRANSFER_DST_BIT, VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT);
        if (!dstBufferMemory || !dstBuffer) {
            return FAILURE_STR("!dstBufferMemory || !dstBuffer", -1);
        }

        switch (streamFormat) {
        case imaging::ImageFormat::kNone:
        case imaging::ImageFormat::kRgba8888:
            break;

        case imaging::ImageFormat::kYuV4203P:
        case imaging::ImageFormat::kYuV420NV12:
            maxYuvConversionBufferSize =
                    std::max(maxYuvConversionBufferSize,
                             imaging::GetDataSize(streamFormat, cfg.size.width, cfg.size.height));
            break;
        }

        bufs.gpuImageMemory = std::move(gpuImageMemory);
        bufs.dstBufferMemory = std::move(dstBufferMemory);
        bufs.gpuImage = std::move(gpuImage);
        bufs.dstBuffer = std::move(dstBuffer);
        bufs.srcCropRegion = getCropRegion(roc.size, cfg.size);
        bufs.size = cfg.size;
        bufs.bufferSizeBytes = dstBufferSize;
        bufs.id = cfg.id;
    }

    const VkImageCreateInfo framebufferImageCreateInfo = {
        .sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO,
        .pNext = nullptr,
        .flags = 0,
        .imageType = VK_IMAGE_TYPE_2D,
        .format = framebufferFormat,
        .extent = {roc.size.width, roc.size.height, 1},
        .mipLevels = 1,
        .arrayLayers = 1,
        .samples = VK_SAMPLE_COUNT_1_BIT,
        .tiling = VK_IMAGE_TILING_OPTIMAL,
        .usage = VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT | VK_IMAGE_USAGE_TRANSFER_SRC_BIT,
        .sharingMode = VK_SHARING_MODE_EXCLUSIVE,
        .queueFamilyIndexCount = 0,
        .pQueueFamilyIndices = nullptr,
        .initialLayout = VK_IMAGE_LAYOUT_UNDEFINED,
    };

    auto [framebufferImageMemory, framebufferImage] = gvk::util::allocateImage(
            *mDeviceDispatch, mMemoryProperties, framebufferImageCreateInfo,
            VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
    if (!framebufferImageMemory || !framebufferImage) {
        return FAILURE_STR("!framebufferImageMemory || !framebufferImage", -1);
    }

    changeImageLayoutBarriers.push_back({
        .sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER,
        .pNext = nullptr,
        .srcAccessMask = 0,
        .dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT,
        .oldLayout = framebufferImageCreateInfo.initialLayout,
        .newLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL,
        .srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED,
        .dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED,
        .image = framebufferImage.get(),
        .subresourceRange =
                {
                    .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                    .baseMipLevel = 0,
                    .levelCount = 1,
                    .baseArrayLayer = 0,
                    .layerCount = 1,
                },
    });

    {
        VkCommandBuffer changeLayoutsCmdBuf = VK_NULL_HANDLE;
        if (!mDeviceDispatch->allocateCommandBuffers(
                    mCommandPool.get(), VK_COMMAND_BUFFER_LEVEL_PRIMARY, 1, &changeLayoutsCmdBuf)) {
            return FAILURE_STR("changeLayoutsCmdBuf", -1);
        }

        {
            const auto ender = mDeviceDispatch->beginCommandBuffer(
                    changeLayoutsCmdBuf, VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT);
            mDeviceDispatch->cmdPipelineBarrier(
                    changeLayoutsCmdBuf,
                    VK_PIPELINE_STAGE_TRANSFER_BIT | VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT,
                    VK_PIPELINE_STAGE_TRANSFER_BIT | VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT,
                    0, 0, nullptr, 0, nullptr, changeImageLayoutBarriers.size(),
                    changeImageLayoutBarriers.data());
        }

        mDeviceDispatch->queueSubmit(mGraphicsQueue, changeLayoutsCmdBuf);
        mDeviceDispatch->queueWaitIdle(mGraphicsQueue);
        changeImageLayoutBarriers.clear();
        mDeviceDispatch->freeCommandBuffers(mCommandPool.get(), 1, &changeLayoutsCmdBuf);
    }

    gvk::ImageView framebufferImageView =
            mDeviceDispatch->createImageView(framebufferImage.get(), VK_IMAGE_VIEW_TYPE_2D,
                                             framebufferFormat, VK_IMAGE_ASPECT_COLOR_BIT);
    if (!framebufferImageView) {
        return FAILURE_STR("framebufferImageView", -1);
    }

    const VkAttachmentDescription renderAttachmentDescription = {
        .flags = 0,
        .format = framebufferFormat,
        .samples = framebufferImageCreateInfo.samples,
        .loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR,
        .storeOp = VK_ATTACHMENT_STORE_OP_STORE,
        .stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE,
        .stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE,
        .initialLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL,
        .finalLayout = VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
    };

    const VkAttachmentReference colorAttachmentReference = {
        .attachment = 0,
        .layout = renderAttachmentDescription.initialLayout,
    };

    const VkSubpassDescription subpassDescription = {
        .flags = 0,
        .pipelineBindPoint = VK_PIPELINE_BIND_POINT_GRAPHICS,
        .inputAttachmentCount = 0,
        .pInputAttachments = nullptr,
        .colorAttachmentCount = 1,
        .pColorAttachments = &colorAttachmentReference,
        .pResolveAttachments = nullptr,
        .pDepthStencilAttachment = nullptr,
        .preserveAttachmentCount = 0,
        .pPreserveAttachments = nullptr,
    };

    const VkRenderPassCreateInfo renderPassCreateInfo = {
        .sType = VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO,
        .pNext = nullptr,
        .flags = 0,
        .attachmentCount = 1,
        .pAttachments = &renderAttachmentDescription,
        .subpassCount = 1,
        .pSubpasses = &subpassDescription,
        .dependencyCount = 0,
        .pDependencies = nullptr,
    };

    gvk::RenderPass renderPass = mDeviceDispatch->createRenderPass(renderPassCreateInfo);
    if (!renderPass) {
        return FAILURE_STR("renderPass", -1);
    }

    gvk::Framebuffer framebuffer = mDeviceDispatch->createFramebuffer(
            renderPass.get(), framebufferImageView.get(), roc.size.width, roc.size.height);
    if (!framebuffer) {
        return FAILURE_STR("framebuffer", -1);
    }

    const VkPipelineShaderStageCreateInfo vertexShaderStageCreateInfo[] = {
        {
            .sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,
            .pNext = nullptr,
            .flags = 0,
            .stage = VK_SHADER_STAGE_VERTEX_BIT,
            .module = mVertexShaderModule.get(),
            .pName = "main",
            .pSpecializationInfo = nullptr,
        },
        {
            .sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,
            .pNext = nullptr,
            .flags = 0,
            .stage = VK_SHADER_STAGE_FRAGMENT_BIT,
            .module = mFragmentShaderModule.get(),
            .pName = "main",
            .pSpecializationInfo = nullptr,
        },
    };

    const VkPipelineVertexInputStateCreateInfo vertexInputStateCreateInfo = {
        .sType = VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO,
        .pNext = nullptr,
        .flags = 0,
        .vertexBindingDescriptionCount = 1,
        .pVertexBindingDescriptions = &kVertexBindingDescription,
        .vertexAttributeDescriptionCount = 2,
        .pVertexAttributeDescriptions = kVertexAttributeDescriptions,
    };

    const VkPipelineInputAssemblyStateCreateInfo inputAssemblyStateCreateInfo = {
        .sType = VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO,
        .pNext = nullptr,
        .flags = 0,
        .topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST,
        .primitiveRestartEnable = VK_FALSE,
    };

    const VkViewport viewport = {
        .x = 0.0f,
        .y = 0.0f,
        .width = static_cast<float>(roc.size.width),
        .height = static_cast<float>(roc.size.height),
        .minDepth = 0.0f,
        .maxDepth = 1.0f,
    };

    const VkRect2D scissor = {
        .offset = {0, 0},
        .extent = {roc.size.width, roc.size.height},
    };

    const VkPipelineViewportStateCreateInfo viewportStateCreateInfo = {
        .sType = VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO,
        .pNext = nullptr,
        .flags = 0,
        .viewportCount = 1,
        .pViewports = &viewport,
        .scissorCount = 1,
        .pScissors = &scissor,
    };

    const VkPipelineRasterizationStateCreateInfo rasterizationStateCreateInfo = {
        .sType = VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO,
        .pNext = nullptr,
        .flags = 0,
        .depthClampEnable = VK_FALSE,
        .rasterizerDiscardEnable = VK_FALSE,
        .polygonMode = VK_POLYGON_MODE_FILL,
        .cullMode = VK_CULL_MODE_BACK_BIT,
        .frontFace = VK_FRONT_FACE_COUNTER_CLOCKWISE,
        .depthBiasEnable = VK_FALSE,
        .depthBiasConstantFactor = 0.0f,
        .depthBiasClamp = 0.0f,
        .depthBiasSlopeFactor = 0.0f,
        .lineWidth = 1.0f,
    };

    const VkPipelineMultisampleStateCreateInfo multisampleStateCreateInfo = {
        .sType = VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO,
        .pNext = nullptr,
        .flags = 0,
        .rasterizationSamples = VK_SAMPLE_COUNT_1_BIT,
        .sampleShadingEnable = VK_FALSE,
        .minSampleShading = 1.0f,
        .pSampleMask = nullptr,
        .alphaToCoverageEnable = VK_FALSE,
        .alphaToOneEnable = VK_FALSE,
    };

    const VkPipelineColorBlendAttachmentState colorBlendAttachmentState = {
        .blendEnable = VK_FALSE,
        .srcColorBlendFactor = VK_BLEND_FACTOR_ONE,
        .dstColorBlendFactor = VK_BLEND_FACTOR_ZERO,
        .colorBlendOp = VK_BLEND_OP_ADD,
        .srcAlphaBlendFactor = VK_BLEND_FACTOR_ONE,
        .dstAlphaBlendFactor = VK_BLEND_FACTOR_ZERO,
        .alphaBlendOp = VK_BLEND_OP_ADD,
        .colorWriteMask = VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT |
                          VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT,
    };

    const VkPipelineColorBlendStateCreateInfo colorBlendCreateInfo = {
        .sType = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO,
        .pNext = nullptr,
        .flags = 0,
        .logicOpEnable = VK_FALSE,
        .logicOp = VK_LOGIC_OP_COPY,
        .attachmentCount = 1,
        .pAttachments = &colorBlendAttachmentState,
        .blendConstants = {0.0f, 0.0f, 0.0f, 0.0f},
    };

    const VkGraphicsPipelineCreateInfo graphicsPipelineCreateInfo = {
        .sType = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO,
        .pNext = nullptr,
        .flags = 0,
        .stageCount = std::size(vertexShaderStageCreateInfo),
        .pStages = vertexShaderStageCreateInfo,
        .pVertexInputState = &vertexInputStateCreateInfo,
        .pInputAssemblyState = &inputAssemblyStateCreateInfo,
        .pTessellationState = nullptr,
        .pViewportState = &viewportStateCreateInfo,
        .pRasterizationState = &rasterizationStateCreateInfo,
        .pMultisampleState = &multisampleStateCreateInfo,
        .pDepthStencilState = nullptr,
        .pColorBlendState = &colorBlendCreateInfo,
        .pDynamicState = nullptr,
        .layout = mPipelineLayout.get(),
        .renderPass = renderPass.get(),
        .subpass = 0,
        .basePipelineHandle = VK_NULL_HANDLE,
        .basePipelineIndex = -1,
    };

    gvk::Pipeline pipeline;
    if (!mDeviceDispatch->createGraphicsPipelines(1, &graphicsPipelineCreateInfo, &pipeline)) {
        return FAILURE_STR("pipeline", -1);
    }

    VkCommandBuffer renderCmdBuf = VK_NULL_HANDLE;
    if (!mDeviceDispatch->allocateCommandBuffers(
                mCommandPool.get(), VK_COMMAND_BUFFER_LEVEL_PRIMARY, 1, &renderCmdBuf)) {
        return FAILURE_STR("renderCmdBuf", -1);
    }

    stop();

    CaptureSession captureSession;
    captureSession.captureStreamBuffers = std::move(captureStreamBuffers);
    captureSession.yuvConversionBuffer.resize(maxYuvConversionBufferSize);
    captureSession.framebufferImageMemory = std::move(framebufferImageMemory);
    captureSession.framebufferImage = std::move(framebufferImage);
    captureSession.framebufferImageView = std::move(framebufferImageView);
    captureSession.renderPass = std::move(renderPass);
    captureSession.framebuffer = std::move(framebuffer);
    captureSession.pipeline = std::move(pipeline);
    captureSession.renderCmdBuf = renderCmdBuf;
    captureSession.framebuffer_size = roc.size;

    mCaptureSession = std::move(captureSession);
    return 0;
}

VirtualsceneImageProvider::RenderOutputConfig VirtualsceneImageProvider::getRenderOutputConfig(
        const CameraImageProviderStreamConfig* s, unsigned n) {
    return std::accumulate(
            s, s + n, RenderOutputConfig(),
            [](RenderOutputConfig result, const CameraImageProviderStreamConfig& cfg) {
                const size_t cfgArea = size_t(cfg.size.width) * cfg.size.height;
                const size_t resultArea = size_t(result.size.width) * result.size.height;
                if (resultArea < cfgArea) {
                    result.size = cfg.size;
                }
                return result;
            });
}

imaging::ImageFormat VirtualsceneImageProvider::RenderOutputConfig::getFormat() const {
    // TODO: HDR
    return imaging::ImageFormat::kRgba8888;
}

imaging::ImageFormat VirtualsceneImageProvider::getStagingFormat(const imaging::ImageFormat fmt) {
    using imaging::ImageFormat;

    switch (fmt) {
    case ImageFormat::kNone:
        break;

    // vkCmdBlitImage into YUV support is optional,
    // we have to convert on the CPU via libuyv.
    case ImageFormat::kYuV4203P:
    case ImageFormat::kYuV420NV12:
    case ImageFormat::kRgba8888:
        return ImageFormat::kRgba8888;
    }

    return ImageFormat::kNone;
}

VirtualsceneImageProvider::CropRegion VirtualsceneImageProvider::getCropRegion(
        const CameraImageProviderRect srcSize, const CameraImageProviderRect dstSize) {
    DCHECK(srcSize.width);
    DCHECK(srcSize.height);
    DCHECK(dstSize.width);
    DCHECK(dstSize.height);

    using Dimension = decltype(CameraImageProviderRect::width);

    const double srcAspectRatio = static_cast<double>(srcSize.width) / srcSize.height;
    const double dstAspectRatio = static_cast<double>(dstSize.width) / dstSize.height;

    CropRegion result;

    if (srcAspectRatio > dstAspectRatio) {
        // Source is wider than destination, so we crop the width to match the
        // destination's aspect ratio (pillarboxing).
        const Dimension newWidth = static_cast<Dimension>(srcSize.height * dstAspectRatio);
        result.size = {newWidth, srcSize.height};
        result.offset = {static_cast<Dimension>((srcSize.width - newWidth) / 2), 0};
    } else if (srcAspectRatio < dstAspectRatio) {
        // Source is taller than destination, so we crop the height to match the
        // destination's aspect ratio (letterboxing).
        const Dimension newHeight = static_cast<Dimension>(srcSize.width / dstAspectRatio);
        result.size = {srcSize.width, newHeight};
        result.offset = {0, static_cast<Dimension>((srcSize.height - newHeight) / 2)};
    } else {
        // Aspect ratios are the same, no crop needed.
        result.size = srcSize;
    }

    return result;
}

const VirtualsceneImageProvider::CaptureStreamBuffers*
VirtualsceneImageProvider::findCaptureStreamBuffers(const int32_t id, const CaptureStreamBuffers* a,
                                                    size_t n) {
    const CaptureStreamBuffers* i = std::find_if(
            a, a + n, [id](const CaptureStreamBuffers& bufs) { return bufs.id == id; });
    return (i == (a + n)) ? nullptr : i;
}

int VirtualsceneImageProvider::capture(const CameraImageProviderCaptureOpts& /*opts*/,
                                       const CameraImageProviderStreamCaptureSink sink,
                                       void* const sinkOpaque,
                                       const CameraImageProviderStreamCaptureInfo* scis,
                                       const unsigned scisSize) {
    if (!scisSize) {
        return 0;
    } else if (mCaptureSession) {
        CaptureSession& session = *mCaptureSession;
        if (!updateUniformData(session.framebuffer_size, ++session.frameCounter / 256.0f)) {
            return FAILURE_STR("updateUniformData", -1);
        }

        if (!captureImpl(session, sink, sinkOpaque, scis, scisSize,
                         session.yuvConversionBuffer.data())) {
            return FAILURE_STR("captureImpl", -1);
        }

        return 0;
    } else {
        return FAILURE_STR("!mCaptureSession", -1);
    }
}

bool VirtualsceneImageProvider::updateUniformData(const CameraImageProviderRect framebuffer_size,
                                                  const float angle) {
    glm::mat4 modelMatrix =
            glm::rotate(glm::mat4(1.0f), angle * glm::radians(360.f), glm::vec3(0, 0, 1));
    modelMatrix = glm::translate(modelMatrix, glm::vec3(0.5f / 3.0f, -0.5f / 3.0f, 0.0f));

    // Set up view
    auto viewMatrix = glm::lookAt(glm::vec3(1, 1, 1), glm::vec3(0, 0, 0), glm::vec3(0, 0, -1));

    // Set up projection
    auto projMatrix =
            glm::perspective(glm::radians(70.f),
                             framebuffer_size.width / float(framebuffer_size.height), 0.1f, 10.0f);

    UniformBufferData uniformData = {
        .transformationMatrix = projMatrix * viewMatrix * modelMatrix,
    };

    void* bits = mDeviceDispatch->mapMemory(mUniformMem.get(), sizeof(uniformData));
    if (!bits) {
        return FAILURE_STR("mapMemory", false);
    }

    ::memcpy(bits, &uniformData, sizeof(uniformData));
    mDeviceDispatch->unmapMemory(mUniformMem.get());

    return true;
}

bool VirtualsceneImageProvider::captureImpl(const CaptureSession& session,
                                            const CameraImageProviderStreamCaptureSink sink,
                                            void* const sinkOpaque,
                                            const CameraImageProviderStreamCaptureInfo* scis,
                                            const unsigned scisSize, uint8_t* yuvConversionBuffer) {
    const VkCommandBuffer renderCmdBuf = recordCommandBuffer(session, scis, scisSize);
    if (!renderCmdBuf) {
        return FAILURE_STR("renderCmdBuf", false);
    }

    if (!mDeviceDispatch->queueSubmit(mGraphicsQueue, renderCmdBuf)) {
        return FAILURE_STR("queueSubmit", false);
    }

    if (!mDeviceDispatch->queueWaitIdle(mGraphicsQueue)) {
        return FAILURE_STR("queueWaitIdle", false);
    }

    for (unsigned i = 0; i < scisSize; ++i) {
        const CameraImageProviderStreamCaptureInfo& sci = scis[i];
        const CameraImageProviderStreamConfig& cfg = *sci.cfg;
        const CaptureStreamBuffers* bufs = findCaptureStreamBuffers(
                cfg.id, session.captureStreamBuffers.data(), session.captureStreamBuffers.size());
        if (!bufs) {
            continue;
        }

        const uint8_t* bits = static_cast<const uint8_t*>(
                mDeviceDispatch->mapMemory(bufs->dstBufferMemory.get(), bufs->bufferSizeBytes));
        if (!bits) {
            return FAILURE_STR("mapMemory", false);
        }

        switch (static_cast<imaging::ImageFormat>(cfg.format)) {
        case imaging::ImageFormat::kNone:
            break;

        case imaging::ImageFormat::kRgba8888:
            sink(sinkOpaque, &sci, bits, bufs->bufferSizeBytes);
            break;

        case imaging::ImageFormat::kYuV4203P: {
            const int width = static_cast<int>(cfg.size.width);
            const int width2 = width / 2;
            const int height = static_cast<int>(cfg.size.height);
            uint8_t* y = yuvConversionBuffer;
            uint8_t* u = y + width * height;
            uint8_t* v = u + width * height / 4;

            libyuv::ARGBToI420(bits, width * 4, y, width, u, width2, v, width2, width, height);
            sink(sinkOpaque, &sci, yuvConversionBuffer, width * height * 3 / 2);
        } break;

        case imaging::ImageFormat::kYuV420NV12: {
            const int width = static_cast<int>(cfg.size.width);
            const int height = static_cast<int>(cfg.size.height);
            uint8_t* y = yuvConversionBuffer;
            uint8_t* uv = y + width * height;

            libyuv::ARGBToNV12(bits, width * 4, y, width, uv, width, width, height);
            sink(sinkOpaque, &sci, yuvConversionBuffer, width * height * 3 / 2);
        } break;
        }

        mDeviceDispatch->unmapMemory(bufs->dstBufferMemory.get());
    }

    return true;
}

VkCommandBuffer VirtualsceneImageProvider::recordCommandBuffer(
        const CaptureSession& session, const CameraImageProviderStreamCaptureInfo* scis,
        const unsigned scisSize) {
    const VkCommandBuffer renderCmdBuf = session.renderCmdBuf;

    const auto cmdBufEnder = mDeviceDispatch->beginCommandBuffer(
            renderCmdBuf, VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT);
    if (!cmdBufEnder) {
        return FAILURE_STR("beginCommandBuffer", VK_NULL_HANDLE);
    }

    {
        const VkClearValue clearColor = {
            .color =
                    {
                        .float32 = {0.1f, 0.1f, 0.1f, 1.0f}  // R, G, B, A
                    },
        };

        const auto renderPassEnder = mDeviceDispatch->cmdBeginRenderPass(
                renderCmdBuf, session.renderPass.get(), session.framebuffer.get(),
                {{0, 0}, {session.framebuffer_size.width, session.framebuffer_size.height}}, 1,
                &clearColor, VK_SUBPASS_CONTENTS_INLINE);
        if (!renderPassEnder) {
            return FAILURE_STR("cmdBeginRenderPass", VK_NULL_HANDLE);
        }

        mDeviceDispatch->cmdBindPipeline(renderCmdBuf, VK_PIPELINE_BIND_POINT_GRAPHICS,
                                         session.pipeline.get());
        mDeviceDispatch->cmdBindDescriptorSets(renderCmdBuf, VK_PIPELINE_BIND_POINT_GRAPHICS,
                                               mPipelineLayout.get(), 0, 1, &mDescriptorSet, 0,
                                               nullptr);

        const VkBuffer rawVerticesBuf = mVerticesBuf.get();
        const VkDeviceSize vertexOffset = 0;
        mDeviceDispatch->cmdBindVertexBuffers(renderCmdBuf, 0, 1, &rawVerticesBuf, &vertexOffset);
        mDeviceDispatch->cmdBindIndexBuffer(renderCmdBuf, mIndicesBuf.get(), 0,
                                            VK_INDEX_TYPE_UINT32);

        mDeviceDispatch->cmdDrawIndexed(renderCmdBuf, std::size(kTriangeIndices), 1, 0, 0, 0);
    }

    std::vector<VkImageMemoryBarrier> changeImageLayoutBarriers;
    changeImageLayoutBarriers.reserve(scisSize + 1);  // plus the framebuffer

    for (unsigned i = 0; i < scisSize; ++i) {
        const CameraImageProviderStreamCaptureInfo& sci = scis[i];
        const CaptureStreamBuffers* bufs =
                findCaptureStreamBuffers(sci.cfg->id, session.captureStreamBuffers.data(),
                                         session.captureStreamBuffers.size());
        if (!bufs) {
            continue;
        }

        if (bufs->gpuImage) {
            const VkImageBlit imageBlitRegion = {
                .srcSubresource =
                        {
                            .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                            .mipLevel = 0,
                            .baseArrayLayer = 0,
                            .layerCount = 1,
                        },
                .srcOffsets = {{0, 0, 0},
                               {static_cast<int32_t>(session.framebuffer_size.width),
                                static_cast<int32_t>(session.framebuffer_size.height), 1}},
                .dstSubresource =
                        {
                            .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                            .mipLevel = 0,
                            .baseArrayLayer = 0,
                            .layerCount = 1,
                        },
                .dstOffsets = {{0, 0, 0},
                               {static_cast<int32_t>(bufs->size.width),
                                static_cast<int32_t>(bufs->size.height), 1}},
            };

            mDeviceDispatch->cmdBlitImage(
                    renderCmdBuf, session.framebufferImage.get(),
                    VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, bufs->gpuImage.get(),
                    VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1, &imageBlitRegion, VK_FILTER_LINEAR);

            const VkImageMemoryBarrier changeGpuStreamImageLayoutBarrier = {
                .sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER,
                .pNext = nullptr,
                .srcAccessMask = 0,
                .dstAccessMask = 0,
                .oldLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
                .newLayout = VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
                .srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED,
                .dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED,
                .image = bufs->gpuImage.get(),
                .subresourceRange =
                        {
                            .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                            .baseMipLevel = 0,
                            .levelCount = 1,
                            .baseArrayLayer = 0,
                            .layerCount = 1,
                        },
            };

            changeImageLayoutBarriers.push_back(changeGpuStreamImageLayoutBarrier);
        }
    }

    if (!changeImageLayoutBarriers.empty()) {
        mDeviceDispatch->cmdPipelineBarrier(renderCmdBuf, VK_PIPELINE_STAGE_TRANSFER_BIT,
                                            VK_PIPELINE_STAGE_TRANSFER_BIT, 0, 0, nullptr, 0,
                                            nullptr, changeImageLayoutBarriers.size(),
                                            changeImageLayoutBarriers.data());
    }

    std::vector<VkBufferMemoryBarrier> dstBuffersReadyBarriers;
    dstBuffersReadyBarriers.reserve(scisSize);

    for (unsigned i = 0; i < scisSize; ++i) {
        const CameraImageProviderStreamCaptureInfo& sci = scis[i];
        const CaptureStreamBuffers* bufs =
                findCaptureStreamBuffers(sci.cfg->id, session.captureStreamBuffers.data(),
                                         session.captureStreamBuffers.size());
        if (!bufs) {
            continue;
        }

        const VkBufferImageCopy copyRegion = {
            .bufferOffset = 0,
            .bufferRowLength = 0,
            .bufferImageHeight = 0,
            .imageSubresource =
                    {
                        .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                        .mipLevel = 0,
                        .baseArrayLayer = 0,
                        .layerCount = 1,
                    },
            .imageOffset = {0, 0, 0},
            .imageExtent =
                    {
                        .width = bufs->size.width,
                        .height = bufs->size.height,
                        .depth = 1,
                    },
        };

        // If `bufs->gpuImage` is empty it means the framebuffer has the same size
        // and format as the destination and we can copy from the framebuffer.
        const VkImage copyFromImage =
                bufs->gpuImage ? bufs->gpuImage.get() : session.framebufferImage.get();

        mDeviceDispatch->cmdCopyImageToBuffer(renderCmdBuf, copyFromImage,
                                              VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
                                              bufs->dstBuffer.get(), 1, &copyRegion);

        const VkBufferMemoryBarrier dstBufferReadyBarrier = {
            .sType = VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER,
            .pNext = nullptr,
            .srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT,
            .dstAccessMask = VK_ACCESS_HOST_READ_BIT,
            .srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED,
            .dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED,
            .buffer = bufs->dstBuffer.get(),
            .offset = 0,
            .size = VK_WHOLE_SIZE,
        };

        dstBuffersReadyBarriers.push_back(dstBufferReadyBarrier);
    }

    // switch streams back to VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL for the next capture
    for (auto& b : changeImageLayoutBarriers) {
        b.srcAccessMask = 0;
        b.dstAccessMask = 0;
        b.oldLayout = VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL;
        b.newLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;
    }

    // switch framebufferImage back to VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL
    const VkImageMemoryBarrier changeframebufferImageLayoutBarrier = {
        .sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER,
        .pNext = nullptr,
        .srcAccessMask = 0,
        .dstAccessMask = 0,
        .oldLayout = VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
        .newLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL,
        .srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED,
        .dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED,
        .image = session.framebufferImage.get(),
        .subresourceRange =
                {
                    .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                    .baseMipLevel = 0,
                    .levelCount = 1,
                    .baseArrayLayer = 0,
                    .layerCount = 1,
                },
    };

    changeImageLayoutBarriers.push_back(std::move(changeframebufferImageLayoutBarrier));

    mDeviceDispatch->cmdPipelineBarrier(
            renderCmdBuf, VK_PIPELINE_STAGE_TRANSFER_BIT, VK_PIPELINE_STAGE_HOST_BIT, 0, 0, nullptr,
            dstBuffersReadyBarriers.size(), dstBuffersReadyBarriers.data(),
            changeImageLayoutBarriers.size(), changeImageLayoutBarriers.data());

    return renderCmdBuf;
}

void VirtualsceneImageProvider::stop() {
    if (mCaptureSession && mDeviceDispatch && mCommandPool) {
        mDeviceDispatch->freeCommandBuffers(mCommandPool.get(), 1, &mCaptureSession->renderCmdBuf);
        mCaptureSession.reset();
    }
}

VirtualsceneImageProvider::~VirtualsceneImageProvider() {
    stop();
}

void* VirtualsceneImageProvider::create(const CameraImageProviderInfo& info) {
    const auto loader = gvk::SystemMetaLoader::get();
    if (!loader) {
        return FAILURE_STR("loader", nullptr);
    }

    const uint32_t istanceVersion = loader->enumerateInstanceVersion();
    if (istanceVersion < VK_MAKE_API_VERSION(0, 1, 1, 0)) {
        return FAILURE_STR("istanceVersion", nullptr);
    }

    const auto instanceDispatch =
            gvk::InstanceDispatch::create(loader, VK_MAKE_API_VERSION(0, 1, 0, 0), "virtualscene");
    if (!instanceDispatch) {
        return FAILURE_STR("instanceDispatch", nullptr);
    }

    const VkPhysicalDevice physicalDevice = gvk::util::SelectPhysicalDevice(
            *instanceDispatch, [](const VkPhysicalDeviceProperties&) { return 1; }, true);
    if (!physicalDevice) {
        return FAILURE_STR("physicalDevice", nullptr);
    }

    const auto maybeDeviceDispatch = gvk::DeviceDispatch::create(
            instanceDispatch, physicalDevice, VK_QUEUE_GRAPHICS_BIT, VK_NULL_HANDLE);
    if (!maybeDeviceDispatch) {
        return FAILURE_STR("maybeDeviceDispatch", nullptr);
    }

    gvk::DeviceDispatch::CreateResult ddCreateResult = std::move(maybeDeviceDispatch.value());
    const gvk::DeviceDispatch::Ptr dd = std::move(ddCreateResult.dispatch);
    if (!dd) {
        return FAILURE_STR("dd", nullptr);
    }

    if (!ddCreateResult.queueLocations.graphics.ok()) {
        return FAILURE_STR("queueLocations.graphics", nullptr);
    }

    const VkQueue graphicsQueue = dd->getDeviceQueue(ddCreateResult.queueLocations.graphics);
    if (!graphicsQueue) {
        return FAILURE_STR("graphicsQueue", nullptr);
    }

    const VkPhysicalDeviceMemoryProperties memoryProperties =
            instanceDispatch->getPhysicalDeviceMemoryProperties(physicalDevice);

    gvk::CommandPool commandPool = dd->createCommandPool(
            VK_COMMAND_POOL_CREATE_TRANSIENT_BIT | VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT,
            ddCreateResult.queueLocations.graphics.familyIndex);
    if (!commandPool) {
        return FAILURE_STR("commandPool", nullptr);
    }

    gvk::DeviceMemory verticesMem;
    gvk::Buffer verticesBuf;
    gvk::DeviceMemory indicesMem;
    gvk::Buffer indicesBuf;

    {
        VkCommandBuffer copyGeometryCmdBuf = VK_NULL_HANDLE;
        if (!dd->allocateCommandBuffers(commandPool.get(), VK_COMMAND_BUFFER_LEVEL_PRIMARY, 1,
                                        &copyGeometryCmdBuf)) {
            return FAILURE_STR("copyGeometryCmdBuf", nullptr);
        }

        auto [verticesSrcMem, verticesSrcBuf, verticesDstMem, verticesDstBuf] =
                gvk::util::createStagingBuffers(*dd, memoryProperties, kTriangeVertices,
                                                sizeof(kTriangeVertices),
                                                VK_BUFFER_USAGE_VERTEX_BUFFER_BIT);
        if (!verticesSrcBuf || !verticesSrcMem || !verticesDstBuf || !verticesDstMem) {
            dd->freeCommandBuffers(commandPool.get(), 1, &copyGeometryCmdBuf);
            return FAILURE_STR(
                    "!verticesSrcBuf || !verticesSrcMem || !verticesDstBuf || !verticesDstMem",
                    nullptr);
        }

        auto [indicesSrcMem, indicesSrcBuf, indicesDstMem, indicesDstBuf] =
                gvk::util::createStagingBuffers(*dd, memoryProperties, kTriangeIndices,
                                                sizeof(kTriangeIndices),
                                                VK_BUFFER_USAGE_INDEX_BUFFER_BIT);
        if (!indicesSrcBuf || !indicesSrcMem || !indicesDstBuf || !indicesDstMem) {
            dd->freeCommandBuffers(commandPool.get(), 1, &copyGeometryCmdBuf);
            return FAILURE_STR(
                    "!indicesSrcBuf || !indicesSrcMem || !indicesDstBuf || !indicesDstMem",
                    nullptr);
        }

        {
            const auto cmdBufEnder = dd->beginCommandBuffer(
                    copyGeometryCmdBuf, VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT);
            if (!cmdBufEnder) {
                dd->freeCommandBuffers(commandPool.get(), 1, &copyGeometryCmdBuf);
                return FAILURE_STR("cmdBufEnder", nullptr);
            }

            dd->cmdCopyBuffer(copyGeometryCmdBuf, verticesSrcBuf.get(), verticesDstBuf.get(),
                              sizeof(kTriangeVertices));
            dd->cmdCopyBuffer(copyGeometryCmdBuf, indicesSrcBuf.get(), indicesDstBuf.get(),
                              sizeof(kTriangeIndices));
        }

        if (!dd->queueSubmit(graphicsQueue, copyGeometryCmdBuf)) {
            dd->freeCommandBuffers(commandPool.get(), 1, &copyGeometryCmdBuf);
            return FAILURE_STR("queueSubmit", nullptr);
        }

        if (!dd->queueWaitIdle(graphicsQueue)) {
            dd->freeCommandBuffers(commandPool.get(), 1, &copyGeometryCmdBuf);
            return FAILURE_STR("queueWaitIdle", nullptr);
        }

        dd->freeCommandBuffers(commandPool.get(), 1, &copyGeometryCmdBuf);

        verticesMem = std::move(verticesDstMem);
        verticesBuf = std::move(verticesDstBuf);
        indicesMem = std::move(indicesDstMem);
        indicesBuf = std::move(indicesDstBuf);
    }

    auto [uniformMem, uniformBuf] = gvk::util::allocateBuffer(
            *dd, memoryProperties, sizeof(UniformBufferData), VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT,
            VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
    if (!uniformMem || !uniformBuf) {
        return FAILURE_STR("!uniformMem || !uniformBuf", nullptr);
    }

    gvk::ShaderModule vertexShaderModule =
            dd->createShaderModule(kVertexShaderSpvBits, sizeof(kVertexShaderSpvBits));
    if (!vertexShaderModule) {
        return FAILURE_STR("vertexShaderModule", nullptr);
    }

    gvk::ShaderModule fragmentShaderModule =
            dd->createShaderModule(kFragmentShaderSpvBits, sizeof(kFragmentShaderSpvBits));
    if (!fragmentShaderModule) {
        return FAILURE_STR("fragmentShaderModule", nullptr);
    }

    const VkDescriptorSetLayoutBinding descriptorSetLayoutBinding = {
        .binding = 0,
        .descriptorType = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
        .descriptorCount = 1,
        .stageFlags = VK_SHADER_STAGE_VERTEX_BIT,
        .pImmutableSamplers = nullptr,
    };

    gvk::DescriptorSetLayout descriptorSetLayout =
            dd->createDescriptorSetLayout(1, &descriptorSetLayoutBinding);
    if (!descriptorSetLayout) {
        return FAILURE_STR("descriptorSetLayout", nullptr);
    }

    const VkDescriptorSetLayout descriptorSetLayoutRaw = descriptorSetLayout.get();

    const VkDescriptorPoolSize uniformDescriptorCount = {
        .type = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
        .descriptorCount = 1,
    };

    gvk::DescriptorPool descriptorPool = dd->createDescriptorPool(0, 1, 1, &uniformDescriptorCount);
    if (!descriptorPool) {
        return FAILURE_STR("descriptorPool", nullptr);
    }

    gvk::PipelineLayout pipelineLayout = dd->createPipelineLayout(1, &descriptorSetLayoutRaw);
    if (!pipelineLayout) {
        return FAILURE_STR("pipelineLayout", nullptr);
    }

    VkDescriptorSet descriptorSet = VK_NULL_HANDLE;
    if (!dd->allocateDescriptorSets(descriptorPool.get(), 1, &descriptorSetLayoutRaw,
                                    &descriptorSet)) {
        return FAILURE_STR("descriptorSet", nullptr);
    }

    const VkDescriptorBufferInfo descriptorBufferInfo = {
        .buffer = uniformBuf.get(),
        .offset = 0,
        .range = sizeof(UniformBufferData),
    };

    const VkWriteDescriptorSet writeDescriptorSet = {
        .sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET,
        .pNext = nullptr,
        .dstSet = descriptorSet,
        .dstBinding = 0,
        .dstArrayElement = 0,
        .descriptorCount = 1,
        .descriptorType = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
        .pImageInfo = nullptr,
        .pBufferInfo = &descriptorBufferInfo,
        .pTexelBufferView = nullptr,
    };

    dd->updateDescriptorSets(1, &writeDescriptorSet, 0, nullptr);

    auto imageProvider = std::make_unique<VirtualsceneImageProvider>();

    imageProvider->mDeviceDispatch = std::move(dd);
    imageProvider->mCommandPool = std::move(commandPool);
    imageProvider->mVerticesMem = std::move(verticesMem);
    imageProvider->mIndicesMem = std::move(indicesMem);
    imageProvider->mUniformMem = std::move(uniformMem);
    imageProvider->mVerticesBuf = std::move(verticesBuf);
    imageProvider->mIndicesBuf = std::move(indicesBuf);
    imageProvider->mUniformBuf = std::move(uniformBuf);
    imageProvider->mVertexShaderModule = std::move(vertexShaderModule);
    imageProvider->mFragmentShaderModule = std::move(fragmentShaderModule);
    imageProvider->mDescriptorSetLayout = std::move(descriptorSetLayout);
    imageProvider->mDescriptorPool = std::move(descriptorPool);
    imageProvider->mPipelineLayout = std::move(pipelineLayout);
    imageProvider->mDescriptorSet = descriptorSet;

    imageProvider->mGraphicsQueue = graphicsQueue;
    imageProvider->mMemoryProperties = memoryProperties;
    imageProvider->mGraphicsQueueLocation = ddCreateResult.queueLocations.graphics;

    return imageProvider.release();
}

}  // namespace goldfish::camera_image_providers::virtualscene
