load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")
load("@rules_python//python:defs.bzl", "py_binary")

py_binary(
    name = "gen-hw-config",
    srcs = ["src/android/goldfish/config/gen-hw-config.py"],
)

# TODO(jansene): Port to host-common.
genrule(
    name = "hw-config-gen",
    srcs = ["data/hardware-properties.ini"],
    outs = ["include/avd/hw-config-defs.h"],
    cmd = "$(location :gen-hw-config) $(location data/hardware-properties.ini) $(location include/avd/hw-config-defs.h)",
    tools = [":gen-hw-config"],
)

cc_library(
    name = "config_dirs",
    srcs = ["src/android/goldfish/config/config_dirs.cpp"],
    hdrs = ["include/android/goldfish/config/config_dirs.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//hardware/generic/goldfish/android/system",
        "@abseil-cpp//absl/log",
        "@aemu//base:aemu-base",
    ],
)

cc_library(
    name = "hardware_config",
    srcs = [
        "src/android/goldfish/config/hardware_config.cpp",
        ":hw-config-gen",
    ],
    hdrs = ["include/android/goldfish/config/hardware_config.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//hardware/generic/goldfish/android/files",
        "@aemu//base:aemu-base",
    ],
)

cc_library(
    name = "emulator_advertisement",
    srcs = ["src/android/goldfish/config/emulator_advertisement.cpp"],
    hdrs = ["include/android/goldfish/config/emulator_advertisment.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":config_dirs",
        "//hardware/generic/goldfish/android/files",
        "//hardware/generic/goldfish/android/sockets",
        "@aemu//base:aemu-base",
    ],
)

cc_library(
    name = "avd",
    srcs = [
        "src/android/goldfish/config/avd.cpp",
        "src/android/goldfish/config/keys.h",
    ],
    hdrs = [
        "include/android/goldfish/config/avd.h",
        "include/android/goldfish/config/image_list.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":config_dirs",
        ":hardware_config",
        "//hardware/generic/goldfish/android/files",
        "//hardware/generic/goldfish/emulator/launcher:input_paths",
        "@abseil-cpp//absl/container:flat_hash_map",
        "@abseil-cpp//absl/log",
        "@aemu//base:aemu-base",
    ],
)

cc_library(
    name = "avd-test",
    testonly = True,
    hdrs = [
        "test/android/goldfish/config/avd-test.h",
        "test/android/goldfish/config/fake-avd.h",
    ],
    includes = ["test"],
    visibility = ["//visibility:public"],
    deps = [
        ":avd",
        "//hardware/generic/goldfish/android/system",
        "//hardware/generic/goldfish/android/system:test-headers",
        "@abseil-cpp//absl/status:status_matchers",
        "@googletest//:gtest",
    ],
)

cc_test(
    name = "config_unittests",
    size = "small",
    srcs = [
        "test/android/goldfish/config/avd_unittest.cpp",
        "test/android/goldfish/config/config_dirs_unittest.cpp",
    ],
    linkopts = select({
        "@platforms//os:macos": ["-undefined error"],
        "//conditions:default": [],
    }),
    deps = [
        ":avd",
        ":avd-test",
        "//hardware/generic/goldfish/android/system",
        "//hardware/generic/goldfish/android/system:googletest_main",
        "//hardware/generic/goldfish/android/system:test-headers",
        "@abseil-cpp//absl/status:status_matchers",
    ],
)
