load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "input",
    srcs = [
        "src/EventSender.cpp",
        "src/PointerEventDispatcher.cpp",
        "src/SlotRegistry.cpp",
    ],
    hdrs = [
        "include/android/emulation/control/input/EvDevEvent.h",
        "include/android/emulation/control/input/EventSender.h",
        "include/android/emulation/control/input/PointerEventDispatcher.h",
        "include/android/emulation/control/input/SlotRegistry.h",
    ],
    includes = [
        "include",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//hardware/generic/goldfish/emulator/devices:connector_registry_hdrs",
        "//hardware/generic/goldfish/emulator/grpc/services/emulator_controller/proto:emulator_controller_cc_grpc",
        "//hardware/generic/goldfish/emulator/hal/display:headers",
        "//third_party/qemu:qemu-headers",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@aemu//base:aemu-base",
    ],
)

cc_test(
    name = "input_unittests",
    srcs = [
        "test/PointerEventDispatcher-unittest.cpp",
        "test/SlotRegistry-unittest.cpp",
    ],
    deps = [
        ":input",
        "//hardware/generic/goldfish/android/async:async_testing",
        "//hardware/generic/goldfish/android/files",
        "//hardware/generic/goldfish/android/logging:backend",
        "//hardware/generic/goldfish/android/system:googletest_main",
        "//hardware/generic/goldfish/android/system:test-headers",
        "//hardware/generic/goldfish/emulator/grpc/event-stream",
        "//hardware/generic/goldfish/emulator/hal/display:test-display",
        "@abseil-cpp//absl/flags:flag",
        "@abseil-cpp//absl/flags:parse",
        "@bazel_tools//tools/cpp/runfiles",
    ],
)
