load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "input",
    srcs = [
        "event_sender.cc",
        "pointer_event_dispatcher.cc",
        "slot_registry.cc",
    ],
    hdrs = [
        "include/android/emulation/control/ev_dev_event.h",
        "include/android/emulation/control/event_sender.h",
        "include/android/emulation/control/internal/pointer_event_dispatcher.h",
        "include/android/emulation/control/slot_registry.h",
    ],
    includes = [
        "include",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//emulator/grpc/services/emulator_controller:emulator_controller_cc_grpc",
        "//emulator/libs/display",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@aemu//base:aemu-base",
        "@qemu//:qemu-headers",
    ],
)

cc_test(
    name = "input_unittests",
    srcs = [
        "pointer_event_dispatcher_test.cc",
        "slot_registry_test.cc",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":input",
        "//android/async:async_testing",
        "//android/system:googletest_main",
        "//android/system:test-headers",
        "//emulator/grpc/event-stream",
        "//emulator/libs/display:test-display",
        "//emulator/plugin/avd:info-fake",
        "@abseil-cpp//absl/flags:flag",
        "@abseil-cpp//absl/flags:parse",
        "@bazel_tools//tools/cpp/runfiles",
    ],
)
