load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "adb-vsock",
    srcs = ["adb-device.cpp"],
    hdrs = ["include/goldfish/adb/adb-device.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//emulator/adb/host",
        "//emulator/adb/logger",
        "//emulator/plugin/avd:impl",
        "//emulator/plugin/vsock_goldfish:goldfish_vsock_hdrs",
    ],
)
