load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "adb-vsock",
    srcs = ["adb_device.cc"],
    hdrs = ["include/goldfish/adb_device/adb_device.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//emulator/plugin/adb-vsock/host",
        "//emulator/plugin/adb-vsock/logger",
        "//emulator/plugin/avd:impl",
        "//emulator/plugin/vsock_goldfish:goldfish_vsock_hdrs",
    ],
)
