load("@goldfish_build//rules:clang_tidy.bzl", "clang_tidy_test")
load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "logging_interceptor",
    srcs = ["logging_interceptor.cc"],
    hdrs = ["include/android/control/interceptor/logging_interceptor.h"],
    includes = ["include"],
    deps = [
        "//emulator/libs/system:clock",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/time",
        "@grpc//:grpc++",
        "@protobuf",
    ],
)

cc_library(
    name = "breadcrumb_interceptor",
    srcs = ["breadcrumb_interceptor.cc"],
    hdrs = ["include/android/control/interceptor/breadcrumb_interceptor.h"],
    includes = ["include"],
    deps = [
        "//emulator/crashreport:breadcrumb_proto",
        "//emulator/libs/proto_data_store",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/time",
        "@aemu//protos/services/diagnostic:breadcrumb_cc_proto",
        "@aemu//protos/services/diagnostic:grpc_diagnostic_cc_proto",
        "@goldfish//emulator/crashreport:crash_reporter",
        "@grpc//:grpc++",
        "@zlib",
    ],
)

cc_library(
    name = "idle_interceptor",
    srcs = ["idle_interceptor.cc"],
    hdrs = ["include/android/control/interceptor/idle_interceptor.h"],
    includes = ["include"],
    deps = [
        "//emulator/libs/async:async_api",
        "//emulator/libs/process",
        "//emulator/libs/system:clock",
        "@abseil-cpp//absl/time",
        "@grpc//:grpc++",
    ],
)

cc_library(
    name = "perfetto_interceptor",
    srcs = ["perfetto_interceptor.cc"],
    hdrs = ["include/android/control/interceptor/perfetto_interceptor.h"],
    includes = ["include"],
    deps = [
        "//emulator/libs/perfetto:init",
        "@grpc//:grpc++",
    ],
)

# collection of all interceptors for convenience
cc_library(
    name = "interceptors",
    visibility = ["//visibility:public"],
    deps = [
        ":breadcrumb_interceptor",
        ":idle_interceptor",
        ":logging_interceptor",
        ":metrics_interceptor",
        ":perfetto_interceptor",
    ],
)

cc_library(
    name = "percentiles",
    srcs = ["percentiles.cc"],
    hdrs = ["include/android/control/interceptor/percentiles.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = ["@abseil-cpp//absl/log:check"],
)

cc_test(
    name = "percentiles_test",
    srcs = ["percentiles_test.cc"],
    deps = [
        ":percentiles",
        "//emulator/libs/test:googletest_main",
        "@googletest//:gtest",
    ],
)

cc_library(
    name = "metrics_interceptor",
    srcs = ["metrics_interceptor.cc"],
    hdrs = ["include/android/control/interceptor/metrics_interceptor.h"],
    includes = ["include"],
    deps = [
        ":logging_interceptor",
        ":percentiles",
        "//emulator/libs/metrics",
        "//emulator/plugin/avd:info",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/synchronization",
        "@zlib",
    ],
)

cc_test(
    name = "metrics_interceptor_test",
    srcs = ["metrics_interceptor_test.cc"],
    visibility = ["//visibility:public"],
    deps = [
        ":metrics_interceptor",
        "//emulator/libs/test:googletest_main",
        "@googletest//:gtest",
    ],
)

cc_test(
    name = "interceptors_test",
    srcs =
        select({
            "@platforms//os:windows": [],
            "//conditions:default": [
                "breadcrumb_interceptor_test.cc",
                "logging_interceptor_test.cc",
                "perfetto_interceptor_test.cc",
            ],
        }),
    visibility = ["//visibility:public"],
    deps = [
        ":interceptors",
        "//emulator/libs/async:async_testing",
        "//emulator/libs/system:test-headers",
        "//emulator/libs/test:googletest_main",
        "//emulator/plugin/vminterface:vminterface-test",
        "@aemu//protos/services/diagnostic:grpc_diagnostic_cc_proto",
        "@aemu//protos/services/emulator-controller:emulator_controller_cc_proto",
        "@googletest//:gtest",
    ],
)

cc_test(
    name = "perfetto_interceptor_only_test",
    srcs = ["perfetto_interceptor_test.cc"],
    deps = [
        ":perfetto_interceptor",
        "//emulator/libs/system:test-headers",
        "//emulator/libs/test:googletest_main",
        "@googletest//:gtest",
    ],
)

clang_tidy_test(
    name = "tidy",
    targets = [
        ":interceptors",
    ],
    tidy_config_file = "//:clang_tidy_config",
)
