load("@goldfish_build//rules:clang_tidy.bzl", "clang_tidy_test")
load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "physical_model",
    srcs = [
        "foldable_model.cc",
        "physical_model.cc",
    ],
    hdrs = [
        "include/goldfish/sensors/android_sensor.h",
        "include/goldfish/sensors/foldable.h",
        "include/goldfish/sensors/foldable_model.h",
        "include/goldfish/sensors/goldfish_physical_parameters_list.h",
        "include/goldfish/sensors/goldfish_sensors_list.h",
        "include/goldfish/sensors/physical_model.h",
        "include/goldfish/sensors/physical_parameter.h",
        "include/goldfish/sensors/sensor_data.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//emulator/config:hardware_config",
        "//emulator/libs/eventing",
        "//emulator/libs/physics",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:check",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
        "@aemu//base:aemu-base-headers",
        "@gfxstream//third_party/glm",
    ],
    alwayslink = True,
)

cc_test(
    name = "physical_model_test",
    srcs = ["physical_model_test.cc"],
    includes = ["test"],
    visibility = ["//visibility:public"],
    deps = [
        ":physical_model",
        "//android/system:googletest_main",
        "//emulator/config:fake_hardware_config",
    ],
)

clang_tidy_test(
    name = "tidy",
    targets = [
        ":physical_model",
    ],
    tidy_config_file = "//:clang_tidy_config",
)
