cc_library(
    name = "secrets",
    srcs = glob([
        "src/**/*.cpp",
    ]),
    hdrs = glob([
        "include/**/*.h",
    ]),
    includes = [
        "include",
        "src",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//external/boringssl:ssl",
        "//hardware/generic/goldfish/android/files",
        "//hardware/generic/goldfish/files",
        "//hardware/generic/goldfish/system",
        "//hardware/google/aemu/base:aemu-base",
        "@com_google_absl//absl/strings",
        "@com_google_absl//absl/strings:str_format",
    ],
)

cc_test(
    name = "secrets_unnitests",
    srcs = glob(
        [
            "test/**/*.cpp",
            "test/**/*.h",
        ],
        exclude = ["test/**/Win32"],
    ),
    deps = [
        ":secrets",
        "//hardware/generic/goldfish/system:test-headers",
        "@com_google_googletest//:gtest_main",
    ],
)
