load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = [
    "//emulator/hal:__subpackages__",
    "//emulator/plugin/avd:__subpackages__",
])

cc_library(
    name = "emulator_reset",
    hdrs = ["include/goldfish/hal/common/emulator_reset.h"],
    strip_include_prefix = "include",
)
