load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")
load("@rules_pkg//pkg:mappings.bzl", "pkg_files")

package(default_visibility = ["//hardware/generic/goldfish/emulator/grpc:__subpackages__"])

pkg_files(
    name = "emulator-access",
    srcs = [
        "src/android/emulation/control/secure/emulator_access.json",
    ],
    prefix = "lib",
    visibility = ["//visibility:public"],
)

filegroup(
    name = "unsecure-emulator-access",
    data = [
        "test/android/emulation/control/secure/test_allow_list.json",
    ],
    output_group = "",
    tags = [""],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "security",
    srcs = [
        "src/android/emulation/control/secure/AllowList.cpp",
        "src/android/emulation/control/secure/AuthErrorFactory.cpp",
        "src/android/emulation/control/secure/BasicTokenAuth.cpp",
        "src/android/emulation/control/secure/JwkDirectoryObserver.cpp",
        "src/android/emulation/control/secure/JwkKeyLoader.cpp",
        "src/android/emulation/control/secure/JwtTokenAuth.cpp",
    ],
    hdrs = [
        "include/android/emulation/control/secure/AllowList.h",
        "include/android/emulation/control/secure/AuthErrorFactory.h",
        "include/android/emulation/control/secure/BasicTokenAuth.h",
        "include/android/emulation/control/secure/JwkDirectoryObserver.h",
        "include/android/emulation/control/secure/JwkKeyLoader.h",
        "include/android/emulation/control/secure/JwtTokenAuth.h",
    ],
    includes = ["include"],
    deps = [
        "//hardware/generic/goldfish/android/files",
        "//hardware/generic/goldfish/android/system",
        "//hardware/generic/goldfish/emulator/grpc/async",
        "//hardware/generic/goldfish/third_party/json",
        "@aemu//base:aemu-base",
        "@grpc//:grpc++",
        "@re2",
        "@tink_cc//tink:tink_cc",
        "@tink_cc//tink/jwt:jwk_set_converter",
        "@tink_cc//tink/jwt:jwt_public_key_verify",
        "@tink_cc//tink/jwt:jwt_signature_config",
    ],
)

cc_test(
    name = "security-test",
    size = "small",
    timeout = "short",
    srcs = [
        "test/android/emulation/control/secure/AllowList_unittest.cpp",
        "test/android/emulation/control/secure/AuthErrorFactory_unittest.cpp",
        "test/android/emulation/control/secure/JwkDirectoryObserver_unittest.cpp",
        "test/android/emulation/control/secure/JwkKeyLoader_unittest.cpp",
        "test/android/emulation/control/secure/JwtTokenAuth_unittest.cpp",
    ],
    copts = ["-Wno-deprecated-declarations"],
    data = ["src/android/emulation/control/secure/emulator_access.json"],
    deps = [
        ":security",
        "//hardware/generic/goldfish/android/system",
        "//hardware/generic/goldfish/android/system:googletest_main",
        "//hardware/generic/goldfish/android/system:test-headers",
        "@googletest//:gtest",
        "@tink_cc//tink/jwt:jwt_key_templates",
    ],
)
