load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")
load("@rules_pkg//pkg:mappings.bzl", "pkg_files")

package(default_visibility = ["//emulator/grpc:__subpackages__"])

pkg_files(
    name = "emulator-access",
    srcs = [
        "src/android/emulation/control/secure/emulator_access.json",
    ],
    prefix = "lib",
    visibility = ["//visibility:public"],
)

filegroup(
    name = "unsecure-emulator-access",
    data = [
        "test/android/emulation/control/secure/test_allow_list.json",
    ],
    output_group = "",
    tags = [""],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "security",
    srcs = [
        "src/android/emulation/control/secure/allow_list.cpp",
        "src/android/emulation/control/secure/auth_error_factory.cpp",
        "src/android/emulation/control/secure/basic_token_auth.cpp",
        "src/android/emulation/control/secure/jwk_directory_observer.cpp",
        "src/android/emulation/control/secure/jwk_key_loader.cpp",
        "src/android/emulation/control/secure/jwt_token_auth.cpp",
    ],
    hdrs = [
        "include/android/emulation/control/secure/allow_list.h",
        "include/android/emulation/control/secure/auth_error_factory.h",
        "include/android/emulation/control/secure/basic_token_auth.h",
        "include/android/emulation/control/secure/jwk_directory_observer.h",
        "include/android/emulation/control/secure/jwk_key_loader.h",
        "include/android/emulation/control/secure/jwt_token_auth.h",
    ],
    includes = ["include"],
    deps = [
        "//android/files",
        "//android/system",
        "//emulator/grpc/async",
        "@aemu//base:aemu-base",
        "@grpc//:grpc++",
        "@nlohmann_json//:singleheader-json",
        "@re2",
        "@tink_cc//tink:tink_cc",
        "@tink_cc//tink/jwt:jwk_set_converter",
        "@tink_cc//tink/jwt:jwt_public_key_verify",
        "@tink_cc//tink/jwt:jwt_signature_config",
    ],
)

cc_test(
    name = "security-test",
    size = "small",
    timeout = "short",
    srcs = [
        "test/android/emulation/control/secure/allow_list_unittest.cpp",
        "test/android/emulation/control/secure/auth_error_factory_unittest.cpp",
        "test/android/emulation/control/secure/jwk_directory_observer_unittest.cpp",
        "test/android/emulation/control/secure/jwk_key_loader_unittest.cpp",
        "test/android/emulation/control/secure/jwt_token_auth_unittest.cpp",
    ],
    copts = ["-Wno-deprecated-declarations"],
    data = ["src/android/emulation/control/secure/emulator_access.json"],
    deps = [
        ":security",
        "//android/system",
        "//android/system:googletest_main",
        "//android/system:test-headers",
        "@googletest//:gtest",
        "@tink_cc//tink/jwt:jwt_key_templates",
    ],
)
