load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

# This is quite an old c-style command line parsing library written around 2008
cc_library(
    name = "cmdline",
    srcs = [
        "cmdline_option.cc",
        "constants.c",
        "help.cc",
        "main_help.cc",
        "misc.cc",
        "stralloc.cc",
    ],
    hdrs = [
        "include/android/cmdline_definitions.h",
        "include/android/cmdline_option.h",
        "include/android/cmdline_options.h",
        "include/android/help.h",
        "include/android/main_help.h",
        "include/android/network/constants.h",
        "include/android/utils/misc.h",
        "include/android/utils/stralloc.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//emulator/launcher:config_dirs",
        "//emulator/libs/base:array_size",
        "//emulator/libs/host-common",
        "//emulator/libs/logging:absl_c_bridge",
        "//emulator/libs/system",
    ],
)

cc_test(
    name = "cmdline_unittests",
    srcs = [
        "cmdline_option_test.cc",
        "constants_test.cc",
        "test/android/emulation/testing/temporary_command_line_options.h",
    ],
    includes = ["test"],
    visibility = ["//visibility:public"],
    deps = [
        ":cmdline",
        "//emulator/libs/system:test-headers",
        "//emulator/libs/test:googletest_main",
    ],
)
