load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

package(default_visibility = ["//visibility:public"])

alias(
    name = "grpc_endpoint_description_proto",
    actual = "@aemu//protos/client:grpc_endpoint_description_proto",
)

alias(
    name = "grpc_endpoint_description_cc_proto",
    actual = "@aemu//protos/client:grpc_endpoint_description_cc_proto",
)

cc_library(
    name = "emulator_grpc_client",
    srcs = [
        "emulator_grpc_client.cc",
        "grpc_channel_factory.cc",
        "grpc_channel_factory.h",
        "grpc_connection_monitor.cc",
        "grpc_connection_monitor.h",
    ],
    hdrs = ["include/android/emulation/control/emulator_grpc_client.h"],
    includes = ["include"],
    deps = [
        "//android/files:ini_file",
        "//emulator/grpc/client:grpc_endpoint_description_cc_proto",
        "//emulator/grpc/security",
        "//emulator/grpc/services/emulator_controller:emulator_controller_cc_grpc",
        "//emulator/libs/eventing",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/synchronization",
        "@abseil-cpp//absl/time",
        "@grpc//:grpc++",
    ],
)

cc_test(
    name = "emulator_grpc_client_test",
    srcs = ["emulator_grpc_client_test.cc"],
    visibility = ["//visibility:public"],
    deps = [
        ":emulator_grpc_client",
        "//android/sockets",
        "//android/system:googletest_main",
        "//emulator/grpc/services/emulator_controller:emulator_controller_cc_grpc",
        "@abseil-cpp//absl/random",
        "@abseil-cpp//absl/synchronization",
        "@grpc//:grpc++",
    ],
)
