load("@protobuf//bazel:cc_proto_library.bzl", "cc_proto_library")
load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")
load("@rules_proto//proto:defs.bzl", "proto_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "grpc_endpoint_description_proto",
    srcs = ["proto/grpc_endpoint_description.proto"],
    strip_import_prefix = "proto",
    deps = ["@protobuf//:empty_proto"],
)

cc_proto_library(
    name = "grpc_endpoint_description_cc_proto",
    deps = [":grpc_endpoint_description_proto"],
)

cc_library(
    name = "emulator_grpc_client",
    srcs = [
        "src/emulator_grpc_client.cpp",
        "src/grpc_channel_factory.cpp",
        "src/grpc_channel_factory.h",
        "src/grpc_connection_monitor.cpp",
        "src/grpc_connection_monitor.h",
    ],
    hdrs = [
        "include/android/emulation/control/utils/emulator_grpc_client.h",
    ],
    includes = [
        "include",
    ],
    deps = [
        "//android/files",
        "//emulator/grpc/client:grpc_endpoint_description_cc_proto",
        "//emulator/grpc/security",
        "//emulator/grpc/services/emulator_controller:emulator_controller_cc_grpc",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/synchronization",
        "@abseil-cpp//absl/time",
        "@aemu//base:event-support",
        "@grpc//:grpc++",
    ],
)

cc_test(
    name = "emulator_grpc_client_test",
    srcs = ["tests/emulator_grpc_client_test.cpp"],
    deps = [
        ":emulator_grpc_client",
        "//android/sockets",
        "//android/system:googletest_main",
        "//emulator/grpc/services/emulator_controller:emulator_controller_cc_grpc",
        "@abseil-cpp//absl/random",
        "@abseil-cpp//absl/synchronization",
        "@grpc//:grpc++",
    ],
)
