load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")

cc_library(
    name = "process",
    srcs = [
        "command.cc",
        "exec.cc",
        "exec.h",
    ] + select({
        "@platforms//os:windows": [
            "command_windows.cc",
        ],
        "//conditions:default": [
            "command_posix.cc",
        ],
    }),
    hdrs = [
        "include/android/process/command.h",
        "include/android/process/process.h",
    ],
    copts = select({
        "@platforms//os:windows": [
            "-Wno-vla-cxx-extension",
        ],
        "//conditions:default": [],
    }),
    includes = ["include"],
    tags = ["no-tidy"],
    visibility = ["//visibility:public"],
    deps = select({
        "@platforms//os:windows": [
            "//emulator/libs/windows:scoped_file_handle",
            # For unicode.
            "//emulator/libs/windows:win32_utils",
        ],
        "//conditions:default": [],
    }) + [
        "//emulator/libs/file",
        "//emulator/libs/stream",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/synchronization",
    ],
)

cc_binary(
    name = "sleep_emu",
    srcs = ["sleep.cc"],
    deps = [
        "@abseil-cpp//absl/flags:flag",
        "@abseil-cpp//absl/flags:parse",
    ],
)

cc_test(
    name = "process_unittests",
    srcs = ["command_test.cc"],
    data = [
        ":sleep_emu",
        "//emulator/crashreport:crash-me",
    ],
    linkopts = select({
        "@platforms//os:macos": ["-undefined error"],
        "//conditions:default": [],
    }),
    visibility = ["//visibility:public"],
    deps = [
        ":process",
        "//emulator/libs/system:bazel_info",
        "//emulator/libs/system:test-headers",
        "//emulator/libs/test:googletest_main",
        "@abseil-cpp//absl/flags:flag",
        "@abseil-cpp//absl/flags:parse",
    ],
)
