load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "device",
    hdrs = ["device.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = ["//emulator/launcher:emulator_config"],
)

cc_library(
    name = "mock_avd",
    testonly = True,
    hdrs = ["mock_avd.h"],
    include_prefix = "android/goldfish/devices/",
    visibility = ["//visibility:public"],
    deps = ["//emulator/launcher:avd"],
)

cc_library(
    name = "fake_emulator",
    testonly = True,
    hdrs = ["fake_emulator.h"],
    include_prefix = "android/goldfish/devices/",
    visibility = ["//visibility:public"],
    deps = [":mock_avd"],
)

cc_library(
    name = "audio_device",
    srcs = ["audio_device.cc"],
    hdrs = ["audio_device.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":device",
        "//emulator/libs/base",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@aemu//base:aemu-base",
    ],
)

cc_library(
    name = "adb_device",
    srcs = ["adb_device.cc"],
    hdrs = ["adb_device.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":device",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/strings",
    ],
)

cc_test(
    name = "adb_device_test",
    srcs = ["adb_device_test.cc"],
    visibility = ["//visibility:public"],
    deps = [
        ":adb_device",
        ":device",
        ":fake_emulator",
        "//android/system:googletest_main",
        "//android/system:test-headers",
        "@abseil-cpp//absl/status:status_matchers",
        "@abseil-cpp//absl/strings",
    ],
)

cc_library(
    name = "avd_info_device",
    srcs = ["avd_info_device.cc"],
    hdrs = ["avd_info_device.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":device",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/strings",
    ],
)

cc_test(
    name = "avd_info_device_test",
    srcs = ["avd_info_device_test.cc"],
    visibility = ["//visibility:public"],
    deps = [
        ":avd_info_device",
        ":device",
        ":fake_emulator",
        "//android/system:googletest_main",
        "//android/system:test-headers",
        "@abseil-cpp//absl/status:status_matchers",
        "@abseil-cpp//absl/strings",
    ],
)

cc_library(
    name = "cpu_device",
    srcs = ["cpu_device.cc"],
    hdrs = ["cpu_device.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":device",
        "//android/cpu",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@aemu//base:aemu-base",
    ],
)

cc_test(
    name = "cpu_device_test",
    srcs = ["cpu_device_test.cc"],
    visibility = ["//visibility:public"],
    deps = [
        ":cpu_device",
        ":device",
        ":fake_emulator",
        "//android/system:googletest_main",
        "//android/system:test-headers",
        "@abseil-cpp//absl/status:status_matchers",
        "@abseil-cpp//absl/strings",
    ],
)

cc_library(
    name = "display_device",
    srcs = ["display_device.cc"],
    hdrs = ["display_device.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":device",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/strings",
    ],
)

cc_test(
    name = "display_device_test",
    srcs = ["display_device_test.cc"],
    visibility = ["//visibility:public"],
    deps = [
        ":device",
        ":display_device",
        ":fake_emulator",
        "//android/system:googletest_main",
        "//android/system:test-headers",
        "@abseil-cpp//absl/status:status_matchers",
        "@abseil-cpp//absl/strings",
    ],
)

cc_library(
    name = "gpu_device",
    srcs = ["gpu_device.cc"],
    hdrs = ["gpu_device.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":device",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@aemu//base:aemu-base",
    ],
)

cc_library(
    name = "grpc_device",
    srcs = ["grpc_device.cc"],
    hdrs = ["grpc_device.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":device",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@aemu//base:aemu-base",
    ],
)

cc_test(
    name = "grpc_device_test",
    srcs = ["grpc_device_test.cc"],
    data = ["//emulator/launcher:unsecure-emulator-access"],
    visibility = ["//visibility:public"],
    deps = [
        ":device",
        ":fake_emulator",
        ":grpc_device",
        "//android/system:googletest_main",
        "//android/system:test-headers",
        "@abseil-cpp//absl/status:status_matchers",
        "@abseil-cpp//absl/strings",
    ],
)

cc_library(
    name = "initrd_device",
    srcs = ["initrd_device.cc"],
    hdrs = ["initrd_device.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":device",
        ":disk_drive",
        "//emulator/adb/secrets",
        "//emulator/launcher:bootconfig",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@aemu//base:aemu-base",
    ],
)

cc_test(
    name = "initrd_device_test",
    srcs = ["initrd_device_test.cc"],
    visibility = ["//visibility:public"],
    deps = [
        ":device",
        ":fake_emulator",
        ":initrd_device",
        "//android/system:googletest_main",
        "//android/system:test-headers",
        "@abseil-cpp//absl/status:status_matchers",
        "@abseil-cpp//absl/strings",
    ],
)

cc_library(
    name = "kernel_device",
    srcs = ["kernel_device.cc"],
    hdrs = ["kernel_device.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":device",
        "@abseil-cpp//absl/container:btree",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@aemu//base:aemu-base",
    ],
)

cc_test(
    name = "kernel_device_test",
    srcs = ["kernel_device_test.cc"],
    visibility = ["//visibility:public"],
    deps = [
        ":device",
        ":fake_emulator",
        ":kernel_device",
        "//android/system:googletest_main",
        "//android/system:test-headers",
        "@abseil-cpp//absl/status:status_matchers",
        "@abseil-cpp//absl/strings",
    ],
)

cc_library(
    name = "machine",
    srcs = ["machine.cc"],
    hdrs = ["machine.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":device",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@aemu//base:aemu-base",
    ],
)

cc_test(
    name = "machine_test",
    srcs = ["machine_test.cc"],
    visibility = ["//visibility:public"],
    deps = [
        ":device",
        ":fake_emulator",
        ":machine",
        "//android/system:googletest_main",
        "//android/system:test-headers",
        "@abseil-cpp//absl/status:status_matchers",
        "@abseil-cpp//absl/strings",
    ],
)

cc_library(
    name = "memory_device",
    srcs = ["memory_device.cc"],
    hdrs = ["memory_device.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":device",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@aemu//base:aemu-base",
    ],
)

cc_test(
    name = "memory_device_test",
    srcs = ["memory_device_test.cc"],
    visibility = ["//visibility:public"],
    deps = [
        ":device",
        ":fake_emulator",
        ":memory_device",
        "//android/system:googletest_main",
        "//android/system:test-headers",
        "@abseil-cpp//absl/status:status_matchers",
        "@abseil-cpp//absl/strings",
    ],
)

cc_library(
    name = "network_device",
    srcs = ["network_device.cc"],
    hdrs = ["network_device.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":device",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@aemu//base:aemu-base",
    ],
)

cc_test(
    name = "network_device_test",
    srcs = ["network_device_test.cc"],
    visibility = ["//visibility:public"],
    deps = [
        ":device",
        ":fake_emulator",
        ":network_device",
        "//android/system:googletest_main",
        "//android/system:test-headers",
        "@abseil-cpp//absl/status:status_matchers",
        "@abseil-cpp//absl/strings",
    ],
)

cc_library(
    name = "parameter_list",
    srcs = ["parameter_list.cc"],
    hdrs = ["parameter_list.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":device",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@aemu//base:aemu-base",
    ],
)

cc_library(
    name = "wifi_device",
    srcs = ["wifi_device.cc"],
    hdrs = ["wifi_device.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":device",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@aemu//base:aemu-base",
    ],
)

cc_library(
    name = "user_data_drive",
    srcs = ["user_data_drive.cc"],
    hdrs = ["user_data_drive.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":device",
        "//android/filesystems",
        "//emulator/adb/secrets",
        "//emulator/config:config_dirs",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@aemu//base:aemu-base",
    ],
)

cc_library(
    name = "disk_drive",
    srcs = ["disk_drive.cc"],
    hdrs = ["disk_drive.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":device",
        "//android/filesystems",
        "//android/process",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@aemu//base:aemu-base",
    ],
)

cc_test(
    name = "disk_drive_test",
    srcs = ["disk_drive_test.cc"],
    visibility = ["//visibility:public"],
    deps = [
        ":disk_drive",
        ":fake_emulator",
        "//android/system:googletest_main",
        "//android/system:test-headers",
        "@abseil-cpp//absl/status:status_matchers",
        "@abseil-cpp//absl/strings",
    ],
)
