load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "input",
    srcs = [
        "src/AndroidEventSender.cpp",
        "src/MouseEventSender.cpp",
        "src/PenEventSender.cpp",
        "src/PointerEventDispatcher.cpp",
        "src/SlotRegistry.cpp",
        "src/TouchEventSender.cpp",
        "src/WheelEventSender.cpp",
    ],
    hdrs = [
        "include/android/emulation/control/input/AndroidEventSender.h",
        "include/android/emulation/control/input/EventSender.h",
        "include/android/emulation/control/input/MouseEventSender.h",
        "include/android/emulation/control/input/PenEventSender.h",
        "include/android/emulation/control/input/PointerEventDispatcher.h",
        "include/android/emulation/control/input/SlotRegistry.h",
        "include/android/emulation/control/input/TouchEventSender.h",
        "include/android/emulation/control/input/WheelEventSender.h",
    ],
    includes = [
        "include",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//external/qemu:libmodule-common",
        "//external/qemu:qemu-headers",
        "//hardware/generic/goldfish/emulator/android-grpc/services/emulator-controller/proto:emulator_controller_cc_grpc",
        "//hardware/generic/goldfish/emulator/devices:connector_registry_hdrs",
        "//hardware/generic/goldfish/emulator/hal/display:headers",
        "//hardware/google/aemu/base:aemu-base",
        "@com_google_absl//absl/log",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings",
    ],
)

cc_test(
    name = "input_unittests",
    srcs = [
        "test/PointerEventDispatcher-unittest.cpp",
        "test/SlotRegistry-unittest.cpp",
    ],
    deps = [
        ":input",
        "//hardware/generic/goldfish/android/files",
        "//hardware/generic/goldfish/android/logging:backend",
        "//hardware/generic/goldfish/android/system:test-headers",
        "//hardware/generic/goldfish/emulator/hal/display:test-display",
        "@bazel_tools//tools/cpp/runfiles",
        "@com_google_absl//absl/flags:flag",
        "@com_google_absl//absl/flags:parse",
        "@com_google_googletest//:gtest_main",
    ],
)
