load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "memory",
    srcs = [
        "contiguous_range_mapper.cc",
        "memory_hints.cc",
        "memory_tracker.cc",
    ] + select({
        "@platforms//os:windows": [
            "shared_memory_win32.cc",
        ],
        "//conditions:default": ["shared_memory_posix.cc"],
    }),
    copts = ["-DAEMU_TCMALLOC_ENABLED=0"] +
            select({
                "@platforms//os:windows": ["-Wno-microsoft-goto"],
                "//conditions:default": [],
            }),
    includes = [
        "include",
        "src",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//android/logging:absl-c-bridge",
        "//android/system",
        "@aemu//base:aemu-base",
    ],
)

cc_test(
    name = "memory_unittests",
    srcs = [
        "contiguous_range_mapper_test.cc",
        "malloc_usable_size_test.cc",
        "memory_hints_test.cc",
        "shared_memory_test.cc",
    ],
    linkopts = select({
        "@platforms//os:macos": ["-undefined error"],
        "//conditions:default": [],
    }),
    visibility = ["//visibility:public"],
    deps = [
        ":memory",
        "//android/sockets",
        "//android/system",
        "//android/system:googletest_main",
        "//android/system:test-headers",
        "@abseil-cpp//absl/random",
        "@abseil-cpp//absl/strings",
        "@aemu//base:aemu-base",
    ],
)
