load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "memory",
    srcs = [
        "src/android/base/memory/ContiguousRangeMapper.cpp",
        "src/android/base/memory/MemoryHints.cpp",
        "src/android/base/memory/MemoryTracker.cpp",
    ] + select({
        "@platforms//os:windows": [
            "src/android/base/memory/SharedMemory_win32.cpp",
        ],
        "//conditions:default": ["src/android/base/memory/SharedMemory_posix.cpp"],
    }),
    copts = ["-DAEMU_TCMALLOC_ENABLED=0"] +
            select({
                "@platforms//os:windows": ["-Wno-microsoft-goto"],
                "//conditions:default": [],
            }),
    includes = [
        "include",
        "src",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//hardware/generic/goldfish/android/files",
        "//hardware/generic/goldfish/android/system",
        "@aemu//base:aemu-base",
    ],
)

cc_test(
    name = "memory_unittests",
    srcs = [
        "test/android/base/memory/ContiguousRangeMapper_unittest.cpp",
        "test/android/base/memory/MallocUsableSize_unittest.cpp",
        "test/android/base/memory/MemoryHints_unittest.cpp",
        # "test/android/base/memory/OnDemand_unittest.cpp",
        "test/android/base/memory/ScopedPtr_unittest.cpp",
        "test/android/base/memory/SharedMemory_unittest.cpp",
    ],
    linkopts = select({
        "@platforms//os:macos": ["-undefined error"],
        "//conditions:default": [],
    }),
    deps = [
        ":memory",
        "//hardware/generic/goldfish/android/files",
        "//hardware/generic/goldfish/android/logging:backend",
        "//hardware/generic/goldfish/android/looper",
        "//hardware/generic/goldfish/android/sockets",
        "//hardware/generic/goldfish/android/system",
        "//hardware/generic/goldfish/android/system:googletest_main",
        "//hardware/generic/goldfish/android/system:test-headers",
        "//hardware/generic/goldfish/android/threads",
        "@aemu//base:aemu-base",
    ],
)
