load("@goldfish_build//rules:clang_tidy.bzl", "clang_tidy_report")

# You can update the tests (on macos) by running:
# bazel query -k 'kind("cc_test", @goldfish//...)' |  grep -v 'win' | sed 's/.*/    "&",/' | pbcopy
#
TESTS = [
]

# We have a set of test binaries used here and there
PERF_TESTS = [
    "//emulator/libs/async:sockets_perf",
    "//emulator/libs/logging:log_bridge_perf",
    "//emulator/libs/system:clock_perf",
]

# Index qemu
# We only pick one executable, per platform to prevent confusing
# clangd. Otherwise the same .c might show up with a different
# set of defines and include paths, which might result in some non-determinism
# when indexing files.
# Obtained throug:
# bazel query -k 'kind(cc_binary, @qemu//...)'  |  sed 's/.*/    "&",/'
QEMU = [
    "@qemu//:qemu-img",
] + select({
    "@platforms//os:linux": [
        "@qemu//:qemu-system-x86_64",
    ],
    "@platforms//os:macos": [
        "@qemu//:qemu-system-aarch64",
    ],
    "@platforms//os:windows": [
        "@qemu//:_qemu-system-x86_64_dll",
    ],
    "//conditions:default": [],
})

# The binaries we ship!
# We only pick one plugin, per platform to prevent confusing
# clangd. Otherwise the same .cpp might show up with a different
# set of defines, which might result in some non-determinism
EMULATOR = [
    "//emulator/crashreport",
    "//emulator/crashreport/tool:crashreport",
    "//emulator/launcher",
    "//third_party/sparse:img2simg",
] + select({
    "@platforms//os:linux": [
        "//emulator/plugin:goldfish_x86_64",
    ],
    "@platforms//os:macos": [
        "//emulator/plugin:goldfish_aarch64",
    ],
    "@platforms//os:windows": [
        "//emulator/plugin:goldfish_x86_64",
    ],
    "//conditions:default": [],
})

# This is the clang tidy configuration used by the goldfish project
filegroup(
    name = "clang_tidy_config",
    srcs = [".clang-tidy"],
    visibility = ["//visibility:public"],
)

# This target orchestrates the execution of clang-tidy across specified C/C++ targets.
# It collects warnings and, more importantly, generates and *applies* suggested fixes
# back to the source code when it is `run`, it will generate a report when using `build`
#
#
# IMPORTANT CONSIDERATIONS:
# 1.  **Execution Time:** If there are a large number of fixes to be merged and applied,
#     running this target can be very expensive.
# 2.  **Fix Application:** Running this target will *directly modify* source files by
#     applying the clang-tidy generated fixes. Always review changes before committing.
# 3.  **Invocation:** This target is tagged as "manual" and must be explicitly invoked,
#     for example: `bazel build @goldfish//:clang_tidy_report` to generate fixes
#     and `bazel run @goldfish//:clang_tidy_report` to apply fixes
clang_tidy_report(
    name = "clang_tidy_report",
    testonly = True,
    apply_fixes_in = "hardware/generic/goldfish",
    rewrite_sed_pattern = "s/^m_//g",  # Make sure we don't end up with mMemberVar -> m_member_var_
    source_path_substrings = ["goldfish+"],
    tags = ["manual"],  # Invoke explicitly
    targets = TESTS + PERF_TESTS + QEMU + EMULATOR,
    tidy_config_file = ":clang_tidy_config",
)
