load("@goldfish_build//rules:clang_tidy.bzl", "clang_tidy_report")

# You can update the tests (on macos) by running:
# bazel query -k 'kind("cc_test", @goldfish//...)' |  grep -v 'win' | sed 's/.*/    "&",/' | pbcopy
#
TESTS = [
    "@goldfish//android/async:async_testing_unittests",
    "@goldfish//android/async:event_loop_dispatcher_test",
    "@goldfish//android/async:eventloop_unittests",
    "@goldfish//android/async:libuv_signal_handlers_test",
    "@goldfish//android/async:sockets_unittests",
    "@goldfish//android/cpu:cpu_unittests",
    "@goldfish//android/files:file_system_watcher_test",
    "@goldfish//android/files:ini_file",
    "@goldfish//android/logging:color_log_sink_test",
    "@goldfish//android/memory:memory_unittests",
    "@goldfish//android/network:network_unittests",
    "@goldfish//android/process:process_unittests",
    "@goldfish//android/sockets:sockets_unittests",
    "@goldfish//android/system:system-unittests",
    "@goldfish//emulator/adb/host:host_unittests",
    "@goldfish//emulator/adb/logger:logger_unittests",
    "@goldfish//emulator/adb/secrets:secrets_unittests",
    "@goldfish//emulator/crashreport:crashreport_test",
    "@goldfish//emulator/crashreport:hang_detector_test",
    "@goldfish//emulator/grpc/absl:translate_test",
    "@goldfish//emulator/grpc/async:async_library_test",
    "@goldfish//emulator/grpc/client:emulator_grpc_client_test",
    "@goldfish//emulator/grpc/interceptors:interceptors_test",
    "@goldfish//emulator/grpc/security:security-test",
    "@goldfish//emulator/grpc/services/emulator_controller/input:input_unittests",
    "@goldfish//emulator/grpc/services/emulator_controller/server:emulator-service_unittests",
    "@goldfish//emulator/hal/bootproperties:bootproperties_unittests",
    "@goldfish//emulator/hal/camera:camera_impl_unittests",
    "@goldfish//emulator/hal/camera/image_providers/imagefile:imagefile_unittests",
    "@goldfish//emulator/hal/camera/image_providers/videofile:videofile_unittests",
    "@goldfish//emulator/hal/camera/image_providers/virtualscene:virtualscene_unittests",
    "@goldfish//emulator/hal/camera/image_providers/webcam:webcam_unittests",
    "@goldfish//emulator/hal/clipboard:clipboard_unittests",
    "@goldfish//emulator/hal/connector:connector_registry_tests",
    "@goldfish//emulator/hal/connector:devices_unittests",
    "@goldfish//emulator/hal/fingerprint:fingerprint_unittests",
    "@goldfish//emulator/hal/gps:gps_unittests",
    "@goldfish//emulator/hal/guest-status:guest-status_unittests",
    "@goldfish//emulator/hal/plug:hal_plug_adapter_unittests",
    "@goldfish//emulator/hal/sensors:sensors_unittests",
    "@goldfish//emulator/launcher:bootconfig_test",
    "@goldfish//emulator/launcher:config_dirs_test",
    "@goldfish//emulator/launcher:logging_test",
    "@goldfish//emulator/launcher/cmdline:cmdline_unittests",
    "@goldfish//emulator/launcher/devices:adb_device_test",
    "@goldfish//emulator/launcher/devices:avd_info_device_test",
    "@goldfish//emulator/launcher/devices:cpu_device_test",
    "@goldfish//emulator/launcher/devices:display_device_test",
    "@goldfish//emulator/launcher/devices:grpc_device_test",
    "@goldfish//emulator/launcher/devices:initrd_device_test",
    "@goldfish//emulator/launcher/devices:kernel_device_test",
    "@goldfish//emulator/launcher/devices:machine_test",
    "@goldfish//emulator/launcher/devices:memory_device_test",
    "@goldfish//emulator/launcher/devices:network_device_test",
    "@goldfish//emulator/launcher:configure_drives_test",
    "@goldfish//emulator/launcher/devices:disk_drive_test",
    "@goldfish//emulator/libs/SocketBuffer:SocketBuffer_unittests",
    "@goldfish//emulator/libs/UniqueIdAllocator:UniqueIdAllocator_unittests",
    "@goldfish//emulator/libs/archive:reader_writer_unittests",
    "@goldfish//emulator/libs/archive:zigzag_unittests",
    "@goldfish//emulator/libs/base:base_unittests",
    "@goldfish//emulator/libs/broadcasting:broadcasting_unittests",
    "@goldfish//emulator/libs/display:display_unittests",
    "@goldfish//emulator/libs/fps_calculator:fps_calculator_unittests",
    "@goldfish//emulator/libs/gvk:gvk_unittests",
    "@goldfish//emulator/libs/imaging:imaging_unittests",
    "@goldfish//emulator/libs/os:os_unittests",
    "@goldfish//emulator/libs/parsing:parsing_unittests",
    "@goldfish//emulator/libs/physics:physics_unittests",
    "@goldfish//emulator/libs/sensors:physical_model_test",
    "@goldfish//emulator/plugin/avd:global-event-loop-tests",
    "@goldfish//emulator/plugin/vminterface:vminterface_unittests",
]

# We have a set of test binaries used here and there
PERF_TESTS = [
    "//android/async:sockets_perf",
    "//android/logging:log_bridge_perf",
    "//android/system:clock_perf",
]

# Index qemu
# We only pick one executable, per platform to prevent confusing
# clangd. Otherwise the same .c might show up with a different
# set of defines and include paths, which might result in some non-determinism
# when indexing files.
# Obtained throug:
# bazel query -k 'kind(cc_binary, @qemu//...)'  |  sed 's/.*/    "&",/'
QEMU = [
    "@qemu//:qemu-img",
] + select({
    "@platforms//os:linux": [
        "@qemu//:qemu-system-x86_64",
    ],
    "@platforms//os:macos": [
        "@qemu//:qemu-system-aarch64",
    ],
    "@platforms//os:windows": [
        "@qemu//:_qemu-system-x86_64_dll",
    ],
    "//conditions:default": [],
})

# The binaries we ship!
# We only pick one plugin, per platform to prevent confusing
# clangd. Otherwise the same .cpp might show up with a different
# set of defines, which might result in some non-determinism
EMULATOR = [
    "//emulator/crashreport",
    "//emulator/crashreport/tool:crashreport",
    "//emulator/launcher",
    "//third_party/sparse:img2simg",
] + select({
    "@platforms//os:linux": [
        "//emulator/plugin:goldfish_x86_64",
    ],
    "@platforms//os:macos": [
        "//emulator/plugin:goldfish_aarch64",
    ],
    "@platforms//os:windows": [
        "//emulator/plugin:goldfish_x86_64",
    ],
    "//conditions:default": [],
})

# This is the clang tidy configuration used by the goldfish project
filegroup(
    name = "clang_tidy_config",
    srcs = [".clang-tidy"],
    visibility = ["//visibility:public"],
)

# This target orchestrates the execution of clang-tidy across specified C/C++ targets.
# It collects warnings and, more importantly, generates and *applies* suggested fixes
# back to the source code when it is `run`, it will generate a report when using `build`
#
#
# IMPORTANT CONSIDERATIONS:
# 1.  **Execution Time:** If there are a large number of fixes to be merged and applied,
#     running this target can be very expensive.
# 2.  **Fix Application:** Running this target will *directly modify* source files by
#     applying the clang-tidy generated fixes. Always review changes before committing.
# 3.  **Invocation:** This target is tagged as "manual" and must be explicitly invoked,
#     for example: `bazel build @goldfish//:clang_tidy_report` to generate fixes
#     and `bazel run @goldfish//:clang_tidy_report` to apply fixes
clang_tidy_report(
    name = "clang_tidy_report",
    testonly = True,
    apply_fixes_in = "hardware/generic/goldfish",
    rewrite_sed_pattern = "s/^m_//g",  # Make sure we don't end up with mMemberVar -> m_member_var_
    source_path_substrings = ["goldfish+"],
    tags = ["manual"],  # Invoke explicitly
    targets = TESTS + PERF_TESTS + QEMU + EMULATOR,
    tidy_config_file = ":clang_tidy_config",
)
