load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "base",
    srcs = [
        "display.cc",
    ],
    hdrs = [
        "include/goldfish/display/display.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//android/async:async_api",
        "//emulator/libs/base",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/time",
    ],
)

cc_library(
    name = "display",
    srcs = [
        "NullDisplay.h",
        "QemuDisplay.h",
        "multi_display.cc",
        "pixman_display.cc",
        "pixman_frame_manager.cc",
        "qemu_display.cc",
        "virtio_bridge.c",
        "virtio_bridge.h",
    ],
    hdrs = [
        "include/goldfish/display/QemuMultidisplay/multi_display.h",
        "include/goldfish/display/multi_display_callbacks.h",
        "include/goldfish/display/pixman_display.h",
        "include/goldfish/display/pixman_frame_manager.h",
        "include/goldfish/display/pixman_image_ptr.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":base",
        "//android/logging:absl-c-bridge",
        "//emulator/libs/base",
        "//emulator/libs/fps_calculator",
        "//emulator/libs/physics",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/time",
        "@pixman//:pixman-1",
        "@pixman//:pixman_simd",
        "@qemu//:qemu-headers",
    ],
)

cc_library(
    name = "test-display",
    testonly = True,
    srcs = [
        "fake_multi_display.cc",
        "fake_pixman_display.cc",
        "pixman_image_generator.cc",
        "qemu_stubs.c",
    ],
    hdrs = [
        "include/goldfish/display/test/fake_multi_display.h",
        "include/goldfish/display/test/fake_pixman_display.h",
        "include/goldfish/display/test/image_generation_strategy.h",
        "include/goldfish/display/test/mock_display.h",
        "include/goldfish/display/test/pixman_image_generator.h",
    ],
    includes = ["test/include"],
    visibility = ["//visibility:public"],
    deps = [
        ":display",
    ],
)

cc_test(
    name = "display_unittests",
    srcs = [
        "display_test.cc",
        "fake_multi_display_test.cc",
        "fake_pixman_display_test.cc",
        "image_generation_strategy_test.cc",
        "pixman_frame_manager_test.cc",
        "pixman_image_generator_test.cc",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":test-display",
        "//android/async:libuv_event_loop",
        "//android/async:threaded_event_loop",
        "//android/system:googletest_main",
    ],
)
