load("@goldfish_build//rules:clang_tidy.bzl", "clang_tidy_test")
load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "telnet_auth",
    srcs = ["telnet_auth.cc"],
    hdrs = ["telnet_auth.h"],
    linkopts = select({
        "@platforms//os:windows": [
            "-DEFAULTLIB:advapi32.lib",
        ],
        "//conditions:default": [],
    }),
    deps = [
        "//emulator/libs/file",
        "//emulator/libs/system",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:check",
        "@abseil-cpp//absl/random",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@tink_cc//tink:secret_data",
        "@tink_cc//tink:tink_cc",
    ],
)

cc_library(
    name = "line_command_handler",
    hdrs = ["line_command_handler.h"],
    deps = [
        "@abseil-cpp//absl/status:statusor",
    ],
)

cc_library(
    name = "console_server",
    srcs = ["console_server.cc"],
    hdrs = ["console_server.h"],
    deps = [
        ":line_command_handler",
        "//emulator/libs/async:async_api",
        "//emulator/libs/async:libuv_event_loop",
        "//emulator/libs/async:threaded_event_loop",
        "//emulator/libs/network",
        "@abseil-cpp//absl/container:flat_hash_map",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:check",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/synchronization",
    ],
)

cc_library(
    name = "legacy_console_controller",
    srcs = ["legacy_console_controller.cc"],
    hdrs = ["legacy_console_controller.h"],
    includes = ["."],
    deps = [
        ":console_server",
        ":legacy_console_bridge",
        ":line_command_handler",
        ":telnet_auth",
        "//emulator/libs/async:async_api",
        "//emulator/libs/async:libuv_event_loop",
        "//emulator/libs/network",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
    ],
)

cc_library(
    name = "command_registry",
    srcs = ["command_registry.cc"],
    hdrs = ["command_registry.h"],
    deps = [
        ":line_command_handler",
        "//emulator/libs/parsing",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:check",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
    ],
)

cc_library(
    name = "legacy_console_bridge",
    srcs = [
        "legacy_console_bridge.cc",
        "screen_record_commands.cc",
        "screen_record_commands.h",
    ],
    hdrs = [
        "legacy_console_bridge.h",
    ],
    deps = [
        ":command_registry",
        ":line_command_handler",
        ":telnet_auth",
        "//emulator/libs/grpc_client",
        "//emulator/libs/grpc_utils:absl_translate",
        "//emulator/libs/status_macros",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@aemu//protos/services/emulator-controller:emulator_controller_cc_grpc",
        "@aemu//protos/services/incubating/recording:screen_recording_service_cc_grpc",
        "@aemu//protos/services/snapshot:snapshot_service_cc_grpc",
    ],
)

cc_test(
    name = "console_server_test",
    srcs = ["console_server_test.cc"],
    deps = [
        ":console_server",
        "//emulator/libs/async:async_testing",
        "//emulator/libs/async:libuv_sockets",
        "//emulator/libs/network",
        "//emulator/libs/test:googletest_main",
    ],
)

cc_test(
    name = "telnet_auth_test",
    srcs = ["telnet_auth_test.cc"],
    deps = [
        ":telnet_auth",
        "//emulator/libs/system",
        "//emulator/libs/system:test-headers",
        "//emulator/libs/test:googletest_main",
    ],
)

cc_test(
    name = "command_registry_test",
    srcs = ["command_registry_test.cc"],
    deps = [
        ":command_registry",
        "//emulator/libs/async:async_testing",
        "//emulator/libs/test:googletest_main",
    ],
)

cc_test(
    name = "legacy_console_controller_test",
    srcs = ["legacy_console_controller_test.cc"],
    deps = [
        ":legacy_console_bridge",
        ":legacy_console_controller",
        ":telnet_auth",
        "//emulator/libs/async:async_testing",
        "//emulator/libs/async:libuv_event_loop",
        "//emulator/libs/network",
        "//emulator/libs/test:googletest_main",
    ],
)

cc_test(
    name = "legacy_console_bridge_test",
    srcs = ["legacy_console_bridge_test.cc"],
    deps = [
        ":legacy_console_bridge",
        ":telnet_auth",
        "//emulator/libs/system",
        "//emulator/libs/system:test-headers",
        "//emulator/libs/test:googletest_main",
    ],
)

cc_test(
    name = "screen_record_commands_test",
    srcs = ["screen_record_commands_test.cc"],
    deps = [
        ":legacy_console_bridge",
        "//emulator/libs/system",
        "//emulator/libs/system:test-headers",
        "//emulator/libs/test:googletest_main",
    ],
)

clang_tidy_test(
    name = "tidy",
    targets = [
        ":telnet_auth",
        ":line_command_handler",
        ":command_registry",
        ":legacy_console_bridge",
        ":console_server",
    ],
    tidy_config_file = "//:clang_tidy_config",
)
