load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "qemu_clock",
    srcs = ["src/qemu_clock.cpp"],
    hdrs = ["include/android/base/system/qemu_clock.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//android/system:clock",
        "@qemu//:qemu-headers",
    ],
)
