load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "qemu_clock",
    srcs = ["qemu_clock.cc"],
    hdrs = ["include/android/base/qemu_clock.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//emulator/libs/system:clock",
        "@qemu//:qemu-headers-exported",
    ],
)
