load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "virtualscene",
    srcs = [
        "virtualscene.cpp",
    ],
    hdrs = [
        "include/android/camera/image_providers/virtualscene.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//hardware/generic/goldfish/emulator/hal/camera:image_provider_api",
        "@com_google_absl//absl/log",
    ],
    alwayslink = True,
)

cc_test(
    name = "virtualscene_unittests",
    srcs = [
        "test/todo.cpp",
    ],
    deps = [
        ":virtualscene",
        "@com_google_googletest//:gtest_main",
    ],
)
