load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "virtualscene",
    srcs = [
        "VirtualsceneImageProvider.cpp",
        "VirtualsceneImageProvider.h",
        "virtualscene.cpp",
    ],
    hdrs = [
        "include/android/camera/image_providers/virtualscene.h",
    ],
    includes = [
        "include",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//hardware/generic/goldfish/emulator/hal/camera:image_provider_api",
        "//hardware/generic/goldfish/emulator/libs/gvk",
        "@aemu//base:aemu-base-headers",
        "@com_google_absl//absl/log",
        "@gfxstream//third_party/glm",
        "@libyuv",
        "@tinyobjloader",
    ],
    alwayslink = True,
)

cc_test(
    name = "virtualscene_unittests",
    srcs = [
        "test/VirtualsceneImageProvider_test.cpp",
        "test/virtualscene_data.cpp",
    ],
    data = [
        "//prebuilts/android-emulator-build/common/virtualscene/Toren1BD",
    ],
    includes = [
        ".",
    ],
    deps = [
        ":virtualscene",
        "//hardware/generic/goldfish/android/system",
        "//hardware/generic/goldfish/android/system:googletest_main",
    ],
)
