load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "virtualscene",
    srcs = [
        "VirtualsceneImageProvider.h",
        "virtualscene.cc",
        "virtualscene_image_provider.cc",
    ],
    hdrs = ["include/goldfish/camera_image_providers/virtualscene/virtualscene.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//emulator/hal/camera:image_provider_api",
        "//emulator/libs/base:array_size",
        "//emulator/libs/gvk",
        "@abseil-cpp//absl/log",
        "@gfxstream//third_party/glm",
        "@libyuv",
        "@tinyobjloader",
    ],
    alwayslink = True,
)

cc_test(
    name = "virtualscene_unittests",
    srcs = [
        "virtualscene_data.cc",
        "virtualscene_image_provider_test.cc",
    ],
    data = ["@goldfish_prebuilts_common//virtualscene/Toren1BD"],
    visibility = ["//visibility:public"],
    deps = [
        ":virtualscene",
        "//emulator/libs/system:bazel_info",
        "//emulator/libs/test:googletest_main",
    ],
)
