load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "agents",
    srcs = [
        "src/android/emulation/control/AndroidAgentFactory.cpp",
        "src/android/emulation/control/LineConsumer.cpp",
    ],
    hdrs = [
        "include/android/console.h",
        "include/android/console_exports.h",
        "include/android/emulation/control/AndroidAgentFactory.h",
        "include/android/emulation/control/LineConsumer.h",
        "include/android/emulation/control/automation_agent.h",
        "include/android/emulation/control/battery_agent.h",
        "include/android/emulation/control/callbacks.h",
        "include/android/emulation/control/car_data_agent.h",
        "include/android/emulation/control/cellular_agent.h",
        "include/android/emulation/control/clipboard_agent.h",
        "include/android/emulation/control/finger_agent.h",
        "include/android/emulation/control/globals_agent.h",
        "include/android/emulation/control/grpc_agent.h",
        "include/android/emulation/control/http_proxy_agent.h",
        "include/android/emulation/control/hw_control_agent.h",
        "include/android/emulation/control/location_agent.h",
        "include/android/emulation/control/net_agent.h",
        "include/android/emulation/control/rootcanal_hci_agent.h",
        "include/android/emulation/control/sensors_agent.h",
        "include/android/emulation/control/structs.h",
        "include/android/emulation/control/telephony_agent.h",
        "include/android/emulation/control/user_event_agent.h",
        "include/android/emulation/control/virtual_scene_agent.h",
        "include/android/physics/physical_state_agent.h",
        "include/android/settings-agent.h",
        "include/android/ui-emu-agent.h",
    ],
    includes = [
        "include",
        "src",
    ],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//hardware/generic/goldfish/android/files",
    ],
)

cc_test(
    name = "agents_unittests",
    size = "small",
    srcs = ["test/android/emulation/control/LineConsumer_unittest.cpp"],
    includes = ["test"],
    linkopts = select({
        "@platforms//os:macos": ["-undefined error"],
        "//conditions:default": [],
    }),
    deps = [
        ":agents",
        "//hardware/generic/goldfish/android/logging:backend",
        "//hardware/generic/goldfish/android/system",
        "//hardware/generic/goldfish/android/system:test-headers",
        "@aemu//base:aemu-base",
        "@com_google_googletest//:gtest_main",
    ] + select({
        "@platforms//os:windows": [
            "//hardware/generic/goldfish/android/windows/posix:compat",
        ],
        "//conditions:default": [],
    }),
)
