load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "goldfish_vsock_hdrs",
    hdrs = [
        "include/goldfish/vsock/connect.h",
        "include/goldfish/vsock/listen.h",
        "include/goldfish/vsock/snapshot.h",
        "include/goldfish/vsock/vsock_port_fwd.h",
    ],
    includes = ["include"],
    visibility = [
        "//visibility:public",
    ],
)

[cc_library(
    name = "virtio-vsock-goldfish-impl-" + arch,
    srcs = [
        "vsock.cpp",
        "vsock_low_level.c",
        "vsock_low_level.h",
        "vsock_port_fwd.cpp",
    ],
    defines = [
        "COMPILING_PER_TARGET",
        'CONFIG_TARGET=\\"' + arch + '-softmmu-config-target.h\\"',
        'CONFIG_DEVICES=\\"' + arch + '-softmmu-config-devices.h\\"',
    ],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        ":goldfish_vsock_hdrs",
        "//hardware/generic/goldfish/android/event-support",
        "//hardware/generic/goldfish/android/logging:absl-c-bridge",
        "//hardware/generic/goldfish/android/sockets",
        "//hardware/generic/goldfish/emulator/devices:cable",
        "//hardware/generic/goldfish/emulator/devices:connection_awaiter",
        "//hardware/generic/goldfish/emulator/libs/SocketBuffer",
        "//hardware/generic/goldfish/emulator/libs/UniqueIdAllocator",
        "//hardware/generic/goldfish/emulator/libs/archive:QEMUFileArchive",
        "//hardware/generic/goldfish/emulator/libs/debug",
        "//hardware/generic/goldfish/emulator/plugin/avd:avd_hdrs",
        "//hardware/generic/goldfish/emulator/plugin/avd:qemu-looper",
        "//third_party/qemu:libmodule-common",
        "//third_party/qemu:qemu-headers",
    ],
    alwayslink = True,
) for arch in [
    "riscv64",
    "aarch64",
    "x86_64",
]]

[cc_binary(
    name = "virtio-vsock-goldfish-" + arch,
    linkopts = select({
        "@platforms//os:macos": ["-undefined dynamic_lookup"],
        "//conditions:default": [],
    }),
    linkshared = True,
    visibility = ["//visibility:public"],
    deps = [":virtio-vsock-goldfish-impl-" + arch] +
           select({
               "@platforms//os:windows": [
                   "//third_party/qemu:qemu-system-" + arch + ".if",
               ],
               "//conditions:default": [],
           }),
) for arch in [
    "riscv64",
    "aarch64",
    "x86_64",
]]
