load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "goldfish_vsock_hdrs",
    hdrs = [
        "include/goldfish/vsock/clear.h",
        "include/goldfish/vsock/connect.h",
        "include/goldfish/vsock/listen.h",
        "include/goldfish/vsock/snapshot.h",
        "include/goldfish/vsock/vsock_low_level.h",
        "include/goldfish/vsock/vsock_port_fwd.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//emulator/libs/async:async_api",
        "@qemu//:qemu-headers",
    ],
)

[cc_library(
    name = "vsock_impl_" + arch,
    srcs = [
        "vsock.cc",
        "vsock_low_level.c",
        "vsock_port_fwd.cc",
    ],
    defines = [
        "COMPILING_PER_TARGET",
        'CONFIG_TARGET=\\"' + arch + '-softmmu-config-target.h\\"',
        'CONFIG_DEVICES=\\"' + arch + '-softmmu-config-devices.h\\"',
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":goldfish_vsock_hdrs",
        "//android/network",
        "//emulator/hal/connector:cable",
        "//emulator/hal/connector:connection_awaiter",
        "//emulator/hal/guest-status",
        "//emulator/hal/plug:hal_plug_factory",
        "//emulator/libs/SocketBuffer",
        "//emulator/libs/UniqueIdAllocator",
        "//emulator/libs/archive:QEMUFileArchive",
        "//emulator/libs/async:libuv_event_loop",
        "//emulator/libs/async:libuv_sockets",
        "//emulator/libs/async:qemu_event_loop",
        "//emulator/libs/async:threaded_event_loop",
        "//emulator/libs/debug",
        "//emulator/libs/eventing",
        "//emulator/libs/logging:absl_c_bridge",
        "//emulator/libs/synchronization",
        "//emulator/plugin/avd:impl",
        "@qemu//:qemu-headers",
    ],
    alwayslink = True,
) for arch in [
    "riscv64",
    "aarch64",
    "x86_64",
]]
