load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "logger",
    srcs = ["adb_mesage_logger.cc"],
    hdrs = ["include/goldfish/adb/adb_message_logger.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//emulator/hal/connector:cable",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/strings",
    ],
)

cc_test(
    name = "logger_unitests",
    srcs = ["adb_message_logger_test.cc"],
    visibility = ["//visibility:public"],
    deps = [
        ":logger",
        "//android/system:googletest_main",
        "//android/system:test-headers",
    ],
)
