load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

package(default_visibility = ["//emulator/grpc:__subpackages__"])

cc_library(
    name = "translate",
    srcs = [
        "src/absl_status_translate.cpp",
    ],
    hdrs = [
        "include/android/grpc/utils/absl_status_translate.h",
    ],
    includes = ["include"],
    deps = [
        "@abseil-cpp//absl/status",
        "@grpc//:grpc++",
    ],
)

cc_test(
    name = "translate_test",
    srcs = ["test/absl_status_translate_test.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        ":translate",
        "//android/system:googletest_main",
        "@googletest//:gtest",
    ],
)
