load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "host",
    srcs = ["adb_host_server.cc"],
    hdrs = ["include/goldfish/adb/adb_host_server.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//emulator/libs/sockets",
        "//emulator/libs/system",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
    ],
)

cc_test(
    name = "host_unittests",
    srcs = [
        "adb_host_server_test.cc",
        "test_input_buffer_socket_server_thread.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":host",
        "//emulator/libs/system:test-headers",
        "//emulator/libs/test:googletest_main",
    ],
)
