load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "compat",
    srcs = [
        "src/android/base/Win32UnicodeString.cpp",
        "src/android/base/Win32Utils.cpp",
        "src/android/base/win32_unicode.cpp",
    ],
    hdrs = [
        "src/win32_unicode.h",
    ],
    includes = ["src"],
    linkopts = [
        "-DEFAULTLIB:Advapi32.lib",
    ],
    target_compatible_with = [
        "@platforms//os:windows",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//hardware/generic/goldfish/android/system",
        "@aemu//base:aemu-base",
    ],
)

cc_test(
    name = "compat_unittests",
    srcs = [
        "test/android/base/Win32UnicodeString_unittest.cpp",
        "test/android/base/Win32Utils_unittest.cpp",
    ],
    target_compatible_with = [
        "@platforms//os:windows",
    ],
    deps = [
        ":compat",
        "//hardware/generic/goldfish/android/system:test-headers",
        "@com_google_googletest//:gtest_main",
    ],
)
