load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "compat",
    srcs = [
        "src/android/base/Win32UnicodeString.cpp",
        #"src/android/base/Win32Utils.cpp",
        "src/android/base/win32_unicode.cpp",
    ],
    hdrs = [
        "src/win32_unicode.h",
    ],
    includes = ["src"],
    linkopts = [
        "-DEFAULTLIB:Advapi32.lib",
    ],
    target_compatible_with = [
        "@platforms//os:windows",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@aemu//base:aemu-base",
    ],
)
