load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//emulator/grpc:__subpackages__"])

cc_library(
    name = "adb-service",
    srcs = ["adb_service.cc"],
    hdrs = ["include/grpc/android/emulation/control/adb_service.h"],
    includes = ["include"],
    deps = [
        "//emulator/adb/secrets",
        "//emulator/grpc/async",
        "//emulator/grpc/services/adb:adb_service_cc_grpc",
        "@aemu//base:aemu-base",
    ],
)
