load("@goldfish_build//rules:clang_tidy.bzl", "clang_tidy_test")
load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "async_api",
    srcs = [
        "logging.cc",
        "socket_factory.cc",
    ],
    hdrs = [
        "include/goldfish/async/async_socket.h",
        "include/goldfish/async/async_socket_factory.h",
        "include/goldfish/async/async_socket_server.h",
        "include/goldfish/async/async_socket_utils.h",
        "include/goldfish/async/event_loop.h",
        "include/goldfish/async/event_loop_dispatcher.h",
        "include/goldfish/async/scoped_async_resource.h",
        "include/goldfish/async/scoped_async_timer.h",
        "include/goldfish/async/when_all.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//emulator/libs/eventing",
        "//emulator/libs/network",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:check",
        "@abseil-cpp//absl/status:statusor",
    ],
)

cc_library(
    name = "uv_to_absl",
    srcs = ["uv_to_absl.cc"],
    hdrs = ["include/goldfish/async/uv_to_absl.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/strings",
        "@libuv",
    ],
)

cc_library(
    name = "errno_to_absl",
    srcs = ["errno_to_absl.cc"],
    hdrs = ["include/goldfish/async/errno_to_absl.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/strings",
    ],
)

cc_library(
    name = "threaded_event_loop",
    srcs = ["threaded_event_loop.cc"],
    hdrs = ["include/goldfish/async/threaded_event_loop.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":async_api",
        ":libuv_event_loop",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/status:statusor",
    ] + select({
        "@platforms//os:windows": ["//emulator/libs/windows:win32_utils"],
        "//conditions:default": [],
    }),
)

cc_library(
    name = "libuv_event_loop",
    srcs = ["libuv_event_loop.cc"],
    hdrs = ["include/goldfish/async/libuv_event_loop.h"],
    copts = ["-Wno-unused-result"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":async_api",
        ":uv_to_absl",
        "//emulator/libs/system:threads",
        "@abseil-cpp//absl/container:flat_hash_map",
        "@abseil-cpp//absl/log:check",
        "@libuv",
    ],
)

cc_library(
    name = "qemu_event_loop",
    srcs = ["qemu_event_loop.cc"],
    hdrs = ["include/goldfish/async/qemu_event_loop.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":async_api",
        "//emulator/libs/QEMUBH",
        "@abseil-cpp//absl/container:flat_hash_map",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:check",
        "@abseil-cpp//absl/status",
        "@qemu//:qemu-headers",
    ],
)

cc_library(
    name = "fake_qemu_callbacks",
    srcs = ["fake_qemu_callbacks.cc"],
    hdrs = ["test/fake_qemu_callbacks.h"],
    includes = ["test"],
    visibility = [
        "//emulator/libs/async:__pkg__",
        "//emulator/plugin/vsock_goldfish:__pkg__",
    ],
    deps = [
        ":qemu_event_loop",
        "@qemu//:qemu-headers",
    ],
)

cc_test(
    name = "eventloop_unittests",
    size = "small",
    timeout = "moderate",
    srcs = [
        "event_loop_name_test.cc",
        "event_loop_test.cc",
    ],
    copts = ["-Wno-unused-result"],
    includes = ["test"],
    linkopts = select({
        "@platforms//os:macos": ["-undefined error"],
        "@platforms//os:windows": [
            "-DEFAULTLIB:Shell32.lib",
            "-DEFAULTLIB:User32.lib",
        ],
        "//conditions:default": [],
    }),
    visibility = ["//visibility:public"],
    deps = [
        ":async_testing",
        ":libuv_event_loop",
        ":qemu_event_loop",
        ":threaded_event_loop",
        "//emulator/libs/async:fake_qemu_callbacks",
        "//emulator/libs/system",
        "//emulator/libs/system:threads",
        "//emulator/libs/test:googletest_main",
        "@abseil-cpp//absl/status:status_matchers",
    ],
)

cc_library(
    name = "libuv_sockets",
    srcs = ["libuv_sockets.cc"],
    hdrs = ["include/goldfish/async/libuv_socket_factory.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":async_api",
        ":libuv_event_loop",
        ":uv_to_absl",
        "//emulator/libs/base",
        "//emulator/libs/cpp",
        "//emulator/libs/network",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:check",
        "@abseil-cpp//absl/strings",
        "@libuv",
    ],
)

cc_test(
    name = "sockets_unittests",
    size = "small",
    srcs = ["async_socket_test.cc"],
    copts = ["-Wno-unused-result"],
    includes = ["test"],
    linkopts = select({
        "@platforms//os:macos": ["-undefined error"],
        "//conditions:default": [],
    }),
    visibility = ["//visibility:public"],
    deps = [
        ":libuv_sockets",
        "//emulator/libs/network",
        "//emulator/libs/system:test-headers",
        "//emulator/libs/test:googletest_main",
        "@abseil-cpp//absl/status:status_matchers",
    ],
)

cc_test(
    name = "scoped_async_resource_test",
    srcs = ["scoped_async_resource_test.cc"],
    visibility = ["//visibility:public"],
    deps = [
        ":async_api",
        ":async_testing",
        ":libuv_event_loop",
        ":threaded_event_loop",
        "//emulator/libs/test:googletest_main",
    ],
)

cc_test(
    name = "event_loop_dispatcher_test",
    size = "medium",
    srcs = ["event_loop_dispatcher_test.cc"],
    visibility = ["//visibility:public"],
    deps = [
        ":libuv_event_loop",
        "//emulator/libs/eventing",
        "//emulator/libs/test:googletest_main",
        "@abseil-cpp//absl/status:status_matchers",
    ],
)

cc_binary(
    name = "sockets_perf",
    srcs = ["bm_libuv_sockets.cc"],
    copts = [
        "-Wno-deprecated-declarations",
        "-Wno-unused-result",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":libuv_sockets",
        "@google_benchmark//:benchmark",
    ],
)

cc_library(
    name = "async_testing",
    testonly = True,
    srcs = ["test_event_loop.cc"],
    hdrs = [
        "include/goldfish/async/testing/fake_async_socket.h",
        "include/goldfish/async/testing/test_event_loop.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":async_api",
        "//emulator/libs/system:threads",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/strings",
    ],
)

cc_test(
    name = "async_testing_unittests",
    srcs = ["test_event_loop_test.cc"],
    visibility = ["//visibility:public"],
    deps = [
        ":async_testing",
        "//emulator/libs/test:googletest_main",
        "@abseil-cpp//absl/status:status_matchers",
    ],
)

cc_library(
    name = "launch_config",
    hdrs = ["include/goldfish/async/launch_config.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "libuv_process_launcher",
    srcs = ["libuv_process_launcher.cc"],
    hdrs = ["include/goldfish/async/libuv_process_launcher.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":launch_config",
        ":uv_to_absl",
        "//emulator/libs/system:fd_util",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/status:statusor",
        "@libuv",
    ],
)

cc_library(
    name = "libuv_signal_handlers",
    hdrs = ["include/goldfish/async/libuv_signal_handlers.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":libuv_event_loop",
        ":threaded_event_loop",
        ":uv_to_absl",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/status:statusor",
        "@libuv",
    ],
)

cc_test(
    name = "libuv_signal_handlers_test",
    srcs = ["libuv_signal_handlers_test.cc"],
    visibility = ["//visibility:public"],
    deps = [
        ":libuv_signal_handlers",
        "//emulator/libs/test:googletest_main",
        "@abseil-cpp//absl/status:status_matchers",
    ],
)

cc_test(
    name = "when_all_test",
    srcs = ["when_all_test.cc"],
    visibility = ["//visibility:public"],
    deps = [
        ":async_testing",
        ":libuv_event_loop",
        ":threaded_event_loop",
        "//emulator/libs/test:googletest_main",
        "@abseil-cpp//absl/status:status_matchers",
    ],
)

clang_tidy_test(
    name = "tidy",
    targets = [
        ":async_api",
        ":errno_to_absl",
        ":launch_config",
        ":libuv_event_loop",
        ":libuv_process_launcher",
        ":libuv_sockets",
        ":qemu_event_loop",
        ":uv_to_absl",
    ],
    tidy_config_file = "//:clang_tidy_config",
)

cc_test(
    name = "loop_handoff_test",
    size = "small",
    srcs = ["test/loop_handoff_test.cc"],
    copts = ["-Wno-unused-result"],
    includes = ["test"],
    visibility = ["//visibility:public"],
    deps = [
        ":libuv_sockets",
        ":threaded_event_loop",
        "//emulator/libs/network",
        "//emulator/libs/test:googletest_main",
        "@abseil-cpp//absl/status:status_matchers",
    ],
)
