load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "async_api",
    hdrs = [
        "include/goldfish/async/async_socket.h",
        "include/goldfish/async/async_socket_factory.h",
        "include/goldfish/async/async_socket_server.h",
        "include/goldfish/async/async_socket_utils.h",
        "include/goldfish/async/event_loop.h",
        "include/goldfish/async/scoped_async_resource.h",
        "include/goldfish/async/scoped_async_timer.h",
        "include/goldfish/async/threaded_event_loop.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "@com_google_absl//absl/status:statusor",
    ],
)

cc_library(
    name = "async_impl",
    srcs = [
        "src/threaded_event_loop.cpp",
    ],
    hdrs = [
        "include/goldfish/async/threaded_event_loop.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":async_api",
        "@com_google_absl//absl/log",
        "@com_google_absl//absl/status:statusor",
    ],
)

cc_library(
    name = "uv_to_absl",
    srcs = [
        "src/uv_to_absl.cpp",
    ],
    hdrs = [
        "include/goldfish/async/uv_to_absl.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "@com_google_absl//absl/log",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/strings",
        "@libuv",
    ],
)

cc_library(
    name = "errno_to_absl",
    srcs = [
        "src/errno_to_absl.cpp",
    ],
    hdrs = [
        "include/goldfish/async/errno_to_absl.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/strings",
    ],
)

cc_library(
    name = "libuv_event_loop",
    srcs = [
        "src/libuv_event_loop.cpp",
    ],
    hdrs = [
        "include/goldfish/async/libuv_event_loop.h",
    ],
    copts = ["-Wno-unused-result"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":async_api",
        ":async_impl",
        ":uv_to_absl",
        "@com_google_absl//absl/container:flat_hash_set",
        "@libuv",
    ],
)

cc_library(
    name = "qemu_event_loop",
    srcs = ["src/qemu_event_loop.cpp"],
    hdrs = ["include/goldfish/async/qemu_event_loop.h"],
    includes = [
        "include",
        "//third_party/qemu",
        "//third_party/qemu/include",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":async_api",
        "//third_party/qemu:qemu-headers",
        "@com_google_absl//absl/log",
        "@com_google_absl//absl/status",
    ],
)

cc_library(
    name = "fake_qemu_callbacks",
    srcs = [
        "test/fake_qemu_callbacks.cpp",
    ],
    hdrs = [
        "test/fake_qemu_callbacks.h",
    ],
    includes = [
        "test",
    ],
    visibility = [
        "//hardware/generic/goldfish/android/async:__pkg__",
        "//hardware/generic/goldfish/emulator/plugin/vsock_goldfish:__pkg__",
    ],
    deps = [
        ":qemu_event_loop",
        "//third_party/qemu:qemu-headers",
    ],
)

cc_test(
    name = "eventloop_unittests",
    size = "small",
    timeout = "moderate",
    srcs = [
        "test/event_loop_test.cpp",
    ],
    copts = ["-Wno-unused-result"],
    includes = ["test"],
    linkopts = select({
        "@platforms//os:macos": ["-undefined error"],
        "//conditions:default": [],
    }),
    deps = [
        ":libuv_event_loop",
        ":qemu_event_loop",
        "//hardware/generic/goldfish/android/async:fake_qemu_callbacks",
        "//hardware/generic/goldfish/android/system:googletest_main",
    ],
)

cc_library(
    name = "libuv_sockets",
    srcs = [
        "src/libuv_impl.cpp",
    ],
    hdrs = [
        "include/goldfish/async/libuv_socket_factory.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":async_api",
        ":libuv_event_loop",
        ":uv_to_absl",
        "@com_google_absl//absl/log",
        "@com_google_absl//absl/log:check",
        "@com_google_absl//absl/strings",
        "@libuv",
    ],
)

cc_library(
    name = "qemu_sockets",
    srcs = [
        "src/qemu_sockets.cpp",
    ],
    hdrs = [
        "include/goldfish/async/qemu_socket_factory.h",
    ],
    includes = [
        "include",
        "//third_party/qemu/include",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":async_api",
        ":errno_to_absl",
        ":qemu_event_loop",
        "//hardware/generic/goldfish/android/sockets:socket_utils_impl",
        "@com_google_absl//absl/log",
        "@com_google_absl//absl/log:check",
        "@com_google_absl//absl/strings",
    ],
)

cc_test(
    name = "sockets_unittests",
    size = "small",
    srcs = [
        "test/async_socket_test.cpp",
    ],
    copts = ["-Wno-unused-result"],
    includes = ["test"],
    linkopts = select({
        "@platforms//os:macos": ["-undefined error"],
        "//conditions:default": [],
    }),
    deps = [
        ":fake_qemu_callbacks",
        ":libuv_sockets",
        ":qemu_sockets",
        "//hardware/generic/goldfish/android/system:googletest_main",
    ],
)

cc_binary(
    name = "sockets_perf",
    srcs = ["test/bm_libuv_sockets.cpp"],
    copts = [
        "-Wno-deprecated-declarations",
        "-Wno-unused-result",
    ],
    deps = [
        ":libuv_sockets",
        "@com_github_google_benchmark//:benchmark",
    ],
)
