load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "headers",
    hdrs = [
        "include/goldfish/battery/goldfish_battery.h",
        "include/goldfish/devices/battery/battery.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//android/async:async_api",
        "//emulator/libs/avd_universe:battery",
    ],
)

cc_library(
    name = "battery",
    srcs = [
        "battery.cc",
        "goldfish_battery.c",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":headers",
        "//android/async:async_api",
        "//emulator/libs/avd_universe:battery",
        "//emulator/libs/eventing",
        "@qemu//:qemu-headers",
    ],
    alwayslink = True,
)
