load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "headers",
    hdrs = [
        "include/android/battery/battery.h",
        "include/goldfish/battery/goldfish_battery.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "battery",
    srcs = [
        "battery.cpp",
        "goldfish_battery.c",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":headers",
        "//third_party/qemu:qemu-headers",
    ],
    alwayslink = True,
)
