load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "headers",
    hdrs = [
        "include/android/battery/battery.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
    ],
)

cc_library(
    name = "battery",
    srcs = [
        "src/battery.cpp",
        "src/goldfish_battery.c",
        "src/goldfish_battery.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":headers",
        "//third_party/qemu:libmodule-common",
        "//third_party/qemu:qemu-headers",
    ],
    alwayslink = True,
)
