cc_library(
    name = "grpc_device_impl",
    srcs = [
        "src/android/goldfish/EmulatorAdvertisement.cpp",
        "src/android/goldfish/EmulatorAdvertisement.h",
        "src/android/goldfish/agents/qemu-vm-operations-impl.c",
        "src/android/goldfish/display/QemuDisplayTransformer.cpp",
        "src/android/goldfish/display/SharedMemoryLibrary.cpp",
        "src/android/goldfish/grpc-service-device.c",
        "src/android/goldfish/grpc-service-impl.cpp",
    ],
    hdrs = [
        "include/android/goldfish/display/QemuDisplayTransformer.h",
        "include/android/goldfish/display/SharedMemoryLibrary.h",
        "include/android/goldfish/grpc-service-device.h",
    ],
    includes = [
        "include",
        "src",
    ],
    linkstatic = False,
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//external/crosvm/rutabaga_gfx",
        "//external/qemu:libmodule-common",
        "//external/qemu:qemu-headers",
        "//hardware/generic/goldfish/emulator/agents",
        "//hardware/generic/goldfish/emulator/android-grpc/event-stream",
        "//hardware/generic/goldfish/emulator/android-grpc/services-stack",
        "//hardware/generic/goldfish/emulator/plugin/avd:avd_hdrs",
        "@com_google_absl//absl/strings",
        "@pixman//:pixman-1",
        "@pixman//:pixman_simd",
    ],
    alwayslink = True,
)

cc_binary(
    name = "grpc",
    linkshared = True,
    visibility = [
        "//visibility:public",
    ],
    deps = [":grpc_device_impl"] +
           select({
               "@platforms//os:windows": [
                   "//external/qemu:qemu-system-x86_64.if",
               ],
               "//conditions:default": [],
           }),
)
