load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "headers",
    hdrs = [
        "include/goldfish/grpc/grpc-service-device.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//hardware/generic/goldfish/emulator/grpc/event-stream",
        "//hardware/generic/goldfish/emulator/grpc/services/emulator_controller:emulator_controller_cc_grpc",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/time",
    ],
)

cc_library(
    name = "grpc",
    srcs = [
        "grpc-service-device.c",
        "grpc-service-impl.cpp",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":headers",
        "//hardware/generic/goldfish/android/async:qemu_event_loop",
        "//hardware/generic/goldfish/emulator/config:emulator_advertisement",
        "//hardware/generic/goldfish/emulator/grpc/event-stream",
        "//hardware/generic/goldfish/emulator/grpc/services-stack",
        "//hardware/generic/goldfish/emulator/libs/device_registry",
        "//hardware/generic/goldfish/emulator/plugin/avd",
        "//hardware/generic/goldfish/emulator/plugin/avd:avd_hdrs",
        "//hardware/generic/goldfish/emulator/plugin/avd:global-event-loop",
        "//third_party/qemu:qemu-headers",
        "@abseil-cpp//absl/strings",
        "@grpc//:grpc++_reflection",
    ],
    alwayslink = True,
)
