load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

package(default_visibility = ["//hardware/generic/goldfish/emulator/grpc:__subpackages__"])

cc_library(
    name = "event-support",
    srcs = ["src/android/emulation/control/utils/EventWaiter.cpp"],
    hdrs = [
        "include/android/emulation/control/utils/CallbackEventSupport.h",
        "include/android/emulation/control/utils/EventSupport.h",
        "include/android/emulation/control/utils/EventWaiter.h",
        "include/android/emulation/control/utils/PropertyChangeSupport.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = ["@com_google_absl//absl/synchronization"],
)

cc_test(
    name = "event-support-test",
    srcs = [
        "test/android/emulation/control/utils/CallbackEvent_unittest.cpp",
        "test/android/emulation/control/utils/EventWaiter_unittest.cpp",
        "test/android/emulation/control/utils/GenericEventWaiter_unittest.cpp",
        "test/android/emulation/control/utils/PropertyChangeEvent_unittest.cpp",
    ],
    deps = [
        ":event-support",
        "//hardware/generic/goldfish/android/system:googletest_main",
        "@com_google_googletest//:gtest",
    ],
)
