load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "headers",
    hdrs = [
        "include/android/fingerprint/FingerprintDevice.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//emulator/hal/connector:connector_registry_hdrs",
    ],
)

cc_library(
    name = "fingerprint",
    srcs = [
        "src/fingerprint/FingerprintDevice.cpp",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":headers",
        "//emulator/hal/connector:qemud",
        "//emulator/hal/plug:hal_plug",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/strings:str_format",
    ],
    alwayslink = True,
)

cc_test(
    name = "fingerprint_unittests",
    srcs = [
        "test/fingerprint/FingerprintDevice_unittest.cpp",
    ],
    includes = ["test"],
    deps = [
        ":fingerprint",
        "//android/system:googletest_main",
        "//android/system:test-headers",
        "//emulator/config:avd-test",
        "//emulator/hal/connector:test-helpers",
        "//emulator/hal/plug:fake_vsock",
    ],
)

cc_library(
    name = "test_fingerprint",
    hdrs = [
        "test/FakeFingerprintDevice.h",
    ],
    includes = ["test"],
    visibility = ["//visibility:public"],
    deps = [
        ":headers",
    ],
)
