load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "headers",
    hdrs = [
        "include/android/fingerprint/FingerprintDevice.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//hardware/generic/goldfish/emulator/devices:connector_registry_hdrs",
    ],
)

cc_library(
    name = "fingerprint",
    srcs = [
        "src/fingerprint/FingerprintDevice.cpp",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":headers",
        "//hardware/generic/goldfish/emulator/devices:PingTopic",
        "//hardware/generic/goldfish/emulator/devices:cable",
        "//hardware/generic/goldfish/emulator/devices:qemud",
        "@com_google_absl//absl/log",
        "@com_google_absl//absl/strings:str_format",
    ],
    alwayslink = True,
)

cc_test(
    name = "fingerprint_unittests",
    srcs = [
        "test/fingerprint/FingerprintDevice_unittest.cpp",
    ],
    includes = ["test"],
    deps = [
        ":fingerprint",
        "//hardware/generic/goldfish/android/system:googletest_main",
        "//hardware/generic/goldfish/android/system:test-headers",
        "//hardware/generic/goldfish/emulator/config:avd-test",
        "//hardware/generic/goldfish/emulator/devices:test-helpers",
        "@aemu//:aemu-host-common-test-headers",
        "@aemu//base:aemu-base",
        "@aemu//base:aemu-base-headers",
        "@com_google_protobuf//:protobuf",
    ],
)

cc_library(
    name = "test_fingerprint",
    hdrs = [
        "test/FakeFingerprintDevice.h",
    ],
    includes = ["test"],
    visibility = ["//visibility:public"],
    deps = [
        ":headers",
    ],
)
