load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "fingerprint",
    srcs = [
        "fingerprint_device.cc",
    ],
    hdrs = [
        "include/goldfish/devices/fingerprint/fingerprint_device.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//emulator/hal/connector:connector_registry",
        "//emulator/hal/connector:qemud",
        "//emulator/hal/plug:hal_plug",
        "//emulator/libs/avd_universe:fingerprint",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/strings:str_format",
    ],
    alwayslink = True,
)

cc_test(
    name = "fingerprint_unittests",
    srcs = [
        "fingerprint_device_test.cc",
    ],
    includes = ["test"],
    visibility = ["//visibility:public"],
    deps = [
        ":fingerprint",
        "//android/system:googletest_main",
        "//android/system:test-headers",
        "//emulator/config:avd-test",
        "//emulator/hal/connector:test-helpers",
        "//emulator/hal/plug:fake_vsock",
    ],
)
