load("@goldfish_build//rules:clang_tidy.bzl", "clang_tidy_test")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

# maybe move to aemu
cc_library(
    name = "glm_helpers",
    hdrs = [
        "include/glm/glm_test_helpers.h",
        "include/goldfish/physics/glm_helpers.h",
    ],
    includes = ["include"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "@gfxstream//third_party/glm",
    ],
)

cc_library(
    name = "physics",
    srcs = [
        "ambient_environment.cc",
        "body_model.cc",
        "inertial_model.cc",
    ],
    hdrs = [
        "include/goldfish/physics/ambient_environment.h",
        "include/goldfish/physics/body_model.h",
        "include/goldfish/physics/inertial_model.h",
        "include/goldfish/physics/physics.h",
        "include/goldfish/physics/rotation.h",
        "include/goldfish/physics/skin_rotation.h",
    ],
    includes = ["include"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        ":glm_helpers",
        "//emulator/libs/archive",
        "//emulator/libs/archive:glm",
        "@abseil-cpp//absl/status",
    ],
)

cc_test(
    name = "physics_unittests",
    size = "small",
    srcs = [
        "ambient_environment_test.cc",
        "body_model_test.cc",
        "inertial_model_test.cc",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":physics",
        "//emulator/libs/system:test-headers",
        "//emulator/libs/test:googletest_main",
    ],
)

clang_tidy_test(
    name = "tidy",
    targets = [
        ":physics",
    ],
    tidy_config_file = "//:clang_tidy_config",
)
