load("@rules_python//python:defs.bzl", "py_test")

filegroup(
    name = "expected_contents",
    srcs = select({
        "@platforms//os:linux": [
            "testdata/release_zip_emulator_linux_x64.txt",
        ],
        "@platforms//os:macos": [
            "testdata/release_zip_emulator_mac_aarch64.txt",
        ],
        "@platforms//os:windows": [
            "testdata/release_zip_emulator_windows_x64.txt",
        ],
    }),
)

filegroup(
    name = "expected_contents_internal",
    srcs = select({
        "@platforms//os:linux": [
            "testdata/release_zip_emulator_linux_internal_x64.txt",
        ],
        "//conditions:default": [],
    }),
)

py_test(
    name = "release_zip_test",
    size = "small",
    srcs = ["release_zip_test.py"],
    args = [
        "--release_zip_path",
        "$(rlocationpath //emulator:release)",
        "--expected_path",
        "$(rlocationpath :expected_contents)",
    ],
    data = [
        ":expected_contents",
        "//emulator:release",
    ],
    deps = ["@rules_python//python/runfiles"],
)

py_test(
    name = "release_zip_internal_test",
    size = "small",
    srcs = ["release_zip_test.py"],
    args = [
        "--release_zip_path",
        "$(rlocationpath //emulator:release_internal)",
        "--expected_path",
        "$(rlocationpath :expected_contents_internal)",
    ],
    data = [
        ":expected_contents_internal",
        "//emulator:release_internal",
    ],
    main = "release_zip_test.py",
    target_compatible_with = ["@platforms//os:linux"],
    deps = ["@rules_python//python/runfiles"],
)
