load("@rules_java//java:java_test.bzl", "java_test")

java_test(
    name = "boot_test",
    data = [
        "//hardware/generic/goldfish/emulator/launcher:goldfish",
    ] + select({
        "@platforms//os:linux": [
            "//prebuilts/android-emulator-build/sdkhome-linux:sdkhome",
            "@android_minigbm-x86_64//:system_image",
        ],
        "@platforms//os:macos": [
            "//prebuilts/android-emulator-build/sdkhome-darwin:sdkhome",
            "@android_minigbm-arm64-v8a//:system_image",
        ],
        "//conditions:default": [],
    }),
    jvm_flags = [
        "-Demulator.test.emulator.path=hardware/generic/goldfish/emulator/launcher/goldfish",
        "-Demulator.test.emulator.is-emu-next=1",
    ] + select({
        "@platforms//os:linux": [
            "-Demulator.test.sdk.path=prebuilts/android-emulator-build/sdkhome-linux",
            "-Demulator.test.system.image.files=\"$(locations @android_minigbm-x86_64//:system_image)\"",
        ],
        "@platforms//os:macos": [
            "-Demulator.test.sdk.path=prebuilts/android-emulator-build/sdkhome-darwin",
            "-Demulator.test.system.image.files=\"$(locations @android_minigbm-arm64-v8a//:system_image)\"",
        ],
        "//conditions:default": [],
    }),
    tags = [
        "block-network",
        "manual",
    ],
    target_compatible_with = [
        # Currently launch and boot tests fail on Mac.
        # TODO(b/435653752): Fix and re-enable for other platforms.
        "@platforms//os:linux",
    ],
    test_class = "com.android.tools.idea.EmulatorTest",
    runtime_deps = ["//tools/emulator/tests:emulator.tests"],
)

test_suite(
    name = "integration_tests",
    tags = ["manual"],
    tests = [
        ":boot_test",
    ],
)
