load("@goldfish_build//rules:clang_tidy.bzl", "clang_tidy_test")
load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "secrets",
    srcs = ["adbkey.cc"],
    hdrs = ["include/goldfish/adb/adbkey.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//emulator/libs/system",
        "@abseil-cpp//absl/log",
        "@boringssl//:ssl",
    ],
)

cc_test(
    name = "secrets_unittests",
    srcs = ["adbkey_test.cc"],
    visibility = ["//visibility:public"],
    deps = [
        ":secrets",
        "//emulator/libs/system:test-headers",
        "//emulator/libs/test:googletest_main",
    ],
)

clang_tidy_test(
    name = "tidy",
    targets = [
        "secrets_unittests",
        "secrets",
    ],
    tidy_config_file = "//:clang_tidy_config",
)
