load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "secrets",
    srcs = ["adbkey.cc"],
    hdrs = ["include/goldfish/adb/adbkey.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//android/system",
        "//emulator/config:config_dirs",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
        "@aemu//base:aemu-base",
        "@boringssl//:ssl",
    ],
)

cc_test(
    name = "secrets_unittests",
    srcs = ["adbkey_test.cc"],
    visibility = ["//visibility:public"],
    deps = [
        ":secrets",
        "//android/system:googletest_main",
        "//android/system:test-headers",
    ],
)
