load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "gps",
    hdrs = [
        "include/goldfish/gps/Location.h",
    ],
    includes = ["include"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "@abseil-cpp//absl/strings:str_format",
    ],
)
