load("@goldfish_build//rules:clang_tidy.bzl", "clang_tidy_test")
load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "bootproperties",
    srcs = ["boot_properties_device.cc"],
    hdrs = [
        "include/goldfish/devices/boot/boot_properties_device.h",
        "include/goldfish/devices/boot/boot_property_string.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//android/status_macros",
        "//emulator/hal/connector:connector_registry",
        "//emulator/hal/connector:qemud",
        "//emulator/hal/plug:hal_plug",
        "@abseil-cpp//absl/container:flat_hash_map",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings:str_format",
    ],
    alwayslink = True,
)

cc_test(
    name = "bootproperties_unittests",
    srcs = ["boot_properties_device_test.cc"],
    visibility = ["//visibility:public"],
    deps = [
        ":bootproperties",
        "//android/status_macros:status_matcher_macros",
        "//android/system:googletest_main",
        "//emulator/hal/connector:test-helpers",
        "//emulator/hal/plug:fake_vsock",
        "@abseil-cpp//absl/status:status_matchers",
    ],
)

clang_tidy_test(
    name = "tidy",
    targets = [
        ":bootproperties",
    ],
    tidy_config_file = "//:clang_tidy_config",
)
