load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "headers",
    hdrs = [
        "include/android/boot/BootPropertiesDevice.h",
        "include/android/boot/BootPropertyString.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//emulator/hal/connector:connector_registry",
    ],
)

cc_library(
    name = "bootproperties",
    srcs = [
        "src/boot/BootPropertiesDevice.cpp",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":headers",
        "//emulator/hal/connector:qemud",
        "//emulator/hal/plug:hal_plug",
        "@abseil-cpp//absl/container:flat_hash_map",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/strings:str_format",
        "@aemu//base:event-support",
    ],
    alwayslink = True,
)

cc_test(
    name = "bootproperties_unittests",
    srcs = [
        "test/boot/BootPropertiesDevice_unittest.cpp",
    ],
    includes = ["test"],
    deps = [
        ":bootproperties",
        "//android/system:googletest_main",
        "//android/system:test-headers",
        "//emulator/config:avd-test",
        "//emulator/hal/connector:test-helpers",
        "//emulator/hal/plug:fake_vsock",
    ],
)

cc_library(
    name = "test_bootproperties",
    hdrs = [
        "test/FakeBootPropertiesDevice.h",
    ],
    includes = ["test"],
    visibility = ["//visibility:public"],
    deps = [
        ":headers",
    ],
)
