load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "headers",
    hdrs = [
        "include/android/boot/BootPropertiesDevice.h",
        "include/android/boot/BootPropertyString.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//hardware/generic/goldfish/emulator/devices:connector_registry_hdrs",
    ],
)

cc_library(
    name = "bootproperties",
    srcs = [
        "src/boot/BootPropertiesDevice.cpp",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":headers",
        "//hardware/generic/goldfish/emulator/devices:PingTopic",
        "//hardware/generic/goldfish/emulator/devices:cable",
        "//hardware/generic/goldfish/emulator/devices:qemud",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/strings:str_format",
        "@aemu//base:event-support",
    ],
    alwayslink = True,
)

cc_test(
    name = "bootproperties_unittests",
    srcs = [
        "test/boot/BootPropertiesDevice_unittest.cpp",
    ],
    includes = ["test"],
    deps = [
        ":bootproperties",
        "//hardware/generic/goldfish/android/system:googletest_main",
        "//hardware/generic/goldfish/android/system:test-headers",
        "//hardware/generic/goldfish/emulator/config:avd-test",
        "//hardware/generic/goldfish/emulator/devices:test-helpers",
        "@aemu//:aemu-host-common-test-headers",
        "@aemu//base:aemu-base",
        "@aemu//base:aemu-base-headers",
        "@protobuf",
    ],
)

cc_library(
    name = "test_bootproperties",
    hdrs = [
        "test/FakeBootPropertiesDevice.h",
    ],
    includes = ["test"],
    visibility = ["//visibility:public"],
    deps = [
        ":headers",
    ],
)
