load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "array_size",
    hdrs = ["include/goldfish/base/array_size.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "base",
    hdrs = [
        "include/goldfish/base/intrusive_ptr.h",
        "include/goldfish/base/unique_handle.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    alwayslink = True,
)

cc_test(
    name = "base_unittests",
    srcs = [
        "intrusive_ptr_test.cc",
        "unique_handle_test.cc",
    ],
    includes = ["test"],
    visibility = ["//visibility:public"],
    deps = [
        ":base",
        "//android/system:googletest_main",
    ],
)
