load("@goldfish_build//rules:clang_tidy.bzl", "clang_tidy_test")
load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "network",
    srcs = [
        "dns_resolver.cc",
        "endpoint.cc",
        "ip_address.cc",
    ],
    hdrs = [
        "include/goldfish/network/dns_resolver.h",
        "include/goldfish/network/endpoint.h",
        "include/goldfish/network/ip_address.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:check",
        "@abseil-cpp//absl/status:statusor",
        "@aemu//base:event-support",
        "@c-ares//:ares",
    ],
)

cc_test(
    name = "network_unittests",
    size = "small",
    srcs = [
        "dns_resolver_test.cc",
        "endpoint_test.cc",
        "ip_address_test.cc",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":network",
        "//android/system:googletest_main",
        "//android/system:test-headers",
        "@abseil-cpp//absl/status:status_matchers",
    ],
)

clang_tidy_test(
    name = "tidy",
    targets = [
        ":network",
    ],
    tidy_config_file = "//:clang_tidy_config",
)
