load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "network",
    srcs = [
        "src/dns_resolver.cpp",
        "src/endpoint.cpp",
        "src/ip_address.cpp",
    ],
    hdrs = [
        "include/goldfish/network/dns_resolver.h",
        "include/goldfish/network/endpoint.h",
        "include/goldfish/network/ip_address.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:check",
        "@abseil-cpp//absl/status:statusor",
        "@aemu//base:event-support",
        "@c-ares//:ares",
    ],
)

cc_test(
    name = "network_unittests",
    size = "small",
    srcs = [
        "test/dns_resolver_test.cpp",
        "test/endpoint_test.cpp",
        "test/ip_address_test.cpp",
    ],
    deps = [
        ":network",
        "//android/system:googletest_main",
        "@abseil-cpp//absl/status:status_matchers",
    ],
)
