load("@goldfish_build//rules:clang_tidy.bzl", "clang_tidy_test")
load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "emulator_advertisement",
    srcs = ["emulator_advertisement.cc"],
    hdrs = ["include/goldfish/discovery/emulator_advertisement.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//emulator/libs/ini_file",
        "//emulator/libs/sockets",
        "//emulator/libs/system",
        "@abseil-cpp//absl/container:flat_hash_map",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
    ],
)

cc_test(
    name = "emulator_advertisement_test",
    size = "small",
    srcs = ["emulator_advertisement_test.cc"],
    visibility = ["//visibility:public"],
    deps = [
        ":emulator_advertisement",
        "//emulator/libs/system:test-headers",
        "//emulator/libs/test:googletest_main",
        "@abseil-cpp//absl/status:status_matchers",
    ],
)

clang_tidy_test(
    name = "tidy",
    targets = [
        ":emulator_advertisement",
        ":emulator_advertisement_test",
    ],
    tidy_config_file = "//:clang_tidy_config",
)
