load("@bazel_lib//lib:output_files.bzl", "output_files")
load("@bazel_skylib//rules:build_test.bzl", "build_test")
load("@goldfish_build//rules/native:native_binaries.bzl", "stripped_binaries")
load("@rules_license//rules:license.bzl", "license")
load("@rules_license//rules:license_kind.bzl", "license_kind")
load("@rules_pkg//pkg:mappings.bzl", "pkg_attributes", "pkg_filegroup", "pkg_files")
load("@rules_pkg//pkg:zip.bzl", "pkg_zip")
load(
    "//emulator/tools:packaging.bzl",
    "breakpad_symbols_pkg",
    "build_id_from_command_line",
    "native_symbols_pkg",
    "remapped_pkg_files",
)

package(
    default_applicable_licenses = [":license"],
    default_visibility = ["//visibility:public"],
)

license(
    name = "license",
    license_kinds = [
        ":SPDX-license-identifier-Apache-2.0",
    ],
    visibility = [":__subpackages__"],
)

license_kind(
    name = "SPDX-license-identifier-Apache-2.0",
    conditions = ["notice"],
    url = "https://spdx.org/licenses/Apache-2.0.html",
)

# You can pass in the build id from the bazel command line flag
# as follows:
# --@goldfish//emulator:build_id=P123
build_id_from_command_line(
    name = "build_id",
    build_setting_default = "developer",
)

launcher_binaries = [
    "//emulator/launcher",
]

binaries = [
    "//emulator/crashreport",
    "//third_party/sparse:img2simg",
    "@qemu//:qemu-img",
    "@crashpad//handler:crashpad_handler",
    #"@netsim//:netsimd",
] + select({
    "@platforms//os:windows": [
        "@goldfish_prebuilts_common//netsim:netsim_windows_x86_64",
        "@qemu//:qemu-system-x86_64",
    ],
    "@platforms//os:macos": [
        "@goldfish_prebuilts_common//netsim:netsim_darwin_aarch64",
        "@qemu//:qemu-system-x86_64_signed",
        "@qemu//:qemu-system-aarch64_signed",
    ],
    "//conditions:default": [
        "@goldfish_prebuilts_common//netsim:netsim_linux_x86_64",
        "@qemu//:qemu-system-x86_64",
        "@qemu//:qemu-system-aarch64",
        # We currently don't have riscv images
        # "@qemu//:qemu-system-riscv64",
    ],
})

egl_binaries = select({
    "@platforms//os:macos": [
        "@goldfish_prebuilts_common//vulkan:lib_darwin_aarch64",
        "@goldfish_prebuilts_common//ANGLE:lib_darwin_aarch64",
        "@goldfish_prebuilts_common//vulkan:icds_darwin_aarch64",
    ],
    "@platforms//os:linux": [
        "@goldfish_prebuilts_common//swiftshader:lib_linux_x86_64",
    ],
    "@platforms//os:windows": [
        "@goldfish_prebuilts_common//vulkan:lib_windows_x86_64",
        "@goldfish_prebuilts_common//ANGLE:lib_windows_x86_64",
        "@goldfish_prebuilts_common//vulkan:icds_windows_x86_64",
    ],
    "//conditions:default": [],
})

vulkan_binaries = select({
    "@platforms//os:macos": [
        "@goldfish_prebuilts_common//vulkan:lib_darwin_aarch64",
        "@goldfish_prebuilts_common//vulkan:icds_darwin_aarch64",
    ],
    "@platforms//os:linux": [
        "@goldfish_prebuilts_common//vulkan:lib_linux_x86_64",
        "@goldfish_prebuilts_common//vulkan:icds_linux_x86_64",
    ],
    "@platforms//os:windows": [
        "@goldfish_prebuilts_common//vulkan:lib_windows_x86_64",
        "@goldfish_prebuilts_common//vulkan:icds_windows_x86_64",
    ],
    "//conditions:default": [],
})

plugin_binaries = [
    "//emulator/plugin:goldfish_x86_64",
    "@crosvm//:rutabaga_ffi",
] + select({
    "@platforms//os:windows": [],
    "//conditions:default": [
        "//emulator/plugin:goldfish_aarch64",
        # We currently don't have riscv images
        # "//emulator/plugin:goldfish_riscv64",
    ],
}) + select({
    "@platforms//os:linux": [
        # For netsimd prebuilt
        "@goldfish_prebuilts_common//vulkan:linux_libc++",
        # TODO(b/434942959,whollins): Re-add this.
        #"@gcc_lib//:libpulse",
    ],
    "//conditions:default": [
    ],
})

all_binaries = launcher_binaries + binaries + plugin_binaries

stripped_binaries(
    name = "goldfish_binaries_stripped",
    srcs = all_binaries,
)

# Define pkg_files rules
pkg_files(
    # Note no prefix.
    name = "launcher",
    srcs = launcher_binaries,
    attributes = pkg_attributes(
        mode = "0755",
    ),
    renames = select({
        "@platforms//os:windows": {
            "//emulator/launcher": "emulator.exe",
        },
        "//conditions:default": {
            "//emulator/launcher": "emulator",
        },
    }),
)

remapped_pkg_files(
    name = "launcher_stripped",
    src = ":launcher",
    transform = ":goldfish_binaries_stripped",
)

pkg_files(
    name = "binaries",
    srcs = binaries,
    attributes = pkg_attributes(
        mode = "0755",
    ),
    # Where it should be in the final package
    prefix = "bin",
    renames = select({
        "@platforms//os:windows": {
            "@qemu//:qemu-system-x86_64": "qemu-system-x86_64.exe",
        },
        "@platforms//os:macos": {
            "@qemu//:qemu-system-x86_64_signed": "qemu-system-x86_64",
            "@qemu//:qemu-system-aarch64_signed": "qemu-system-aarch64",
        },
        "//conditions:default": {
            "@qemu//:qemu-system-x86_64": "qemu-system-x86_64",
            "@qemu//:qemu-system-aarch64": "qemu-system-aarch64",
            # We currently don't have riscv images
            # "@qemu//:qemu-system-riscv64": "qemu-system-riscv64",
        },
    }),
)

remapped_pkg_files(
    name = "binaries_stripped",
    src = ":binaries",
    transform = ":goldfish_binaries_stripped",
)

pkg_files(
    name = "plugins",
    srcs = plugin_binaries,
    prefix = "lib/qemu",
)

pkg_files(
    name = "egl",
    srcs = egl_binaries,
    prefix = "lib64",
)

pkg_files(
    name = "vulkan",
    srcs = vulkan_binaries,
    prefix = "lib64/vulkan",
)

pkg_files(
    name = "data_virtualscene_Toren1BD",
    srcs = ["@goldfish_prebuilts_common//virtualscene/Toren1BD"],
    prefix = "data/virtualscene/Toren1BD",
)

remapped_pkg_files(
    name = "plugins_stripped",
    src = ":plugins",
    transform = ":goldfish_binaries_stripped",
)

pkg_files(
    name = "emulator-access",
    srcs = ["//emulator/grpc/security:emulator-access"],
    prefix = "lib",
)

output_files(
    name = "vctools-dlls-needed",
    paths = [
        "../goldfish_build++toolchain+vctools/msvc/bin/Hostx64/x64/msvcp140.dll",
        "../goldfish_build++toolchain+vctools/msvc/bin/Hostx64/x64/vcruntime140.dll",
        "../goldfish_build++toolchain+vctools/msvc/bin/Hostx64/x64/vcruntime140_1.dll",
    ],
    target = "@vctools//:dlls",
    target_compatible_with = ["@platforms//os:windows"],
)

pkg_files(
    # Note no prefix. These must go in the same dir as emulator.exe.
    name = "win-dlls",
    srcs = [":vctools-dlls-needed"],
    target_compatible_with = ["@platforms//os:windows"],
)

pkg_files(
    name = "qemu-keymaps",
    srcs = ["@qemu//:qemu-keymaps"],
    prefix = "share/qemu/keymaps",
)

pkg_files(
    name = "qemu-roms",
    srcs = ["@qemu//:qemu-roms"],
    prefix = "share/qemu",
)

pkg_filegroup(
    name = "emulator-dir",
    srcs = [
        ":binaries_stripped",
        ":data_virtualscene_Toren1BD",
        ":egl",
        ":emulator-access",
        ":launcher_stripped",
        ":plugins_stripped",
        ":qemu-keymaps",
        ":qemu-roms",
        ":vulkan",
    ] + select({
        "@platforms//os:windows": [":win-dlls"],
        "//conditions:default": [],
    }),
    prefix = "emulator",
)

pkg_zip(
    name = "release",
    srcs = ["emulator-dir"],
    package_file_name = "sdk-repo-{platform}-{product_name}-{build_id}.zip",
    package_variables = "//emulator/tools:aemu_version_info",
    tags = ["manual"],
)

filegroup(
    name = "goldfish_binaries",
    srcs = all_binaries,
)

breakpad_symbols_pkg(
    name = "package_goldfish_symbols",
    binaries = all_binaries,
    package_file_name = "sdk-repo-{platform}-{product_name}-breakpad-symbols-{build_id}.zip",
    package_variables = "//emulator/tools:aemu_version_info",
)

native_symbols_pkg(
    name = "package_goldfish_native_symbols",
    binaries = all_binaries,
    layout_templates = {
        "launcher": ":launcher",
        "qemu": ":binaries",
        "plugins": ":plugins",
    },
    package_file_name = "sdk-repo-{platform}-{product_name}-native-symbols-{build_id}.zip",
    package_variables = "//emulator/tools:aemu_version_info",
)

build_test(
    name = "release_build_test",
    tags = ["manual"],
    targets = [":release"],
)

test_suite(
    # This contains all unit tests from external packages and dependencies
    # These are not run by default.
    name = "external_unit_tests",
    tags = ["manual"],
    tests = [
        "@boringssl//:crypto_test",
        "@boringssl//:decrepit_test",
        "@boringssl//:pki_test",
        "@boringssl//:ssl_test",
        "@boringssl//:urandom_test",
        "@crashpad//:crashpad_tests",
        "@ffmpeg//:tests",
        "@libyuv//:libyuv_unittest",
    ],
)
