load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "cpu",
    srcs = glob([
        "src/android/goldfish/cpu/*.cpp",
        "src/android/goldfish/cpu/*.h",
    ]) + select({
        "@platforms//os:windows": [
            "src/android/windows_installer.cpp",
            "src/android/windows_installer.h",
        ],
        "//conditions:default": [],
    }),
    hdrs = glob([
        "include/android/goldfish/cpu/*.h",
    ]),
    copts =
        select({
            "@platforms//os:windows": ["-Wno-microsoft-goto"],
            "//conditions:default": [],
        }),
    includes = [
        "include",
        "src",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//hardware/generic/goldfish/android/system",
        "//hardware/google/aemu/base:aemu-base",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings",
        "@com_google_absl//absl/strings:str_format",
    ],
)

cc_test(
    name = "cpu_unittests",
    srcs = glob(
        [
            "test/**/*.cpp",
            "test/**/*.h",
        ],
        exclude = ["test/**/Win32"],
    ),
    linkopts = select({
        "@platforms//os:macos": ["-undefined error"],
        "//conditions:default": [],
    }),
    deps = [
        ":cpu",
        "//hardware/generic/goldfish/android/system:test-headers",
        "@com_google_googletest//:gtest_main",
    ],
)
