load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "cpu",
    srcs = [
        "src/android/goldfish/cpu/AppleCpuAccelerator.h",
        "src/android/goldfish/cpu/CpuAccelerator.cpp",
        "src/android/goldfish/cpu/x86_cpuid.cpp",
        "src/android/goldfish/cpu/x86_cpuid.h",
    ] + select({
        "@platforms//os:windows": [
            "src/android/windows_installer.cpp",
            "src/android/windows_installer.h",
        ],
        "//conditions:default": [],
    }),
    hdrs = [
        "include/android/goldfish/cpu/CpuAccelerator.h",
        "include/android/goldfish/cpu/cpu_accelerator.h",
    ],
    copts =
        select({
            "@platforms//os:windows": ["-Wno-microsoft-goto"],
            "//conditions:default": [],
        }),
    includes = [
        "include",
        "src",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//android/system",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
        "@aemu//base:aemu-base",
    ],
)

cc_test(
    name = "cpu_unittests",
    srcs = ["test/android/goldfish/cpu/x86_cpuid_unittest.cpp"],
    linkopts = select({
        "@platforms//os:macos": ["-undefined error"],
        "//conditions:default": [],
    }),
    visibility = ["//visibility:public"],
    deps = [
        ":cpu",
        "//android/system:googletest_main",
        "//android/system:test-headers",
    ],
)
