cc_library(
    name = "sample_device_impl",
    srcs = [
        "src/android/goldfish/sample-plugin.c",
    ],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//external/qemu:libchardev",
        "//external/qemu:libhwcore",
        "//external/qemu:libmodule-common",
    ],
    alwayslink = True,
)

cc_binary(
    name = "sample",
    linkshared = True,
    visibility = [
        "//visibility:public",
    ],
    deps = [":sample_device_impl"] +
           select({
               "@platforms//os:windows": [
                   "//external/qemu:qemu-system-x86_64.if",
               ],
               "//conditions:default": [],
           }),
)
