load("@goldfish_build//rules:clang_tidy.bzl", "clang_tidy_test")
load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "hal_plug",
    srcs = [
        "logging.cc",
    ],
    hdrs = [
        "include/goldfish/devices/internal/hal_plug.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:check",
    ],
)

cc_library(
    name = "hal_plug_factory",
    srcs = ["hal_plug_factory.cc"],
    hdrs = ["include/goldfish/devices/hal_plug_factory.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":hal_plug",
        ":hal_plug_to_i_plug_adapter",
        ":marshalling_hal_socket",
        "//emulator/plugin/vsock_goldfish:goldfish_vsock_hdrs",
        "@abseil-cpp//absl/log:check",
    ],
)

cc_library(
    name = "marshalling_hal_socket",
    srcs = ["marshalling_hal_socket.cc"],
    hdrs = ["include/goldfish/devices/marshalling_hal_socket.h"],
    includes = ["include"],
    deps = [
        ":hal_plug",
        "//emulator/hal/connector:cable",
        "//emulator/libs/async:async_api",
        "@abseil-cpp//absl/log:check",
    ],
)

cc_library(
    name = "hal_plug_to_i_plug_adapter",
    srcs = ["hal_plug_to_i_plug_adapter.cc"],
    hdrs = ["include/goldfish/devices/hal_plug_to_i_plug_adapter.h"],
    includes = ["include"],
    deps = [
        ":hal_plug",
        ":marshalling_hal_socket",
        "//emulator/hal/connector:cable",
        "//emulator/libs/async:async_api",
        "@abseil-cpp//absl/log:check",
    ],
)

cc_library(
    name = "fake_vsock",
    srcs = [
        "fake_vsock.cc",
    ],
    hdrs = [
        "test/fake_vsock.h",
        "test/hal_plug_testing_friend.h",
    ],
    includes = ["test"],
    visibility = [
        "//emulator/hal:__subpackages__",
        "//emulator/hal/connector:__subpackages__",
        "//emulator/plugin/grpc/services:__subpackages__",
    ],
    deps = [
        "//emulator/hal/connector:cable",
        "//emulator/plugin/vsock_goldfish:goldfish_vsock_hdrs",
    ],
)

cc_test(
    name = "hal_plug_adapter_unittests",
    size = "small",
    srcs = [
        "hal_plug_adapter_concurrency_test.cc",
        "hal_plug_adapter_test.cc",
        "hal_plug_factory_listen_test.cc",
        "hal_plug_factory_test.cc",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":fake_vsock",
        ":hal_plug_factory",
        ":hal_plug_to_i_plug_adapter",
        ":marshalling_hal_socket",
        "//emulator/hal/connector:connector_registry_impl",
        "//emulator/libs/async:async_testing",
        "//emulator/libs/async:libuv_event_loop",
        "//emulator/libs/async:threaded_event_loop",
        "//emulator/libs/test:googletest_main",
        "@abseil-cpp//absl/status:status_matchers",
        "@abseil-cpp//absl/synchronization",
    ],
)

clang_tidy_test(
    name = "tidy",
    targets = [
        ":hal_plug",
        ":hal_plug_factory",
        ":hal_plug_to_i_plug_adapter",
        ":marshalling_hal_socket",
    ],
    tidy_config_file = "//:clang_tidy_config",
)
