load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "hal_plug",
    srcs = [
        "logging.cpp",
    ],
    hdrs = [
        "include/goldfish/hal/plug/HalPlug.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "@abseil-cpp//absl/log",
    ],
)

cc_library(
    name = "hal_plug_factory",
    srcs = ["HalPlugFactory.cpp"],
    hdrs = ["include/goldfish/hal/plug/HalPlugFactory.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":hal_plug",
        ":hal_plug_to_i_plug_adapter",
        ":marshalling_hal_socket",
        "//hardware/generic/goldfish/emulator/plugin/vsock_goldfish:goldfish_vsock_hdrs",
    ],
)

cc_library(
    name = "marshalling_hal_socket",
    srcs = ["MarshallingHalSocket.cpp"],
    hdrs = ["include/goldfish/hal/plug/MarshallingHalSocket.h"],
    includes = ["include"],
    deps = [
        ":hal_plug",
        "//hardware/generic/goldfish/android/async:async_api",
        "//hardware/generic/goldfish/emulator/devices:cable",
    ],
)

cc_library(
    name = "hal_plug_to_i_plug_adapter",
    srcs = ["HalPlugToIPlugAdapter.cpp"],
    hdrs = ["include/goldfish/hal/plug/HalPlugToIPlugAdapter.h"],
    includes = ["include"],
    deps = [
        ":hal_plug",
        ":marshalling_hal_socket",
        "//hardware/generic/goldfish/android/async:async_api",
        "//hardware/generic/goldfish/emulator/devices:cable",
    ],
)

cc_library(
    name = "fake_vsock",
    srcs = [
        "test/fake_vsock.cpp",
    ],
    hdrs = [
        "test/fake_vsock.h",
        "test/hal_plug_testing_friend.h",
    ],
    includes = ["test"],
    visibility = [
        "//hardware/generic/goldfish/emulator/devices:__subpackages__",
        "//hardware/generic/goldfish/emulator/grpc/services/emulator_controller/server:__subpackages__",
        "//hardware/generic/goldfish/emulator/hal:__subpackages__",
    ],
    deps = [
        "//hardware/generic/goldfish/emulator/devices:cable",
        "//hardware/generic/goldfish/emulator/plugin/vsock_goldfish:goldfish_vsock_hdrs",
    ],
)

cc_test(
    name = "hal_plug_adapter_unittests",
    size = "small",
    srcs = [
        "test/hal_plug_adapter_concurrency_test.cpp",
        "test/hal_plug_adapter_unittest.cpp",
        "test/hal_plug_factory_listen_test.cpp",
        "test/hal_plug_factory_test.cpp",
    ],
    deps = [
        ":fake_vsock",
        ":hal_plug_factory",
        ":hal_plug_to_i_plug_adapter",
        ":marshalling_hal_socket",
        "//hardware/generic/goldfish/android/async:async_testing",
        "//hardware/generic/goldfish/android/async:libuv_event_loop",
        "//hardware/generic/goldfish/android/system:googletest_main",
        "//hardware/generic/goldfish/emulator/devices:connector_registry_impl",
        "@abseil-cpp//absl/synchronization",
    ],
)
