load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "host",
    srcs = ["src/AdbHostServer.cpp"],
    hdrs = ["include/android/emulation/control/adb/AdbHostServer.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//android/sockets",
        "//android/system",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
        "@aemu//base:aemu-base",
    ],
)

cc_test(
    name = "host_unitests",
    srcs = ["test/AdbHostServer_unittest.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        ":host",
        "//android/system:googletest_main",
        "//android/system:test-headers",
        "@aemu//base:aemu-base",
    ],
)
