load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "host",
    srcs = ["adb_host_server.cc"],
    hdrs = ["include/goldfish/adb/adb_host_server.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//android/sockets",
        "//android/system",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
        "@aemu//base:aemu-base",
    ],
)

cc_test(
    name = "host_unittests",
    srcs = [
        "TestInputBufferSocketServerThread.h",
        "adb_host_server_test.cc",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":host",
        "//android/system:googletest_main",
        "//android/system:test-headers",
    ],
)
