load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//emulator/grpc:__subpackages__"])

cc_library(
    name = "event-stream",
    hdrs = ["include/android/emulation/control/utils/GrpcEventStreamSupport.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//emulator/grpc/async",
        "@aemu//base:event-support",
        "@grpc//:grpc++",
    ],
)
