load("@goldfish_build//rules:clang_tidy.bzl", "clang_tidy_test")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "zigzag",
    hdrs = [
        "include/goldfish/archive/zigzag/zigzag.h",
    ],
    includes = ["include"],
    visibility = [
        "//visibility:public",
    ],
)

cc_test(
    name = "zigzag_unittests",
    size = "small",
    srcs = [
        "zigzag_tests.cc",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":zigzag",
        "//emulator/libs/test:googletest_main",
    ],
)

cc_library(
    name = "archive",
    srcs = [
        "reader.cc",
        "writer.cc",
    ],
    hdrs = [
        "include/goldfish/archive/reader.h",
        "include/goldfish/archive/writer.h",
    ],
    includes = ["include"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        ":zigzag",
        "@abseil-cpp//absl/status:statusor",
    ],
)

cc_library(
    name = "collections",
    srcs = [
        "string.cc",
    ],
    hdrs = [
        "include/goldfish/archive/collections/deque.h",
        "include/goldfish/archive/collections/pair.h",
        "include/goldfish/archive/collections/set.h",
        "include/goldfish/archive/collections/string.h",
        "include/goldfish/archive/collections/vector.h",
    ],
    includes = ["include"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        ":archive",
        "//emulator/libs/status_macros",
    ],
)

cc_library(
    name = "time",
    srcs = [
        "time.cc",
    ],
    hdrs = [
        "include/goldfish/archive/time.h",
    ],
    includes = ["include"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        ":archive",
        "@abseil-cpp//absl/time",
    ],
)

cc_library(
    name = "DequeArchive",
    srcs = [
        "deque_archive.cc",
    ],
    hdrs = [
        "include/goldfish/archive/deque_archive.h",
        "include/goldfish/archive/deque_reader.h",
        "include/goldfish/archive/deque_writer.h",
    ],
    includes = ["include"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        ":archive",
        "//emulator/libs/debug",
    ],
)

cc_test(
    name = "reader_writer_unittests",
    size = "small",
    srcs = [
        "reader_writer_tests.cc",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":DequeArchive",
        "//emulator/libs/test:googletest_main",
        "@abseil-cpp//absl/status:status_matchers",
    ],
)

cc_test(
    name = "collections_unittests",
    size = "small",
    srcs = [
        "collections_tests.cc",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":DequeArchive",
        ":collections",
        "//emulator/libs/test:googletest_main",
        "@abseil-cpp//absl/status:status_matchers",
    ],
)

cc_test(
    name = "time_unittests",
    size = "small",
    srcs = [
        "time_tests.cc",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":DequeArchive",
        ":time",
        "//emulator/libs/test:googletest_main",
        "@abseil-cpp//absl/status:status_matchers",
    ],
)

cc_library(
    name = "QEMUFileArchive",
    srcs = ["qemu_file_archive.cc"],
    hdrs = [
        "include/goldfish/archive/qemu_file_reader.h",
        "include/goldfish/archive/qemu_file_writer.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":archive",
        "@qemu//:qemu-headers-exported",
    ],
)

test_suite(
    name = "archive_unittests",
    tests = [
        ":reader_writer_unittests",
        ":zigzag_unittests",
    ],
)

clang_tidy_test(
    name = "tidy",
    targets = [
        ":zigzag",
        ":archive",
        ":time",
        ":DequeArchive",
        ":QEMUFileArchive",
        ":zigzag_unittests",
        ":reader_writer_unittests",
        ":time_unittests",
    ],
    tidy_config_file = "//:clang_tidy_config",
)
