test_suite(
    name = "emulator_android_tests",
    tests = [
        "//hardware/generic/goldfish/android/cpu:cpu_unittests",
        "//hardware/generic/goldfish/android/files:files_unittests",
        "//hardware/generic/goldfish/android/logging:backend_unittests",
        "//hardware/generic/goldfish/android/looper:looper_unittests",
        "//hardware/generic/goldfish/android/memory:memory_unittests",
        "//hardware/generic/goldfish/android/process:process_unittests",
        "//hardware/generic/goldfish/android/sockets:sockets_unittests",
        "//hardware/generic/goldfish/android/system:system-unittests",
        "//hardware/generic/goldfish/android/threads:threads_unittests",
    ],
)
