test_suite(
    name = "emulator_android_tests",
    tests = [
        "//android/cpu:cpu_unittests",
        "//android/files:files_unittests",
        "//android/logging:backend_unittests",
        "//android/process:process_unittests",
        "//android/sockets:sockets_unittests",
        "//android/system:system-unittests",
    ],
)
