load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "ext4",
    srcs = [
        "ext4_resize.cc",
        "ext4_utils.cc",
    ],
    hdrs = [
        "include/android/filesystems/ext4_resize.h",
        "include/android/filesystems/ext4_utils.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//android/system",
        "//emulator/libs/process",
        "//third_party/ext4_utils",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:absl_log",
    ],
)
