load("@goldfish_build//rules:clang_tidy.bzl", "clang_tidy_test")
load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

package(default_visibility = ["//visibility:public"])

WEBRTC_COPTS = select({
    "@platforms//os:windows": ["/GR-"],
    "//conditions:default": ["-fno-rtti"],
})

cc_library(
    name = "qemu_audio_capture",
    srcs = ["qemu_audio_capture.cc"],
    hdrs = ["include/goldfish/audio/qemu_audio_capture.h"],
    includes = ["include"],
    deps = [
        "//emulator/plugin/vminterface:vm_lock",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:check",
        "@abseil-cpp//absl/status",
        "@qemu//:aemu_func_defs",
        "@qemu//:qemu-headers-exported",
    ],
)

cc_library(
    name = "test_qemu_audio_stub",
    testonly = True,
    srcs = ["test_qemu_audio_stub.cc"],
    hdrs = ["test_qemu_audio_stub.h"],
    deps = [
        "@abseil-cpp//absl/base:core_headers",
        "@abseil-cpp//absl/synchronization",
    ],
)

cc_library(
    name = "qemu_audio_source",
    srcs = ["qemu_audio_source.cc"],
    hdrs = ["include/goldfish/audio/qemu_audio_source.h"],
    copts = WEBRTC_COPTS,
    includes = ["include"],
    deps = [
        ":qemu_audio_capture",
        "//emulator/videobridge:in_process_audio_source",
        "//emulator/videobridge:videobridge_core",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:check",
    ],
)

cc_test(
    name = "qemu_audio_source_test",
    srcs = ["qemu_audio_source_test.cc"],
    copts = WEBRTC_COPTS,
    deps = [
        ":qemu_audio_source",
        ":test_qemu_audio_stub",
        "//emulator/libs/test:googletest_main",
        "//emulator/videobridge:in_process_audio_source",
        "@webrtc//api:media_stream_interface",
    ],
)

cc_test(
    name = "qemu_audio_capture_test",
    srcs = ["qemu_audio_capture_test.cc"],
    copts = WEBRTC_COPTS,
    deps = [
        ":qemu_audio_capture",
        ":test_qemu_audio_stub",
        "//emulator/libs/test:googletest_main",
        "//emulator/plugin/vminterface:vminterface-test",
        "//emulator/videobridge:in_process_audio_source",
        "@webrtc//api:media_stream_interface",
    ],
)

clang_tidy_test(
    name = "tidy",
    targets = [
        ":qemu_audio_capture",
        ":qemu_audio_capture_test",
        ":qemu_audio_source",
        ":qemu_audio_source_test",
    ],
    tidy_config_file = "//:clang_tidy_config",
)
