load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "synchronization",
    hdrs = [
        "include/goldfish/synchronization/mutex.h",
    ],
    includes = ["include"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "@abseil-cpp//absl/synchronization",
    ],
)
