load("@goldfish_build//rules:clang_tidy.bzl", "clang_tidy_test")
load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "status_macros",
    hdrs = ["include/android/status/status_macros.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
    ],
)

cc_library(
    name = "status_matcher_macros",
    testonly = True,
    hdrs = ["include/android/status/status_matcher_macros.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":status_macros",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:status_matchers",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
    ],
)

clang_tidy_test(
    name = "tidy",
    targets = [
        ":status_macros",
        ":status_matcher_macros",
    ],
    tidy_config_file = "//:clang_tidy_config",
)
