load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "ext4_utils",
    srcs = [
        "allocate.c",
        "contents.c",
        "crc16.c",
        "ext4_sb.c",
        "ext4_utils.c",
        "extent.c",
        "fs_config.c",
        "indirect.c",
        "make_ext4fs.c",
        "sha1.c",
        "src/allocate.h",
        "src/contents.h",
        "src/ext4.h",
        "src/ext4_extents.h",
        "src/ext4_kernel_headers.h",
        "src/ext4_sb.h",
        "src/ext4_utils.h",
        "src/ext4fixup.h",
        "src/extent.h",
        "src/indirect.h",
        "src/jbd2.h",
        "src/private/android_filesystem_capability.h",
        "src/private/android_filesystem_config.h",
        "src/private/fs_config.h",
        "src/sha1.h",
        "src/wipe.h",
        "src/xattr.h",
        "uuid.c",
        "uuid.h",
        "wipe.c",
    ],
    hdrs = [
        "include/make_ext4fs.h",
    ],
    includes = [
        "include",
        "src",
    ],
    linkopts = select({
        "@platforms//os:windows": [
            "-DEFAULTLIB:Rpcrt4.lib",
            "-DEFAULTLIB:Ws2_32.lib",
        ],
        "//conditions:default": [],
    }),
    visibility = ["//visibility:public"],
    deps = [
        "//android/system",
        "//third_party/sparse",
    ] + select({
        "@platforms//os:windows": ["@aemu//windows:compat"],
        "//conditions:default": [],
    }),
)
