load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "clock",
    srcs = [
        "src/abseil_clock.cpp",
        "src/clock.cpp",
    ],
    hdrs = [
        "include/android/base/system/abseil_clock.h",
        "include/android/base/system/clock.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "@abseil-cpp//absl/time",
        "@aemu//base:aemu-base",
    ],
)

cc_library(
    name = "system",
    srcs = [
        "src/android/base/Version.cpp",
        "src/android/base/bazel/bazel_info.cpp",
        "src/android/base/system/File.cpp",
        "src/android/base/system/System.cpp",
        "src/android/base/system/file_io.cpp",
        "src/android/base/system/storage_capacity.cpp",
    ] + select({
        "@platforms//os:windows": [
            "win/android/base/system/Win32UnicodeString.cpp",
            "win/android/base/system/Win32Utils.cpp",
        ],
        "//conditions:default": [],
    }),
    hdrs = [
        "include/android/base/bazel/bazel_info.h",
        "include/android/base/file/file_io.h",
        "include/android/base/system/CStrWrapper.h",
        "include/android/base/system/File.h",
        "include/android/base/system/System.h",
        "include/android/base/system/no_sigalarm.h",
        "include/android/base/system/storage_capacity.h",
        "include/android/utils/compiler.h",
    ] + select({
        "@platforms//os:windows": [
            "include/android/base/system/Win32UnicodeString.h",
            "include/android/base/system/Win32Utils.h",
        ],
        "//conditions:default": [],
    }),
    includes = ["include"],
    linkopts = select({
        "@platforms//os:windows": [
            "-DEFAULTLIB:Shell32.lib",
            "-DEFAULTLIB:User32.lib",
        ],
        "//conditions:default": [],
    }),
    visibility = ["//visibility:public"],
    deps = [
        ":clock",
        "@abseil-cpp//absl/algorithm:container",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings:str_format",
        "@aemu//base:aemu-base",
        "@bazel_tools//tools/cpp/runfiles",
    ] + select({
        "@platforms//os:linux": [
            "//android/process",
        ],
        "@platforms//os:windows": [
            "@glib//glib/dirent",
        ],
        "//conditions:default": [],
    }),
)

cc_library(
    name = "test-headers",
    testonly = True,
    srcs = ["test/android/base/system/test_file_util_bazel.cc"],
    hdrs = [
        "test-headers/android/base/system/TestClock.h",
        "test-headers/android/base/testing/MockUtils.h",
        "test-headers/android/base/testing/ResultMatchers.h",
        "test-headers/android/base/testing/TestEvent.h",
        "test-headers/android/base/testing/TestMemoryOutputStream.h",
        "test-headers/android/base/testing/TestSystem.h",
        "test-headers/android/base/testing/TestTempDir.h",
        "test-headers/android/base/testing/TestThread.h",
        "test-headers/android/base/testing/Utils.h",
        "test-headers/android/base/testing/test_file_util.h",
    ],
    includes = ["test-headers"],
    visibility = ["//visibility:public"],
    deps = [
        ":system",
        "//android/logging:backend",
        "@abseil-cpp//absl/log:absl_log",
        "@abseil-cpp//absl/strings",
        "@aemu//base:aemu-base",
        "@bazel_tools//tools/cpp/runfiles",
    ],
)

cc_test(
    name = "system-unittests",
    srcs = [
        "test/android/base/Version_unittest.cpp",
        "test/android/base/bazel/bazel_info_unittest.cpp",
        "test/android/base/system/File_test.cpp",
        "test/android/base/system/System_unittest.cpp",
        "test/android/base/system/storage_capacity_unittest.cpp",
    ],
    data = ["test/android/base/bazel/info.txt"],
    deps = [
        ":system",
        ":test-headers",
        "//android/system:googletest_main",
        "@abseil-cpp//absl/status:status_matchers",
    ],
)

cc_test(
    name = "win_compat_unittests",
    srcs = [
        "test/android/base/system/Win32UnicodeString_unittest.cpp",
        "test/android/base/system/Win32Utils_unittest.cpp",
    ],
    target_compatible_with = [
        "@platforms//os:windows",
    ],
    deps = [
        ":compat",
        "//android/system:googletest_main",
        "//android/system:test-headers",
    ],
)

cc_library(
    name = "googletest_main",
    testonly = True,
    srcs = ["test/android/base/gtest_main.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        ":system",
        "@abseil-cpp//absl/debugging:failure_signal_handler",
        "@abseil-cpp//absl/debugging:symbolize",
        "@abseil-cpp//absl/flags:flag",
        "@abseil-cpp//absl/flags:parse",
        "@abseil-cpp//absl/log:flags",
        "@abseil-cpp//absl/log:initialize",
        "@googletest//:gtest",
    ],
)

cc_binary(
    name = "clock_perf",
    testonly = True,
    srcs = ["test/bm_clock.cpp"],
    copts = [
        "-Wno-deprecated-declarations",
        "-Wno-unused-result",
    ],
    deps = [
        ":clock",
        ":system",
        "@google_benchmark//:benchmark",
    ],
)
