load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "system",
    srcs = [
        "src/android/base/Version.cpp",
        "src/android/base/bazel/bazel_info.cpp",
        "src/android/base/system/System.cpp",
        "src/android/base/system/file_io.cpp",
        "src/android/base/system/storage_capacity.cpp",
    ],
    hdrs = [
        "include/android/base/bazel/bazel_info.h",
        "include/android/base/file/file_io.h",
        "include/android/base/system/CStrWrapper.h",
        "include/android/base/system/System.h",
        "include/android/base/system/Win32UnicodeString.h",
        "include/android/base/system/Win32Utils.h",
        "include/android/base/system/storage_capacity.h",
        "include/android/utils/compiler.h",
    ],
    includes = ["include"],
    linkopts = select({
        "@platforms//os:windows": [
            "-DEFAULTLIB:Shell32.lib",
            "-DEFAULTLIB:User32.lib",
        ],
        "//conditions:default": [],
    }),
    visibility = ["//visibility:public"],
    deps = [
        "@aemu//base:aemu-base",
        "@bazel_tools//tools/cpp/runfiles",
        "@com_google_absl//absl/log",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings:str_format",
    ] + select({
        "@platforms//os:linux": [
            "//hardware/generic/goldfish/android/process",
        ],
        "@platforms//os:windows": [
            "@glib//:dirent",
        ],
        "//conditions:default": [],
    }),
)

cc_library(
    name = "test-headers",
    testonly = True,
    srcs = ["test/android/base/system/test_file_util_bazel.cc"],
    hdrs = [
        "test-headers/android/base/testing/MockUtils.h",
        "test-headers/android/base/testing/ResultMatchers.h",
        "test-headers/android/base/testing/TestEvent.h",
        "test-headers/android/base/testing/TestLooper.h",
        "test-headers/android/base/testing/TestMemoryOutputStream.h",
        "test-headers/android/base/testing/TestSystem.h",
        "test-headers/android/base/testing/TestTempDir.h",
        "test-headers/android/base/testing/TestThread.h",
        "test-headers/android/base/testing/Utils.h",
        "test-headers/android/base/testing/test_file_util.h",
    ],
    includes = ["test-headers"],
    visibility = ["//visibility:public"],
    deps = [
        ":system",
        "//hardware/generic/goldfish/android/logging:backend",
        "@aemu//base:aemu-base",
        "@bazel_tools//tools/cpp/runfiles",
        "@com_google_absl//absl/log:absl_log",
        "@com_google_absl//absl/strings",
    ],
)

cc_test(
    name = "system-unittests",
    srcs = [
        "test/android/base/Version_unittest.cpp",
        "test/android/base/bazel/bazel_info_unittest.cpp",
        "test/android/base/system/System_unittest.cpp",
        "test/android/base/system/storage_capacity_unittest.cpp",
    ] + select({
        "@platforms//os:windows": [
            "test/android/base/system/Win32UnicodeString_unittest.cpp",
        ],
        "//conditions:default": [],
    }),
    data = ["test/android/base/bazel/info.txt"],
    deps = [
        ":system",
        ":test-headers",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_library(
    name = "googletest_main",
    testonly = True,
    srcs = ["test/android/base/gtest_main.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        ":system",
        "@com_google_absl//absl/log:initialize",
        "@com_google_googletest//:gtest",
    ],
)
