load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")
load("@rules_python//python:defs.bzl", "py_binary")

cc_library(
    name = "tool_lib",
    srcs = [
        "annotation_extractor.cc",
        "crash_report_manager.cc",
        "formatter.cc",
        "minidump_processor.cc",
    ],
    hdrs = [
        "annotation_extractor.h",
        "crash_report_manager.h",
        "formatter.h",
        "minidump_processor.h",
    ],
    deps = [
        "//android/system",
        "//emulator/crashreport:crash_system",
        "//emulator/crashreport:crash_uploader",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/memory",
        "@abseil-cpp//absl/time",
        "@breakpad//src/processor",
        "@crashpad//client",
        "@crashpad//snapshot",
        "@nlohmann_json//:singleheader-json",
    ],
)

cc_binary(
    name = "crashreport",
    srcs = ["main.cc"],
    visibility = ["//visibility:public"],
    deps = [
        ":tool_lib",
        "@abseil-cpp//absl/flags:flag",
        "@abseil-cpp//absl/flags:parse",
        "@abseil-cpp//absl/flags:usage",
        "@abseil-cpp//absl/log:globals",
        "@abseil-cpp//absl/log:initialize",
        "@crashpad//client",
    ],
)

py_binary(
    name = "bazel_crashreport",
    srcs = ["bazel_crashreport.py"],
    data = [
        ":crashreport",
        "//emulator:package_goldfish_symbols_extract",
    ],
    deps = [
        "//emulator/tools:symbol_zipper",
        "@bazel_tools//tools/python/runfiles",
    ],
)
