load("@goldfish_build//rules:clang_tidy.bzl", "clang_tidy_test")
load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "base",
    srcs = [
        "display.cc",
    ],
    hdrs = [
        "include/goldfish/display/display.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//emulator/libs/async:async_api",
        "//emulator/libs/base",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/time",
    ],
)

cc_library(
    name = "display",
    srcs = [
        "multi_display.cc",
        "virtual_display.cc",
    ],
    hdrs = [
        "include/goldfish/display/virtual_display.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":primary_display",
        "//emulator/libs/async:async_api",
        "//emulator/libs/base",
        "//emulator/plugin/hal/multidisplay",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/time",
    ],
)

cc_library(
    name = "primary_display",
    srcs = [
        "imaging.cc",
        "input_handler.cc",
        "null_display.h",
        "pixman_display.cc",
        "pixman_frame_manager.cc",
        "qemu_display.cc",
        "qemu_display.h",
        "virtio_bridge.c",
        "virtio_bridge.h",
        "write_png.cc",
    ],
    hdrs = [
        "include/goldfish/display/QemuMultidisplay/multi_display.h",
        "include/goldfish/display/imaging.h",
        "include/goldfish/display/input_handler.h",
        "include/goldfish/display/multi_display_callbacks.h",
        "include/goldfish/display/pixman_display.h",
        "include/goldfish/display/pixman_frame_manager.h",
        "include/goldfish/display/pixman_image_ptr.h",
        "include/goldfish/display/write_png.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":base",
        "//emulator/libs/archive",
        "//emulator/libs/base",
        "//emulator/libs/fps_calculator",
        "//emulator/libs/logging:absl_c_bridge",
        "//emulator/libs/physics",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/time",
        "@libpng//:png",
        "@pixman//:pixman-1",
        "@pixman//:pixman_simd",
        "@qemu//:qemu-headers-exported",
    ],
)

cc_library(
    name = "video_recorder",
    srcs = [
        "video_recorder.cc",
        "webm_encoder.cc",
    ],
    hdrs = [
        "include/goldfish/display/QemuMultidisplay/multi_display.h",
        "include/goldfish/display/multi_display_callbacks.h",
        "include/goldfish/display/video_recorder.h",
        "include/goldfish/display/webm_encoder.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":base",
        "//emulator/libs/base",
        "//emulator/libs/logging:absl_c_bridge",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/time",
        "@ffmpeg//libavcodec:avcodec",
        "@ffmpeg//libavformat:avformat",
        "@ffmpeg//libavutil:avutil",
        "@ffmpeg//libswscale:swscale",
    ],
)

cc_library(
    name = "test-display",
    testonly = True,
    srcs = [
        "fake_multi_display.cc",
        "fake_pixman_display.cc",
        "pixman_image_generator.cc",
        "qemu_stubs.c",
    ],
    hdrs = [
        "include/goldfish/display/test/fake_multi_display.h",
        "include/goldfish/display/test/fake_pixman_display.h",
        "include/goldfish/display/test/image_generation_strategy.h",
        "include/goldfish/display/test/mock_display.h",
        "include/goldfish/display/test/pixman_image_generator.h",
    ],
    includes = ["test/include"],
    visibility = ["//visibility:public"],
    deps = [
        ":primary_display",
    ],
)

cc_test(
    name = "display_unittests",
    srcs = [
        "display_test.cc",
        "fake_multi_display_test.cc",
        "fake_pixman_display_test.cc",
        "image_generation_strategy_test.cc",
        "imaging_test.cc",
        "pixman_display_concurrency_test.cc",
        "pixman_frame_manager_test.cc",
        "pixman_image_generator_test.cc",
        "qemu_display_test.cc",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":test-display",
        "//emulator/libs/async:async_testing",
        "//emulator/libs/async:libuv_event_loop",
        "//emulator/libs/async:threaded_event_loop",
        "//emulator/libs/test:googletest_main",
    ],
)

clang_tidy_test(
    name = "tidy",
    targets = [
        ":primary_display",
        ":video_recorder",
        ":base",
        ":display",
        ":display_unittests",
    ],
    tidy_config_file = "//:clang_tidy_config",
)
