load("@goldfish_build//rules:clang_tidy.bzl", "clang_tidy_test")
load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "interceptors",
    srcs = [
        "breadcrumb_interceptor.cc",
        "idle_interceptor.cc",
        "logging_interceptor.cc",
    ],
    hdrs = [
        "include/android/control/interceptor/breadcrumb_interceptor.h",
        "include/android/control/interceptor/idle_interceptor.h",
        "include/google/protobuf/android/control/interceptor/logging_interceptor.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//android/async:async_api",
        "//android/process",
        "//android/system:clock",
        "//emulator/crashreport:breadcrumb",
        "@abseil-cpp//absl/time",
        "@aemu//protos/services/diagnostic:grpc_diagnostic_cc_proto",
        "@goldfish//emulator/crashreport:crash_reporter",
        "@goldfish//emulator/libs/proto_data_store",
        "@grpc//:grpc++",
        "@zlib",
    ],
)

cc_test(
    name = "interceptors_test",
    srcs =
        select({
            "@platforms//os:windows": [],
            "//conditions:default": [
                "breadcrumb_interceptor_test.cc",
                "logging_interceptor_test.cc",
            ],
        }),
    visibility = ["//visibility:public"],
    deps = [
        ":interceptors",
        "//android/async:async_testing",
        "//android/system:googletest_main",
        "//android/system:test-headers",
        "@aemu//protos/services/diagnostic:grpc_diagnostic_cc_proto",
        "@aemu//protos/services/emulator-controller:emulator_controller_cc_proto",
        "@googletest//:gtest",
    ],
)

clang_tidy_test(
    name = "tidy",
    targets = [
        "interceptors",
    ],
    tidy_config_file = "//:clang_tidy_config",
)
