load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "interceptors",
    srcs = [
        "src/android/emulation/control/interceptor/idle_interceptor.cpp",
        "src/android/emulation/control/interceptor/logging_interceptor.cpp",
    ],
    hdrs = [
        "include/android/emulation/control/interceptor/breadcrumb_interceptor.h",
        "include/android/emulation/control/interceptor/idle_interceptor.h",
        "include/android/emulation/control/interceptor/logging_interceptor.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//android/async:async_api",
        "//android/system:clock",
        "@aemu//base:aemu-base",
        "@grpc//:grpc++",
    ],
)

cc_test(
    name = "interceptors_test",
    srcs =
        select({
            "@platforms//os:windows": [],
            "//conditions:default": [
                "test/android/emulation/control/interceptor/logging_interceptor_unittest.cpp",
            ],
        }),
    deps = [
        ":interceptors",
        "//android/async:async_testing",
        "//android/system:googletest_main",
        "//android/system:test-headers",
        "//emulator/grpc/services/emulator_controller:emulator_controller_cc_proto",
        "@googletest//:gtest",
    ],
)
