load("@rules_cc//cc:defs.bzl", "cc_binary")

[
    cc_binary(
        name = "goldfish_" + arch,
        srcs = ["plugin.cc"],
        dynamic_deps = [
            "@glib//glib:glib_shared",
            "@glib//gmodule:gmodule_shared",
        ],
        linkopts = select({
            "@platforms//os:macos": ["-undefined dynamic_lookup"],
            "//conditions:default": [],
        }),
        linkshared = True,
        target_compatible_with = select({
            # We only support x86 on Windows currently.
            "@platforms//os:windows": [] if arch in [
                "x86_64",
                "aarch64",
            ] else ["@platforms//:incompatible"],
            "//conditions:default": [],
        }),
        visibility = ["//visibility:public"],
        win_def_file = select({
            "@platforms//os:windows": "goldfish_" + arch + ".def",
            "//conditions:default": None,
        }),
        deps = [
            "//emulator/crashreport:crash_reporter",
            "//emulator/crashreport:debug",
            "//emulator/libs/logging:color_log_sink",
            "//emulator/plugin/adb-vsock",
            "//emulator/plugin/avd:impl",
            "//emulator/plugin/battery",
            "//emulator/plugin/grpc",
            "//emulator/plugin/netsim:netsim-chardev",
            "//emulator/plugin/netsim:netsim-netdev",
            "//emulator/plugin/netsim:netsim_connection",
            "//emulator/plugin/virtio-input-android",
            "//emulator/plugin/virtio-wifi",
            "//emulator/plugin/vminterface:vm_ops",
            "//emulator/tools:aemu_version",
            "@abseil-cpp//absl/debugging:failure_signal_handler",
            "@abseil-cpp//absl/debugging:symbolize",
            "@abseil-cpp//absl/log",
            "@abseil-cpp//absl/log:structured",
            "@qemu//:aemu_func_defs",
            "@qemu//:qemu-headers-exported",
            "//emulator/plugin/vsock_goldfish:vsock_impl_" + arch,
            "@glib//glib:glib_import",
            "@glib//gmodule:gmodule_import",
        ] + select({
            "@platforms//os:windows": [
                "@qemu//:qemu-system-" + arch + ".if",
                "//emulator/crashreport:breadcrumb",
            ],
            "//conditions:default": [
                "//emulator/crashreport:breadcrumb",
            ],
        }) + [
            # crashreport dep must go after the windows compat dep.
            # buildifier: leave-alone
            "//emulator/crashreport:crash_system",
        ],
    )
    for arch in [
        "riscv64",
        "aarch64",
        "x86_64",
    ]
]
