load("@rules_python//python:defs.bzl", "py_binary", "py_library")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "amc_lib",
    srcs = glob(["src/aemu/**/*.py"]),
    imports = ["src"],
)

py_binary(
    name = "amc",
    srcs = ["src/amc.py"],
    main = "src/amc.py",
    deps = [":amc_lib"],
)
