load("@goldfish_build//rules:clang_tidy.bzl", "clang_tidy_test")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "UniqueIdAllocator",
    srcs = [
        "unique_id_allocator.cc",
    ],
    hdrs = [
        "include/goldfish/unique_id_allocator.h",
    ],
    includes = ["include"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//emulator/libs/archive",
        "//emulator/libs/archive:collections",
        "@abseil-cpp//absl/log:check",
    ],
)

cc_test(
    name = "UniqueIdAllocator_unittests",
    size = "small",
    srcs = [
        "unique_id_allocator_tests.cc",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":UniqueIdAllocator",
        "//emulator/libs/archive:DequeArchive",
        "//emulator/libs/test:googletest_main",
        "@abseil-cpp//absl/status:status_matchers",
    ],
)

clang_tidy_test(
    name = "tidy",
    targets = [
        ":UniqueIdAllocator",
        ":UniqueIdAllocator_unittests",
    ],
    tidy_config_file = "//:clang_tidy_config",
)
