load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "UniqueIdAllocator",
    srcs = [
        "UniqueIdAllocator.cpp",
    ],
    hdrs = [
        "include/goldfish/UniqueIdAllocator.h",
    ],
    includes = ["include"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//emulator/libs/archive",
    ],
)

cc_test(
    name = "UniqueIdAllocator_unittests",
    size = "small",
    srcs = [
        "UniqueIdAllocator_unittests.cpp",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":UniqueIdAllocator",
        "//android/system:googletest_main",
        "//emulator/libs/archive:DequeArchive",
    ],
)
