load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "UniqueIdAllocator",
    srcs = [
        "unique_id_allocator.cc",
    ],
    hdrs = [
        "include/goldfish/unique_id_allocator.h",
    ],
    includes = ["include"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//emulator/libs/archive",
    ],
)

cc_test(
    name = "UniqueIdAllocator_unittests",
    size = "small",
    srcs = [
        "unique_id_allocator_tests.cc",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":UniqueIdAllocator",
        "//emulator/libs/archive:DequeArchive",
        "//emulator/libs/test:googletest_main",
    ],
)
