load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

package(default_visibility = ["//emulator/grpc:__subpackages__"])

cc_library(
    name = "emulator-service",
    srcs = [
        "src/android/emulation/control/ClipboardService.cpp",
        "src/android/emulation/control/ClipboardService.h",
        "src/android/emulation/control/DisplayService.cpp",
        "src/android/emulation/control/DisplayService.h",
        "src/android/emulation/control/EmulatorService.cpp",
        "src/android/emulation/control/GpsService.cpp",
        "src/android/emulation/control/GpsService.h",
        "src/android/emulation/control/NotificationStream.cpp",
        "src/android/emulation/control/NotificationStream.h",
        "src/android/emulation/control/SensorService.cpp",
        "src/android/emulation/control/SensorService.h",
        "src/android/emulation/control/StatusService.cpp",
        "src/android/emulation/control/StatusService.h",
        "src/android/emulation/control/VmService.cpp",
        "src/android/emulation/control/VmService.h",
    ],
    hdrs = [
        "include/android/emulation/control/EmulatorService.h",
        "include/android/emulation/control/display/DisplayChangeListener.h",
    ],
    includes = [
        "include",
        "src",
    ],
    deps = [
        "//android/async:async_api",
        "//emulator/config:hardware_config",
        "//emulator/grpc/absl:translate",
        "//emulator/grpc/async",
        "//emulator/grpc/event-stream",
        "//emulator/grpc/services/emulator_controller:emulator_controller_cc_grpc",
        "//emulator/grpc/services/emulator_controller/input",
        "//emulator/grpc/services/emulator_controller/keyboard",
        "//emulator/hal/clipboard:headers",
        "//emulator/hal/connector:connector_registry_hdrs",
        "//emulator/hal/display",
        "//emulator/hal/gps",
        "//emulator/hal/guest-status:headers",
        "//emulator/hal/sensors",
        "//emulator/libs/gps",
        "//emulator/plugin/vminterface",
        "@abseil-cpp//absl/container:flat_hash_map",
        "@aemu//base:aemu-base",
    ],
)

cc_test(
    name = "emulator-service_unittests",
    srcs = [
        "include/android/emulation/control/EmulatorService.h",
        "src/android/emulation/control/DisplayService.h",
        "src/android/emulation/control/NotificationStream.h",
        "src/android/emulation/control/VmService.h",
        "test/DisplayServiceTest.cpp",
        "test/GrpcServiceTest.h",
        "test/NotificationStreamTest.cpp",
        "test/QemuStubs.c",
        "test/VmServiceTest.cpp",
    ],
    deps = [
        ":emulator-service",
        "//android/async:libuv_event_loop",
        "//android/async:threaded_event_loop",
        "//android/system:googletest_main",
        "//emulator/config:avd-test",
        "//emulator/hal/connector:test-helpers",
        "//emulator/hal/display:test-display",
        "//emulator/hal/plug:fake_vsock",
        "//emulator/hal/sensors",
        "//emulator/plugin/vminterface:test_vminterface",
        "//emulator/plugin/vminterface:vminterface-test",
        "@aemu//base:aemu-base",
    ],
)
