load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "emulator-service",
    srcs = [
        "battery_service.cc",
        "battery_service.h",
        "clipboard_service.cc",
        "clipboard_service.h",
        "display_service.cc",
        "display_service.h",
        "emulator_service.cc",
        "gps_service.cc",
        "gps_service.h",
        "notification_stream_writer.h",
        "sensor_service.cc",
        "sensor_service.h",
        "sensor_service_incubating.cc",
        "status_service.cc",
        "status_service.h",
        "vm_service.cc",
        "vm_service.h",
    ],
    hdrs = [
        "include/android/emulation/control/display_change_listener.h",
        "include/android/emulation/control/emulator_service.h",
        "include/android/emulation/control/incubating/sensor_service_incubating.h",
    ],
    includes = [
        "include",
        "src",
    ],
    deps = [
        "//android/async:async_api",
        "//emulator/config:hardware_config",
        "//emulator/grpc/absl:translate",
        "//emulator/grpc/async",
        "//emulator/grpc/event-stream",
        "//emulator/grpc/services/emulator_controller:emulator_controller_cc_grpc",
        "//emulator/grpc/services/emulator_controller/input",
        "//emulator/grpc/services/emulator_controller/keyboard",
        "//emulator/libs/fps_calculator",
        "//emulator/libs/shared_memory",
        "//emulator/plugin/avd:info",
        "//emulator/plugin/vminterface",
        "@abseil-cpp//absl/container:flat_hash_map",
        "@aemu//base:aemu-base",
        "@aemu//protos/services/incubating/sensor:sensor_service_cc_grpc",
    ],
)

cc_test(
    name = "emulator-service_unittests",
    srcs = [
        "display_service_test.cc",
        "qemu_stubs.c",
        "sensor_service_incubating_test.cc",
        "sensor_service_test.cc",
        "test/GrpcServiceTest.h",
        "vm_service_test.cc",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":emulator-service",
        "//android/async:libuv_event_loop",
        "//android/async:threaded_event_loop",
        "//android/process",
        "//android/system:googletest_main",
        "//emulator/config:fake_hardware_config",
        "//emulator/grpc/services/emulator_controller/keyboard:test_qemu_input_stub",
        "//emulator/libs/display:test-display",
        "//emulator/plugin/vminterface:test_vminterface",
        "//emulator/plugin/vminterface:vminterface-test",
        "@aemu//base:aemu-base",
    ],
)
