load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "headers",
    hdrs = [
        "include/android/clipboard/ClipboardDevice.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//emulator/hal/connector:connector_registry",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:check",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
    ],
)

cc_library(
    name = "clipboard",
    srcs = [
        "src/clipboard/ClipboardDevice.cpp",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":headers",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/strings",
        "@aemu//base:event-support",
    ],
    alwayslink = True,
)

cc_test(
    name = "clipboard_unittests",
    srcs = [
        "test/clipboard/ClipboardDevice_unittest.cpp",
    ],
    includes = ["test"],
    deps = [
        ":clipboard",
        "//android/system:googletest_main",
        "//android/system:test-headers",
        "//emulator/config:avd-test",
        "//emulator/hal/connector:test-helpers",
        "//emulator/hal/plug:fake_vsock",
    ],
)

cc_library(
    name = "test_clipboard",
    hdrs = [
        "test/FakeClipboardDevice.h",
    ],
    includes = ["test"],
    visibility = ["//visibility:public"],
    deps = [
        ":headers",
    ],
)
