load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "headers",
    hdrs = [
        "include/android/clipboard/ClipboardDevice.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//hardware/generic/goldfish/emulator/devices:connector_registry_hdrs",
        "@com_google_absl//absl/log",
        "@com_google_absl//absl/log:check",
        "@com_google_absl//absl/strings",
        "@com_google_absl//absl/strings:str_format",
    ],
)

cc_library(
    name = "clipboard",
    srcs = [
        "src/clipboard/ClipboardDevice.cpp",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":headers",
        "//hardware/generic/goldfish/android/logging:absl-c-bridge",
        "//hardware/generic/goldfish/android/system",
        "//hardware/generic/goldfish/emulator/agents",
        "//hardware/generic/goldfish/emulator/config",
        "//hardware/generic/goldfish/emulator/devices:PingTopic",
        "//hardware/generic/goldfish/emulator/devices:cable",
        "//hardware/generic/goldfish/emulator/devices:qemud",
        "@aemu//base:aemu-base",
        "@aemu//base:event-support",
        "@com_google_absl//absl/log",
        "@com_google_absl//absl/log:check",
        "@com_google_absl//absl/strings",
        "@com_google_absl//absl/strings:str_format",
        "@com_google_absl//absl/synchronization",
    ],
    alwayslink = True,
)

cc_test(
    name = "clipboard_unittests",
    srcs = [
        "test/clipboard/ClipboardDevice_unittest.cpp",
    ],
    includes = ["test"],
    deps = [
        ":clipboard",
        "//hardware/generic/goldfish/android/system:googletest_main",
        "//hardware/generic/goldfish/android/system:test-headers",
        "//hardware/generic/goldfish/emulator/config:avd-test",
        "//hardware/generic/goldfish/emulator/devices:test-helpers",
        "@aemu//:aemu-host-common-test-headers",
        "@aemu//base:aemu-base",
        "@aemu//base:aemu-base-headers",
        "@com_google_protobuf//:protobuf",
    ],
)

cc_library(
    name = "test_clipboard",
    hdrs = [
        "test/FakeClipboardDevice.h",
    ],
    includes = ["test"],
    visibility = ["//visibility:public"],
    deps = [
        ":headers",
    ],
)
