load("@goldfish_build//rules:clang_tidy.bzl", "clang_tidy_test")
load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "generic_netlink_message",
    srcs = [
        "generic_netlink_message.cc",
        "io_vector.cc",
    ],
    hdrs = [
        "include/goldfish/network/generic_netlink_message.h",
        "include/goldfish/network/io_vector.h",
        "include/goldfish/network/iovec.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "@abseil-cpp//absl/log",
        "@qemu//:qemu-headers",
    ],
)

cc_library(
    name = "network",
    srcs = [
        "dns_resolver.cc",
        "endpoint.cc",
        "ip_address.cc",
        "ip_endpoint.cc",
        "un_endpoint.cc",
    ],
    hdrs = [
        "include/goldfish/network/dns_resolver.h",
        "include/goldfish/network/endpoint.h",
        "include/goldfish/network/ip_address.h",
        "include/goldfish/network/ip_endpoint.h",
        "include/goldfish/network/un_endpoint.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//emulator/libs/cpp",
        "//emulator/libs/eventing",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:check",
        "@abseil-cpp//absl/status:statusor",
        "@c-ares//:ares",
    ],
)

cc_test(
    name = "network_unittests",
    size = "small",
    srcs = [
        "dns_resolver_test.cc",
        "endpoint_test.cc",
        "ip_address_test.cc",
        "ip_endpoint_test.cc",
        "un_endpoint_test.cc",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":network",
        "//emulator/libs/status_macros:status_matcher_macros",
        "//emulator/libs/system:test-headers",
        "//emulator/libs/test:googletest_main",
        "@abseil-cpp//absl/status:status_matchers",
    ],
)

clang_tidy_test(
    name = "tidy",
    targets = [
        ":network",
    ],
    tidy_config_file = "//:clang_tidy_config",
)
