load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")

cc_library(
    name = "stream",
    hdrs = [
        "include/goldfish/blocking_stream_buf.h",
        "include/goldfish/synchronized_stream_buf.h",
    ],
    includes = ["include"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "@abseil-cpp//absl/synchronization",
    ],
)

cc_test(
    name = "stream_tests",
    size = "small",
    srcs = [
        "stream_tests.cc",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":stream",
        "//emulator/libs/test:googletest_main",
    ],
)

cc_binary(
    name = "stream_perf",
    srcs = [
        "stream_perf.cc",
    ],
    tags = ["benchmark"],
    deps = [
        ":stream",
        "@google_benchmark//:benchmark",
    ],
)
