load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "emulator_config",
    hdrs = ["emulator_config.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//emulator/launcher:avd",
        "//emulator/launcher:input_paths",
        "//emulator/launcher/cmdline",
        "//emulator/libs/metrics:configure_metrics_writer",
    ],
)

cc_library(
    name = "fake_emulator",
    testonly = True,
    hdrs = ["fake_emulator.h"],
    deps = [
        ":emulator_config",
        "//emulator/launcher:mock_avd",
        "//emulator/libs/system:bazel_info",
    ],
)

cc_library(
    name = "device",
    hdrs = ["device.h"],
    deps = [":emulator_config"],
)

cc_library(
    name = "audio_device",
    srcs = ["audio_device.cc"],
    hdrs = ["audio_device.h"],
    deps = [
        ":device",
        "//emulator/libs/base",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
    ],
)

cc_library(
    name = "adb_device",
    srcs = ["adb_device.cc"],
    hdrs = ["adb_device.h"],
    deps = [
        ":device",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/strings",
    ],
)

cc_test(
    name = "adb_device_test",
    srcs = ["adb_device_test.cc"],
    deps = [
        ":adb_device",
        ":device",
        ":fake_emulator",
        "//emulator/libs/status_macros:status_matcher_macros",
        "//emulator/libs/system:test-headers",
        "//emulator/libs/test:googletest_main",
        "@abseil-cpp//absl/status:status_matchers",
        "@abseil-cpp//absl/strings",
    ],
)

cc_library(
    name = "avd_info_device",
    srcs = ["avd_info_device.cc"],
    hdrs = ["avd_info_device.h"],
    deps = [
        ":device",
        ":snapshot_device",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/strings",
    ],
)

cc_test(
    name = "avd_info_device_test",
    srcs = ["avd_info_device_test.cc"],
    deps = [
        ":avd_info_device",
        ":device",
        ":fake_emulator",
        "//emulator/libs/status_macros:status_matcher_macros",
        "//emulator/libs/system:test-headers",
        "//emulator/libs/test:googletest_main",
        "@abseil-cpp//absl/status:status_matchers",
        "@abseil-cpp//absl/strings",
    ],
)

cc_library(
    name = "cpu_device",
    srcs = ["cpu_device.cc"],
    hdrs = ["cpu_device.h"],
    deps = [
        ":device",
        "//emulator/libs/cpu",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
    ],
)

cc_test(
    name = "cpu_device_test",
    srcs = ["cpu_device_test.cc"],
    deps = [
        ":cpu_device",
        ":device",
        ":fake_emulator",
        "//emulator/libs/status_macros:status_matcher_macros",
        "//emulator/libs/system:test-headers",
        "//emulator/libs/test:googletest_main",
        "@abseil-cpp//absl/status:status_matchers",
        "@abseil-cpp//absl/strings",
    ],
)

cc_library(
    name = "display_device",
    srcs = ["display_device.cc"],
    hdrs = ["display_device.h"],
    deps = [
        ":device",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/strings",
    ],
)

cc_test(
    name = "display_device_test",
    srcs = ["display_device_test.cc"],
    deps = [
        ":device",
        ":display_device",
        ":fake_emulator",
        "//emulator/libs/status_macros:status_matcher_macros",
        "//emulator/libs/system:test-headers",
        "//emulator/libs/test:googletest_main",
        "@abseil-cpp//absl/status:status_matchers",
        "@abseil-cpp//absl/strings",
    ],
)

cc_library(
    name = "gpu_device",
    srcs = ["gpu_device.cc"],
    hdrs = ["gpu_device.h"],
    deps = [
        ":device",
        "//emulator/libs/parsing:resizable_display_config",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
    ],
)

cc_library(
    name = "grpc_device",
    srcs = ["grpc_device.cc"],
    hdrs = ["grpc_device.h"],
    deps = [
        ":device",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
    ],
)

cc_test(
    name = "grpc_device_test",
    srcs = ["grpc_device_test.cc"],
    data = ["//emulator/launcher:unsecure-emulator-access"],
    deps = [
        ":device",
        ":fake_emulator",
        ":grpc_device",
        "//emulator/libs/status_macros:status_matcher_macros",
        "//emulator/libs/system:test-headers",
        "//emulator/libs/test:googletest_main",
        "@abseil-cpp//absl/status:status_matchers",
        "@abseil-cpp//absl/strings",
    ],
)

cc_library(
    name = "bootconfig",
    srcs = ["bootconfig.cc"],
    hdrs = ["bootconfig.h"],
    deps = ["//emulator/libs/system"],
)

cc_test(
    name = "bootconfig_test",
    srcs = ["bootconfig_test.cc"],
    deps = [
        ":bootconfig",
        "//emulator/libs/system:test-headers",
        "//emulator/libs/test:googletest_main",
    ],
)

cc_library(
    name = "initrd_device",
    srcs = ["initrd_device.cc"],
    hdrs = ["initrd_device.h"],
    deps = [
        ":bootconfig",
        ":device",
        ":disk_drive",
        "//emulator/libs/adbkey",
        "//emulator/libs/parsing:resizable_display_config",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
    ],
)

cc_test(
    name = "initrd_device_test",
    srcs = ["initrd_device_test.cc"],
    deps = [
        ":device",
        ":fake_emulator",
        ":initrd_device",
        "//emulator/libs/status_macros:status_matcher_macros",
        "//emulator/libs/system:test-headers",
        "//emulator/libs/test:googletest_main",
        "@abseil-cpp//absl/status:status_matchers",
        "@abseil-cpp//absl/strings",
    ],
)

cc_library(
    name = "kernel_device",
    srcs = ["kernel_device.cc"],
    hdrs = ["kernel_device.h"],
    deps = [
        ":device",
        "@abseil-cpp//absl/container:btree",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
    ],
)

cc_test(
    name = "kernel_device_test",
    srcs = ["kernel_device_test.cc"],
    deps = [
        ":device",
        ":fake_emulator",
        ":kernel_device",
        "//emulator/libs/status_macros:status_matcher_macros",
        "//emulator/libs/system:test-headers",
        "//emulator/libs/test:googletest_main",
        "@abseil-cpp//absl/status:status_matchers",
        "@abseil-cpp//absl/strings",
    ],
)

cc_library(
    name = "machine",
    srcs = ["machine.cc"],
    hdrs = ["machine.h"],
    deps = [
        ":device",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
    ],
)

cc_test(
    name = "machine_test",
    srcs = ["machine_test.cc"],
    deps = [
        ":device",
        ":fake_emulator",
        ":machine",
        "//emulator/libs/status_macros:status_matcher_macros",
        "//emulator/libs/system:test-headers",
        "//emulator/libs/test:googletest_main",
        "@abseil-cpp//absl/status:status_matchers",
        "@abseil-cpp//absl/strings",
    ],
)

cc_library(
    name = "memory_device",
    srcs = ["memory_device.cc"],
    hdrs = ["memory_device.h"],
    deps = [
        ":device",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
    ],
)

cc_test(
    name = "memory_device_test",
    srcs = ["memory_device_test.cc"],
    deps = [
        ":device",
        ":fake_emulator",
        ":memory_device",
        "//emulator/libs/status_macros:status_matcher_macros",
        "//emulator/libs/system:test-headers",
        "//emulator/libs/test:googletest_main",
        "@abseil-cpp//absl/status:status_matchers",
        "@abseil-cpp//absl/strings",
    ],
)

cc_library(
    name = "network_device",
    srcs = ["network_device.cc"],
    hdrs = ["network_device.h"],
    deps = [
        ":device",
        "@abseil-cpp//absl/random",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
    ],
)

cc_test(
    name = "network_device_test",
    srcs = ["network_device_test.cc"],
    deps = [
        ":device",
        ":fake_emulator",
        ":network_device",
        "//emulator/libs/status_macros:status_matcher_macros",
        "//emulator/libs/system:test-headers",
        "//emulator/libs/test:googletest_main",
        "@abseil-cpp//absl/status:status_matchers",
        "@abseil-cpp//absl/strings",
    ],
)

cc_library(
    name = "parameter_list",
    srcs = ["parameter_list.cc"],
    hdrs = ["parameter_list.h"],
    deps = [
        ":device",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
    ],
)

cc_library(
    name = "hugepage_device",
    srcs = ["hugepage_device.cc"],
    hdrs = ["hugepage_device.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":device",
        ":emulator_config",
        "//emulator/launcher:avd",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/strings",
    ],
)

cc_library(
    name = "wifi_device",
    srcs = ["wifi_device.cc"],
    hdrs = ["wifi_device.h"],
    deps = [
        ":device",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
    ],
)

cc_library(
    name = "user_data_drive",
    srcs = ["user_data_drive.cc"],
    hdrs = ["user_data_drive.h"],
    deps = [
        ":device",
        "//emulator/libs/ext4",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
    ],
)

cc_library(
    name = "disk_drive",
    srcs = ["disk_drive.cc"],
    hdrs = ["disk_drive.h"],
    deps = [
        ":device",
        "//emulator/libs/ext4",
        "//emulator/libs/process",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
    ],
)

cc_test(
    name = "disk_drive_test",
    srcs = ["disk_drive_test.cc"],
    deps = [
        ":disk_drive",
        ":fake_emulator",
        "//emulator/libs/status_macros:status_matcher_macros",
        "//emulator/libs/system:test-headers",
        "//emulator/libs/test:googletest_main",
        "@abseil-cpp//absl/status:status_matchers",
        "@abseil-cpp//absl/strings",
    ],
)

cc_library(
    name = "configure_drives",
    srcs = ["configure_drives.cc"],
    hdrs = ["configure_drives.h"],
    deps = [
        ":device",
        ":disk_drive",
        ":user_data_drive",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
    ],
)

cc_test(
    name = "configure_drives_test",
    srcs = ["configure_drives_test.cc"],
    deps = [
        ":configure_drives",
        ":fake_emulator",
        "//emulator/launcher:mock_avd",
        "//emulator/libs/system:test-headers",
        "//emulator/libs/test:googletest_main",
        "@abseil-cpp//absl/status:status_matchers",
        "@abseil-cpp//absl/strings",
    ],
)

cc_library(
    name = "snapshot_device",
    srcs = ["snapshot_device.cc"],
    hdrs = ["snapshot_device.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":device",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/strings",
    ],
)

cc_library(
    name = "launch_qemu",
    srcs = ["launch_qemu.cc"],
    hdrs = ["launch_qemu.h"],
    # Qemu roms needed for unittests - Emulator check that it is available.
    data = ["@qemu//:qemu-roms"],
    visibility = ["//visibility:public"],
    deps = [
        ":adb_device",
        ":audio_device",
        ":avd_info_device",
        ":configure_drives",
        ":cpu_device",
        ":display_device",
        ":emulator_config",
        ":gpu_device",
        ":grpc_device",
        ":hugepage_device",
        ":initrd_device",
        ":kernel_device",
        ":machine",
        ":memory_device",
        ":network_device",
        ":parameter_list",
        ":snapshot_device",
        ":wifi_device",
        "//emulator/launcher:avd",
        "//emulator/launcher:input_paths",
        "//emulator/launcher/cmdline",
        "//emulator/libs/async:launch_config",
        "//emulator/libs/system",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
    ],
)
