load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")

cc_library(
    name = "headers",
    hdrs = [
        "include/android/goldfish/vm/VmInterface.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//hardware/generic/goldfish/emulator/devices:connector_registry_hdrs",
    ],
)

cc_library(
    name = "vm",
    srcs = [
        "src/vm/QemuVmOperations.cpp",
        "src/vm/VmLock.cpp",
        "src/vm/qemu-machine-info.h",
    ],
    includes = ["src"],
    visibility = ["//visibility:public"],
    deps = [
        ":headers",
        "//third_party/qemu:qemu-headers",
        "@com_google_absl//absl/container:flat_hash_map",
        "@com_google_absl//absl/log",
        "@com_google_absl//absl/synchronization",
    ],
)

cc_library(
    name = "vm_with_cpu_stub",
    srcs = [
        "src/vm/fake-machine-info.c",
        "src/vm/qemu-machine-info.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":headers",
        ":vm",
        "//third_party/qemu:qemu-headers",
    ],
)

# TODO(jansene): We should likely merge our goldfish cpu based drivers so we do not duplicate too much code.
[cc_library(
    name = "vm-goldfish-cpu-info-" + arch,
    srcs = [
        "src/vm/qemu-machine-info.c",
        "src/vm/qemu-machine-info.h",
    ],
    defines = [
        "NEED_CPU_H",
        'CONFIG_TARGET=\\"' + arch + '-softmmu-config-target.h\\"',
        'CONFIG_DEVICES=\\"' + arch + '-softmmu-config-devices.h\\"',
    ],
    includes = ["src"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        ":headers",
        "//third_party/qemu:qemu-headers",
        "@com_google_absl//absl/log",
        "@com_google_absl//absl/synchronization",
    ],
    alwayslink = True,
) for arch in [
    "riscv64",
    "aarch64",
    "x86_64",
]]

[cc_binary(
    name = "vm-goldfish-" + arch,
    linkshared = True,
    visibility = [
        "//visibility:public",
    ],
    deps = [":vm-goldfish-cpu-info-" + arch] +
           select({
               "@platforms//os:windows": [
                   "//third_party/qemu:qemu-system-" + arch + ".if",
               ],
               "//conditions:default": [],
           }),
) for arch in [
    "riscv64",
    "aarch64",
    "x86_64",
]]

cc_library(
    name = "vminterface-test",
    srcs = [
        "test/TestVmLock.cpp",
        "test/TestVmLock.h",
        "test/vm-mock.c",
        "test/vm-mock.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":vm",
        ":vm_with_cpu_stub",
    ],
)

cc_test(
    name = "vminterface_unittests",
    srcs = [
        "test/vm_unittest.cpp",
    ],
    includes = ["test"],
    linkopts = select({
        "@platforms//os:macos": ["-undefined error"],
        "//conditions:default": [],
    }),
    deps = [
        ":vminterface-test",
        "//hardware/generic/goldfish/android/system:googletest_main",
        "//hardware/generic/goldfish/android/system:test-headers",
        "@aemu//:aemu-host-common-test-headers",
        "@aemu//base:aemu-base-headers",
    ],
)
