load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "cpu",
    srcs = [
        "apple_cpu_accelerator.h",
        "cpu_accelerator.cc",
        "version.cc",
        "x86_cpuid.cc",
        "x86_cpuid.h",
    ] + select({
        "@platforms//os:windows": [
            "windows_installer.cc",
            "windows_installer.h",
        ],
        "//conditions:default": [],
    }),
    hdrs = [
        "include/android/cpu/cpu_accelerator.h",
        "include/android/cpu/version.h",
    ],
    copts =
        select({
            "@platforms//os:windows": ["-Wno-microsoft-goto"],
            "//conditions:default": [],
        }),
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//emulator/libs/base",
        "//emulator/libs/system",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
    ] + select({
        "@platforms//os:windows": [
            "//emulator/libs/windows:scoped_file_handle",
            "//emulator/libs/windows:scoped_reg_key",
            "//emulator/libs/windows:win32_utils",
        ],
        "//conditions:default": [],
    }),
)

cc_test(
    name = "cpu_unittests",
    srcs = [
        "version_test.cc",
        "x86_cpuid_test.cc",
    ],
    linkopts = select({
        "@platforms//os:macos": ["-undefined error"],
        "//conditions:default": [],
    }),
    visibility = ["//visibility:public"],
    deps = [
        ":cpu",
        "//emulator/libs/system:test-headers",
        "//emulator/libs/test:googletest_main",
    ],
)
