load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "x86_cpuid",
    srcs = ["x86_cpuid.cc"],
    hdrs = ["x86_cpuid.h"],
    deps = ["//emulator/libs/system"],
)

cc_test(
    name = "x86_cpuid_test",
    srcs = ["x86_cpuid_test.cc"],
    deps = [
        ":x86_cpuid",
        "//emulator/libs/test:googletest_main",
    ],
)

cc_library(
    name = "cpu_brand",
    srcs = ["cpu_brand.cc"],
    hdrs = ["include/android/cpu/cpu_brand.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [":x86_cpuid"],
)

cc_library(
    name = "cpu",
    srcs = [
        "apple_cpu_accelerator.h",
        "cpu_accelerator.cc",
        "version.cc",
        "x86_cpuid.cc",
        "x86_cpuid.h",
    ] + select({
        "@platforms//os:windows": [
            "windows_installer.cc",
            "windows_installer.h",
        ],
        "//conditions:default": [],
    }),
    hdrs = [
        "include/android/cpu/cpu_accelerator.h",
        "include/android/cpu/version.h",
    ],
    copts =
        select({
            "@platforms//os:windows": ["-Wno-microsoft-goto"],
            "//conditions:default": [],
        }),
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":x86_cpuid",
        "//emulator/libs/base",
        "//emulator/libs/system",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
    ] + select({
        "@platforms//os:windows": [
            "//emulator/libs/windows:scoped_file_handle",
            "//emulator/libs/windows:scoped_reg_key",
            "//emulator/libs/windows:win32_utils",
        ],
        "//conditions:default": [],
    }),
)

cc_test(
    name = "version_test",
    srcs = ["version_test.cc"],
    linkopts = select({
        "@platforms//os:macos": ["-undefined error"],
        "//conditions:default": [],
    }),
    deps = [
        ":cpu",
        "//emulator/libs/system:test-headers",
        "//emulator/libs/test:googletest_main",
    ],
)
