load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "services-stack",
    srcs = ["grpc_services.cc"],
    hdrs = ["include/goldfish/async/android/emulation/control/grpc_services.h"],
    includes = ["include"],
    visibility = ["//emulator/plugin/grpc:__subpackages__"],
    deps = [
        "//emulator/adb/secrets",
        "//emulator/libs/async:async_api",
        "//emulator/libs/grpc_security",
        "//emulator/libs/sockets",
        "//emulator/plugin/grpc/interceptors",
        "//emulator/plugin/grpc/services:emulator_controller",
        "@aemu//protos/client:grpc_endpoint_description_cc_proto",
    ],
)
