load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "services-stack",
    srcs = ["grpc_services.cc"],
    hdrs = ["include/goldfish/async/android/emulation/control/grpc_services.h"],
    includes = ["include"],
    visibility = ["//emulator/plugin/grpc:__subpackages__"],
    deps = [
        "//emulator/adb/secrets",
        "//emulator/grpc/client:grpc_endpoint_description_cc_proto",
        "//emulator/grpc/interceptors",
        "//emulator/grpc/security",
        "//emulator/grpc/services/emulator_controller/server:emulator-service",
        "@aemu//base:aemu-base",
    ],
)
