# It's an older code sir but it checks out
cc_library(
    name = "streams",
    srcs = ["src/aemu/base/streams/RingStreambuf.cpp"],
    defines = [
        "__STDC_LIMIT_MACROS=1",
        "__STDC_FORMAT_MACROS=1",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//hardware/google/aemu/base:aemu-base",
    ],
)
