load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "gralloc_details",
    hdrs = [
        "include/android/camera/GrallocDetails.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//hardware/generic/goldfish/emulator/libs/imaging",
    ],
    alwayslink = True,
)

cc_library(
    name = "image_provider_api",
    hdrs = [
        "include/android/camera/CameraImageProviderAPI.h",
        "include/android/camera/ImageProviderCppAdapter.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//hardware/generic/goldfish/emulator/libs/imaging",
    ],
    alwayslink = True,
)

cc_library(
    name = "camera",
    srcs = [
        "CameraDevice.cpp",
        "CameraDeviceBase.cpp",
        "CameraDeviceEnumerator.cpp",
        "CameraImageProviderInfoCpp.cpp",
        "CameraImageProviderRegistry.cpp",
        "CameraImageSource.cpp",
        "CameraProtocolBase.cpp",
        "QueryParser.cpp",
        "getGuestEmulatedCameraProperty.cpp",
        "include/android/camera/CameraDevice.h",
        "include/android/camera/CameraDeviceBase.h",
        "include/android/camera/CameraDeviceEnumerator.h",
        "include/android/camera/CameraImageProviderInfoCpp.h",
        "include/android/camera/CameraImageProviderRegistry.h",
        "include/android/camera/CameraImageSource.h",
        "include/android/camera/CameraProtocolBase.h",
        "include/android/camera/QueryParser.h",
        "include/android/camera/getGuestEmulatedCameraProperty.h",
        "registerDevice.cpp",
    ],
    hdrs = [
        "include/android/camera/registerDevice.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":gralloc_details",
        ":image_provider_api",
        "//hardware/generic/goldfish/emulator/config",
        "//hardware/generic/goldfish/emulator/hal/camera/image_providers/imagefile",
        "//hardware/generic/goldfish/emulator/hal/camera/image_providers/videofile",
        "//hardware/generic/goldfish/emulator/hal/camera/image_providers/virtualscene",
        "//hardware/generic/goldfish/emulator/hal/camera/image_providers/webcam",
        "//hardware/generic/goldfish/emulator/hal/connector:PingTopic",
        "//hardware/generic/goldfish/emulator/hal/connector:cable",
        "//hardware/generic/goldfish/emulator/hal/connector:connector_registry_hdrs",
        "//hardware/generic/goldfish/emulator/libs/parsing",
        "@abseil-cpp//absl/log",
    ],
    alwayslink = True,
)

cc_test(
    name = "camera_impl_unittests",
    srcs = [
        "test/CameraDeviceEnumerator_test.cpp",
        "test/CameraDevice_test.cpp",
        "test/CameraImageProviderRegistry_test.cpp",
        "test/CameraImageSource_test.cpp",
        "test/CameraProtocolBase_test.cpp",
        "test/QueryParser_test.cpp",
        "test/getGuestEmulatedCameraProperty_test.cpp",
    ],
    deps = [
        ":camera",
        "//hardware/generic/goldfish/android/system:googletest_main",
    ],
)

test_suite(
    name = "camera_unittests",
    tests = [
        ":camera_impl_unittests",
        "//hardware/generic/goldfish/emulator/hal/camera/image_providers:image_providers_unittests",
    ],
)

cc_library(
    name = "test_camera",
    hdrs = [
        "test/FakeCameraDevice.h",
    ],
    includes = ["test"],
    visibility = ["//visibility:public"],
    deps = [
        ":camera",
    ],
)
