load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "os",
    srcs = [
        "dynamic_library.cc",
    ],
    hdrs = [
        "include/goldfish/os/dynamic_library.h",
        "include/goldfish/os/temp_failure_retry.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//emulator/libs/base",
    ],
    alwayslink = True,
)

cc_test(
    name = "os_unittests",
    srcs = [
        "todo.cc",
    ],
    includes = ["test"],
    visibility = ["//visibility:public"],
    deps = [
        ":os",
        "//android/system:googletest_main",
    ],
)
