load("@rules_cc//cc:cc_test.bzl", "cc_test")
load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "info",
    hdrs = [
        "include/goldfish/avd/avd-info.h",
    ],
    includes = ["include"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//emulator/config:device_type",
        "//emulator/config:hardware_config",
    ],
)

cc_library(
    name = "gralloc_impl",
    srcs = [
        "GrallocImpl.cpp",
        "rutabaga_glue.c",
    ],
    hdrs = [
        "include/goldfish/avd/GrallocImpl.h",
        "include/goldfish/avd/rutabaga_glue.h",
    ],
    copts = ["-Wno-extern-c-compat"],
    includes = ["include"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//emulator/hal/camera:gralloc_details",
        "//emulator/libs/parsing",
        "@crosvm//:rutabaga_c_ffi",
        "@pixman//:pixman-1",
        "@qemu//:qemu-headers",
    ],
    alwayslink = True,
)

cc_library(
    name = "global-event-loop",
    srcs = [
        "global-event-loop.cpp",
    ],
    hdrs = ["include/goldfish/avd/global-event-loop.h"],
    includes = ["include"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//android/async:libuv_event_loop",
        "//android/async:threaded_event_loop",
    ],
)

cc_test(
    name = "global-event-loop-tests",
    size = "small",
    srcs = [
        "test/global-event-loop-test.cpp",
    ],
    deps = [
        ":global-event-loop",
        "//android/system:googletest_main",
    ],
)

cc_library(
    name = "vcpu_event_loop",
    srcs = ["QemuCpuWrapper.c"],
    hdrs = [
        "QemuCpuWrapper.h",
        "VCpuEventLoop.h",
    ],
    visibility = ["//visibility:public"],
    deps = ["@qemu//:qemu-headers"],
)

cc_library(
    name = "impl",
    srcs = [
        "avd-finalize.cpp",
        "avd-info.cpp",
    ],
    hdrs = [
        "include/goldfish/avd/avd-finalize.h",
        "include/goldfish/avd/avd-info-register_types.h",
        "include/goldfish/avd/avd-private.h",
    ],
    copts = ["-Wno-extern-c-compat"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":global-event-loop",
        ":gralloc_impl",
        ":info",
        ":vcpu_event_loop",
        "//android/async:async_api",
        "//android/async:libuv_event_loop",
        "//android/async:qemu_event_loop",
        "//emulator/adb/host",
        "//emulator/adb/logger",
        "//emulator/crashreport:crash_reporter",
        "//emulator/hal/bootproperties",
        "//emulator/hal/camera",
        "//emulator/hal/clipboard",
        "//emulator/hal/common:emulator_reset",
        "//emulator/hal/connector:connector_registry_impl",
        "//emulator/hal/fingerprint",
        "//emulator/hal/gps",
        "//emulator/hal/guest-status",
        "//emulator/hal/sensors",
        "//emulator/libs/display",
        "//emulator/plugin/system:qemu_clock",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:check",
        "@abseil-cpp//absl/log:globals",
        "@abseil-cpp//absl/log:initialize",
        "@abseil-cpp//absl/log:log_sink_registry",
        "@qemu//:qemu-headers",
    ],
    alwayslink = True,
)
