load("@rules_cc//cc:cc_test.bzl", "cc_test")
load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "info",
    hdrs = ["include/goldfish/avd_info/avd_info.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//emulator/libs/hardware_config",
        "//emulator/libs/hardware_config:device_type",
        "//emulator/libs/metrics:configure_metrics_writer",
        "//emulator/libs/sensors:physical_model",
        "//emulator/plugin/avd_universe",
    ],
)

cc_library(
    name = "info-fake",
    srcs = ["avd_info_fake.cc"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":info",
        "//emulator/plugin/hal/multidisplay",
    ],
)

cc_library(
    name = "gralloc_impl",
    srcs = [
        "gralloc_impl.cc",
        "rutabaga_glue.c",
    ],
    hdrs = [
        "include/goldfish/avd/rutabaga_glue.h",
        "include/goldfish/avd_info/gralloc_impl.h",
    ],
    copts = ["-Wno-extern-c-compat"],
    includes = ["include"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//emulator/libs/parsing",
        "//emulator/plugin/hal/camera:gralloc_details",
        "@pixman//:pixman-1",
        "@qemu//:qemu-headers-exported",
        "@rutabaga_gfx//:rutabaga_c_ffi",
    ],
    alwayslink = True,
)

cc_library(
    name = "global-event-loop",
    srcs = [
        "global_event_loop.cc",
    ],
    hdrs = ["include/goldfish/async/testing/global_event_loop.h"],
    includes = ["include"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//emulator/libs/async:libuv_event_loop",
        "//emulator/libs/async:threaded_event_loop",
    ],
)

cc_test(
    name = "global-event-loop-tests",
    size = "small",
    srcs = [
        "global_event_loop_test.cc",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":global-event-loop",
        "//emulator/libs/test:googletest_main",
    ],
)

cc_library(
    name = "vcpu_event_loop",
    srcs = ["qemu_cpu_wrapper.c"],
    hdrs = [
        "VCpuEventLoop.h",
        "qemu_cpu_wrapper.h",
    ],
    visibility = ["//visibility:public"],
    deps = ["@qemu//:qemu-headers-exported"],
)

cc_library(
    name = "impl",
    srcs = [
        "avd_extended_universe.cc",
        "avd_extended_universe.h",
        "avd_finalize.cc",
        "avd_info.cc",
    ],
    hdrs = [
        "include/goldfish/avd_finalize/avd_finalize.h",
        "include/goldfish/avd_info/avd_info_register_types.h",
        "include/goldfish/avd_info/avd_private.h",
    ],
    copts = ["-Wno-extern-c-compat"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":global-event-loop",
        ":gralloc_impl",
        ":info",
        ":vcpu_event_loop",
        "//emulator/crashreport:crash_reporter",
        "//emulator/libs/archive:QEMUFileArchive",
        "//emulator/libs/async:async_api",
        "//emulator/libs/async:libuv_event_loop",
        "//emulator/libs/async:qemu_event_loop",
        "//emulator/libs/host-common",
        "//emulator/libs/metrics",
        "//emulator/libs/metrics:perf_stat_reporter",
        "//emulator/plugin/battery",
        "//emulator/plugin/display",
        "//emulator/plugin/hal/bootproperties",
        "//emulator/plugin/hal/camera",
        "//emulator/plugin/hal/clipboard",
        "//emulator/plugin/hal/common:emulator_reset",
        "//emulator/plugin/hal/connector:connector_registry_impl",
        "//emulator/plugin/hal/fingerprint",
        "//emulator/plugin/hal/gps",
        "//emulator/plugin/hal/guest-status",
        "//emulator/plugin/hal/multidisplay",
        "//emulator/plugin/hal/sensors",
        "//emulator/plugin/hal/unix_pipe",
        "//emulator/plugin/system:qemu_clock",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:check",
        "@abseil-cpp//absl/log:globals",
        "@abseil-cpp//absl/log:initialize",
        "@abseil-cpp//absl/log:log_sink_registry",
        "@qemu//:qemu-headers-exported",
    ],
    alwayslink = True,
)
