load("@goldfish_build//rules:clang_tidy.bzl", "clang_tidy_test")
load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "gps",
    srcs = [
        "gps_device.cc",
    ],
    hdrs = [
        "include/goldfish/devices/gps/gps_device.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//emulator/hal/connector:connector_registry",
        "//emulator/hal/connector:qemud",
        "//emulator/libs/avd_universe:location",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/strings:str_format",
    ],
    alwayslink = True,
)

cc_test(
    name = "gps_unittests",
    srcs = [
        "gps_device_test.cc",
    ],
    includes = ["test"],
    linkopts = select({
        "@platforms//os:macos": ["-undefined error"],
        "//conditions:default": [],
    }),
    visibility = ["//visibility:public"],
    deps = [
        ":gps",
        "//android/system:googletest_main",
        "//android/system:test-headers",
        "//emulator/hal/connector:test-helpers",
        "//emulator/hal/plug:fake_vsock",
    ],
)

clang_tidy_test(
    name = "tidy",
    targets = [
        ":gps",
    ],
    tidy_config_file = "//:clang_tidy_config",
)
