load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "headers",
    hdrs = [
        "include/android/gps/GpsDevice.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//hardware/generic/goldfish/emulator/hal/connector:connector_registry_hdrs",
        "@abseil-cpp//absl/status",
        "@aemu//base:event-support",
    ],
)

cc_library(
    name = "gps",
    srcs = [
        "src/gps/GpsDevice.cpp",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":headers",
        "//hardware/generic/goldfish/emulator/hal/connector:PingTopic",
        "//hardware/generic/goldfish/emulator/hal/connector:cable",
        "//hardware/generic/goldfish/emulator/hal/connector:qemud",
        "//hardware/generic/goldfish/emulator/libs/gps",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/strings:str_format",
    ],
    alwayslink = True,
)

cc_test(
    name = "gps_unittests",
    srcs = [
        "test/gps/GpsDevice_unittest.cpp",
    ],
    includes = ["test"],
    linkopts = select({
        "@platforms//os:macos": ["-undefined error"],
        "//conditions:default": [],
    }),
    deps = [
        ":gps",
        "//hardware/generic/goldfish/android/system:googletest_main",
        "//hardware/generic/goldfish/android/system:test-headers",
        "//hardware/generic/goldfish/emulator/config:avd-test",
        "//hardware/generic/goldfish/emulator/hal/connector:test-helpers",
        "//hardware/generic/goldfish/emulator/hal/plug:fake_vsock",
    ],
)

cc_library(
    name = "test_gps",
    hdrs = [
        "test/FakeGpsDevice.h",
    ],
    includes = ["test"],
    visibility = ["//visibility:public"],
    deps = [
        ":headers",
    ],
)
