load("@bazel_skylib//lib:selects.bzl", "selects")
load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")
load("launcher_test.bzl", "create_launch_emulator_test")
load("plugins.bzl", "collect_plugins")
load("version_info.bzl", "version_info_header")

cc_library(
    name = "headers",
    srcs = [
        "include/android/goldfish/config/emulator.h",
        "include/android/goldfish/devices/device.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//hardware/generic/goldfish/emulator/cmdline",
    ],
)

cc_library(
    name = "logconfig",
    srcs = [
        "src/android/goldfish/logging.cpp",
    ],
    hdrs = [
        "include/android/goldfish/logging.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//hardware/generic/goldfish/emulator/cmdline",
        "@com_google_absl//absl/log",
        "@com_google_absl//absl/log:initialize",
        "@com_google_absl//absl/strings",
    ],
)

cc_test(
    name = "logging_test",
    srcs = ["test/android/goldfish/logging_unittest.cpp"],
    deps = [
        ":logconfig",
        "//hardware/generic/goldfish/android/logging:backend",
        "//hardware/generic/goldfish/android/system:googletest_main",
        "//hardware/generic/goldfish/android/system:test-headers",
        "@com_google_absl//absl/strings",
    ],
)

cc_library(
    name = "bootconfig",
    srcs = [
        "src/android/goldfish/bootconfig.cpp",
    ],
    hdrs = [
        "src/android/goldfish/bootconfig.h",
    ],
    includes = ["src"],
    visibility = ["//visibility:public"],
    deps = [
        "//hardware/generic/goldfish/android/system",
    ],
)

cc_test(
    name = "bootconfig_test",
    srcs = ["test/android/goldfish/bootconfig_unittest.cpp"],
    deps = [
        ":bootconfig",
        "//hardware/generic/goldfish/android/logging:backend",
        "//hardware/generic/goldfish/android/system:googletest_main",
        "//hardware/generic/goldfish/android/system:test-headers",
    ],
)

cc_library(
    name = "emulator",
    srcs = ["src/android/goldfish/emulator.cpp"],
    # Qemu roms needed for unittests - Emulator check that it is available.
    data = ["//third_party/qemu:qemu-roms"],
    visibility = ["//visibility:public"],
    deps = [
        "//hardware/generic/goldfish/android/system",
        "//hardware/generic/goldfish/emulator/cmdline",
        "//hardware/generic/goldfish/emulator/config",
        "//hardware/generic/goldfish/emulator/crashreport:detectors",
        "//hardware/generic/goldfish/emulator/launcher/src/android/goldfish/devices:audio_device",
        "//hardware/generic/goldfish/emulator/launcher/src/android/goldfish/devices:cpu_device",
        "//hardware/generic/goldfish/emulator/launcher/src/android/goldfish/devices:gpu_device",
        "//hardware/generic/goldfish/emulator/launcher/src/android/goldfish/devices:grpc_device",
        "//hardware/generic/goldfish/emulator/launcher/src/android/goldfish/devices:initrd_device",
        "//hardware/generic/goldfish/emulator/launcher/src/android/goldfish/devices:kernel_device",
        "//hardware/generic/goldfish/emulator/launcher/src/android/goldfish/devices:machine",
        "//hardware/generic/goldfish/emulator/launcher/src/android/goldfish/devices:memory_device",
        "//hardware/generic/goldfish/emulator/launcher/src/android/goldfish/devices:parameter_list",
        "//hardware/generic/goldfish/emulator/launcher/src/android/goldfish/devices/drives:cache_drive",
        "//hardware/generic/goldfish/emulator/launcher/src/android/goldfish/devices/drives:disk_drive",
        "//hardware/generic/goldfish/emulator/launcher/src/android/goldfish/devices/drives:encryption_drive",
        "//hardware/generic/goldfish/emulator/launcher/src/android/goldfish/devices/drives:sdcard_drive",
        "//hardware/generic/goldfish/emulator/launcher/src/android/goldfish/devices/drives:user_data_drive",
        "@aemu//base:aemu-base",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings",
        "@com_google_absl//absl/strings:str_format",
    ] + select({
        "@platforms//os:windows": [
            "//hardware/generic/goldfish/android/windows/posix:compat",
        ],
        "//conditions:default": [],
    }),
)

test_suite(
    name = "emulator_unittests",
    tests = [
        ":bootconfig_test",
        "//hardware/generic/goldfish/emulator/launcher/src/android/goldfish/devices:cpu_device_test",
        "//hardware/generic/goldfish/emulator/launcher/src/android/goldfish/devices:kernel_device_test",
        "//hardware/generic/goldfish/emulator/launcher/src/android/goldfish/devices:machine_test",
        "//hardware/generic/goldfish/emulator/launcher/src/android/goldfish/devices/drives:disk_drive_test",
    ],
)

selects.config_setting_group(
    name = "darwin_aarch64",
    match_all = [
        "@platforms//os:macos",
        "@platforms//cpu:aarch64",
    ],
)

selects.config_setting_group(
    name = "darwin_x86_64",
    match_all = [
        "@platforms//os:macos",
        "@platforms//cpu:x86_64",
    ],
)

collect_plugins(
    name = "plugins",
    output_dir = "plugins",
    plugins = [
        "//hardware/generic/goldfish/emulator/plugin:goldfish_x86_64",
        "@crosvm//:rutabaga_ffi",
    ] + select({
        "@platforms//os:windows": [],
        "//conditions:default": [
            "//hardware/generic/goldfish/emulator/plugin:goldfish_aarch64",
            "//hardware/generic/goldfish/emulator/plugin:goldfish_riscv64",
        ],
    }) + select({
        "darwin_aarch64": [
            "//prebuilts/android-emulator-build/common/vulkan:lib_darwin_aarch64",
            "//prebuilts/android-emulator-build/common/ANGLE:lib_darwin_aarch64",
        ],
        "@platforms//os:linux": [
            "//prebuilts/android-emulator-build/common/ANGLE:lib_linux_x86_64",
            "//prebuilts/android-emulator-build/common/vulkan:lib_linux_x86_64",
        ],
        "//conditions:default": [],
    }),
)

collect_plugins(
    name = "vulkan_icds",
    output_dir = "plugins/lib64/vulkan",
    plugins = select({
        "darwin_aarch64": [
            "//prebuilts/android-emulator-build/common/vulkan:icds_darwin_aarch64",
        ],
        "@platforms//os:linux": [
            "//prebuilts/android-emulator-build/common/vulkan:icds_linux_x86_64",
        ],
        "//conditions:default": [],
    }),
)

cc_binary(
    name = "goldfish",
    srcs = [
        "aemu_version.h",
        "src/android/goldfish/launcher.cpp",
    ],
    data = [
        ":plugins",
        ":vulkan_icds",
        "//hardware/generic/goldfish/emulator/grpc/security:unsecure-emulator-access",
        "//third_party/qemu:qemu-img",
        "//third_party/qemu:qemu-keymaps",
        "//third_party/qemu:qemu-roms",
        "//third_party/qemu:qemu-system-x86_64",
    ] + select({
        "@platforms//os:windows": [],
        "//conditions:default": [
            "//third_party/qemu:qemu-system-aarch64",
            "//third_party/qemu:qemu-system-riscv64",
        ],
    }),
    includes = [
        ".",
        "include",
        "src",
    ],
    linkopts = select({
        "@platforms//os:macos": ["-undefined error"],
        "//conditions:default": [],
    }),
    visibility = ["//visibility:public"],
    deps = [
        ":emulator",
        ":logconfig",
        "//hardware/generic/goldfish/android/cpu",
        "//hardware/generic/goldfish/android/filesystems",
        "//hardware/generic/goldfish/android/system",
        "//hardware/generic/goldfish/emulator/adb/secrets",
        "//hardware/generic/goldfish/emulator/cmdline",
        "//hardware/generic/goldfish/emulator/crashreport:init",
        "//hardware/generic/goldfish/third_party/json",
        "//third_party/qemu:qemu-headers",
        "@aemu//base:aemu-base",
        "@com_google_absl//absl/flags:flag",
        "@com_google_absl//absl/flags:parse",
        "@com_google_absl//absl/log:initialize",
    ],
)

version_info_header(
    name = "version_info",
    outs = "aemu_version.h",
    template = "src/version_template.h.in",
    version_info = "//hardware/generic/goldfish/emulator:aemu_version_info",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "aemu_version",
    hdrs = ["aemu_version.h"],
    visibility = ["//visibility:public"],
)

create_launch_emulator_test(
    name = "can_launch_kernel_with_minigbm",
    target_log_line = "'Linux version 6\\.6\\.66-android15-8-gb66429556fb8-ab13070261'",
    timeout_seconds = 30,
)

create_launch_emulator_test(
    name = "can_boot_with_minigbm",
    target_log_line = "'Completed booting in: \\d+ ms.'",
    timeout_seconds = 120,
)

create_launch_emulator_test(
    name = "can_boot_with_minigbm_2x",
    repeat = 1,
    target_log_line = "'Completed booting in: \\d+ ms.'",
    timeout_seconds = 180,
)

test_suite(
    name = "launcher_unittests",
    tests = [
        ":can_boot_with_minigbm",
        ":can_boot_with_minigbm_2x",
        ":can_launch_kernel_with_minigbm",
        ":emulator_unittests",
        ":logging_test",
    ],
)
