load("@bazel_skylib//lib:selects.bzl", "selects")
load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")
load("@rules_python//python:defs.bzl", "py_binary", "py_library")
load("//hardware/generic/goldfish/emulator/tools:plugins.bzl", "collect_plugins")
load("launcher_test.bzl", "create_launch_emulator_test")

cc_library(
    name = "input_paths",
    srcs = ["src/android/goldfish/input_paths.cpp"],
    hdrs = ["include/android/goldfish/input_paths.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//hardware/generic/goldfish/android/async:uv_to_absl",
        "//hardware/generic/goldfish/android/system",
        "//hardware/generic/goldfish/emulator/config:config_dirs",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/status:statusor",
        "@aemu//base:aemu-base",
        "@libuv",
    ],
)

cc_library(
    name = "emulator_config",
    hdrs = ["include/android/goldfish/emulator_config.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":input_paths",
        "//hardware/generic/goldfish/emulator/cmdline",
        "//hardware/generic/goldfish/emulator/config:avd",
    ],
)

cc_library(
    name = "device",
    hdrs = ["include/android/goldfish/device.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":emulator_config",
    ],
)

cc_library(
    name = "logconfig",
    srcs = [
        "src/android/goldfish/logging.cpp",
    ],
    hdrs = [
        "include/android/goldfish/logging.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//hardware/generic/goldfish/emulator/cmdline",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:initialize",
        "@abseil-cpp//absl/strings",
    ],
)

cc_test(
    name = "logging_test",
    srcs = ["test/android/goldfish/logging_unittest.cpp"],
    deps = [
        ":logconfig",
        "//hardware/generic/goldfish/android/logging:backend",
        "//hardware/generic/goldfish/android/system:googletest_main",
        "//hardware/generic/goldfish/android/system:test-headers",
        "@abseil-cpp//absl/strings",
    ],
)

cc_library(
    name = "bootconfig",
    srcs = ["src/android/goldfish/bootconfig.cpp"],
    hdrs = ["src/android/goldfish/bootconfig.h"],
    includes = ["src"],
    visibility = ["//visibility:public"],
    deps = ["//hardware/generic/goldfish/android/system"],
)

cc_test(
    name = "bootconfig_test",
    srcs = ["test/android/goldfish/bootconfig_unittest.cpp"],
    deps = [
        ":bootconfig",
        "//hardware/generic/goldfish/android/logging:backend",
        "//hardware/generic/goldfish/android/system:googletest_main",
        "//hardware/generic/goldfish/android/system:test-headers",
    ],
)

cc_library(
    name = "emulator",
    srcs = [
        "include/android/goldfish/emulator.h",
        "src/android/goldfish/emulator.cpp",
    ],
    # Qemu roms needed for unittests - Emulator check that it is available.
    data = ["//third_party/qemu:qemu-roms"],
    visibility = ["//visibility:public"],
    deps = [
        ":emulator_config",
        ":input_paths",
        "//hardware/generic/goldfish/android/async:launch_config",
        "//hardware/generic/goldfish/android/system",
        "//hardware/generic/goldfish/emulator/cmdline",
        "//hardware/generic/goldfish/emulator/config:avd",
        "//hardware/generic/goldfish/emulator/crashreport:detectors",
        "//hardware/generic/goldfish/emulator/launcher/src/android/goldfish/devices:adb_device",
        "//hardware/generic/goldfish/emulator/launcher/src/android/goldfish/devices:audio_device",
        "//hardware/generic/goldfish/emulator/launcher/src/android/goldfish/devices:avd_info_device",
        "//hardware/generic/goldfish/emulator/launcher/src/android/goldfish/devices:cpu_device",
        "//hardware/generic/goldfish/emulator/launcher/src/android/goldfish/devices:display_device",
        "//hardware/generic/goldfish/emulator/launcher/src/android/goldfish/devices:gpu_device",
        "//hardware/generic/goldfish/emulator/launcher/src/android/goldfish/devices:grpc_device",
        "//hardware/generic/goldfish/emulator/launcher/src/android/goldfish/devices:initrd_device",
        "//hardware/generic/goldfish/emulator/launcher/src/android/goldfish/devices:kernel_device",
        "//hardware/generic/goldfish/emulator/launcher/src/android/goldfish/devices:machine",
        "//hardware/generic/goldfish/emulator/launcher/src/android/goldfish/devices:memory_device",
        "//hardware/generic/goldfish/emulator/launcher/src/android/goldfish/devices:network_device",
        "//hardware/generic/goldfish/emulator/launcher/src/android/goldfish/devices:parameter_list",
        "//hardware/generic/goldfish/emulator/launcher/src/android/goldfish/devices:wifi_device",
        "//hardware/generic/goldfish/emulator/launcher/src/android/goldfish/devices/drives:configure_drives",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
        "@aemu//base:aemu-base",
    ] + select({
        "@platforms//os:windows": [
            "//hardware/generic/goldfish/android/windows/posix:compat",
        ],
        "//conditions:default": [],
    }),
)

cc_library(
    name = "netsimd",
    srcs = ["src/android/goldfish/netsimd.cpp"],
    hdrs = ["include/android/goldfish/netsimd.h"],
    includes = ["include"],
    deps = [
        "//hardware/generic/goldfish/android/async:launch_config",
        "//hardware/generic/goldfish/android/network",
        "//hardware/generic/goldfish/emulator/cmdline",
        "//hardware/generic/goldfish/emulator/grpc/client:emulator_grpc_client",
        "@grpc//:grpc++",
    ],
)

selects.config_setting_group(
    name = "darwin_aarch64",
    match_all = [
        "@platforms//os:macos",
        "@platforms//cpu:aarch64",
    ],
)

selects.config_setting_group(
    name = "darwin_x86_64",
    match_all = [
        "@platforms//os:macos",
        "@platforms//cpu:x86_64",
    ],
)

collect_plugins(
    name = "plugins",
    output_dir = "lib/qemu",
    plugins = [
        "//hardware/generic/goldfish/emulator/plugin:goldfish_x86_64",
        "@crosvm//:rutabaga_ffi",
    ] + select({
        "darwin_aarch64": [
            "//hardware/generic/goldfish/emulator/plugin:goldfish_aarch64",
            "//hardware/generic/goldfish/emulator/plugin:goldfish_riscv64",
        ],
        "@platforms//os:linux": [
            "//hardware/generic/goldfish/emulator/plugin:goldfish_aarch64",
            "//hardware/generic/goldfish/emulator/plugin:goldfish_riscv64",
            # For old netsimd prebuilt
            "//prebuilts/android-emulator-build/common/vulkan:linux_libc++",
        ],
        "@platforms//os:windows": [
            # We don't build Qemu system aarch64 or riscv64 on Windows.
        ],
        "//conditions:default": [],
    }),
)

collect_plugins(
    name = "vulkan_icds",
    output_dir = "lib64/vulkan",
    plugins = select({
        "darwin_aarch64": [
            "//prebuilts/android-emulator-build/common/vulkan:icds_darwin_aarch64",
            "//prebuilts/android-emulator-build/common/vulkan:lib_darwin_aarch64",
        ],
        "@platforms//os:linux": [
            "//prebuilts/android-emulator-build/common/vulkan:icds_linux_x86_64",
            "//prebuilts/android-emulator-build/common/vulkan:lib_linux_x86_64",
        ],
        "@platforms//os:windows": [
            "//prebuilts/android-emulator-build/common/vulkan:icds_windows_x86_64",
            "//prebuilts/android-emulator-build/common/vulkan:lib_windows_x86_64",
        ],
        "//conditions:default": [],
    }),
)

collect_plugins(
    name = "lib64gl",
    output_dir = "lib64",
    plugins = select({
        "darwin_aarch64": [
            "//prebuilts/android-emulator-build/common/ANGLE:lib_darwin_aarch64",
            "//prebuilts/android-emulator-build/common/vulkan:lib_darwin_aarch64",
            "//prebuilts/android-emulator-build/common/vulkan:icds_darwin_aarch64",
        ],
        "@platforms//os:linux": [
            "//prebuilts/android-emulator-build/common/swiftshader:lib_linux_x86_64",
        ],
        "@platforms//os:windows": [
            "//prebuilts/android-emulator-build/common/ANGLE:lib_windows_x86_64",
            "//prebuilts/android-emulator-build/common/vulkan:lib_windows_x86_64",
            "//prebuilts/android-emulator-build/common/vulkan:icds_windows_x86_64",
        ],
        "//conditions:default": [],
    }),
)

collect_plugins(
    name = "binaries",
    output_dir = "bin",
    plugins = [
        "//hardware/generic/goldfish/emulator/crashreport",
        "//hardware/generic/goldfish/third_party/sparse:img2simg",
        "//third_party/qemu:qemu-img",
        "@com_google_crashpad//handler:crashpad_handler",
        #"@netsim//:netsimd",
    ] + select({
        "@platforms//os:windows": [
            "//prebuilts/android-emulator-build/common/netsim:netsim_windows_x86_64",
            "//third_party/qemu:qemu-system-x86_64",
        ],
        "@platforms//os:macos": [
            "//prebuilts/android-emulator-build/common/netsim:netsim_darwin_aarch64",
            "//third_party/qemu:qemu-system-aarch64_signed",
            "//third_party/qemu:qemu-system-riscv64_signed",
            "//third_party/qemu:qemu-system-x86_64_signed",
        ],
        "//conditions:default": [
            "//prebuilts/android-emulator-build/common/netsim:netsim_linux_x86_64",
            "//third_party/qemu:qemu-system-aarch64",
            "//third_party/qemu:qemu-system-riscv64",
            "//third_party/qemu:qemu-system-x86_64",
        ],
    }),
)

collect_plugins(
    name = "roms",
    output_dir = "share/qemu",
    plugins = [
        "//third_party/qemu:qemu-roms",
    ],
)

collect_plugins(
    name = "keymaps",
    output_dir = "share/qemu/keymaps",
    plugins = [
        "//third_party/qemu:qemu-keymaps",
    ],
)

cc_binary(
    name = "launcher",
    srcs = ["src/android/goldfish/launcher.cpp"],
    data = [
        ":binaries",
        ":keymaps",
        ":lib64gl",
        ":plugins",
        ":roms",
        ":vulkan_icds",
        "//hardware/generic/goldfish/emulator/grpc/security:unsecure-emulator-access",
    ],
    includes = ["."],
    linkopts = select({
        "@platforms//os:macos": ["-undefined error"],
        "//conditions:default": [],
    }),
    visibility = ["//visibility:public"],
    deps = [
        ":emulator",
        ":input_paths",
        ":logconfig",
        ":netsimd",
        "//hardware/generic/goldfish/android/async:libuv_event_loop",
        "//hardware/generic/goldfish/android/async:libuv_process_launcher",
        "//hardware/generic/goldfish/android/cpu",
        "//hardware/generic/goldfish/android/filesystems",
        "//hardware/generic/goldfish/android/system",
        "//hardware/generic/goldfish/emulator/adb/secrets",
        "//hardware/generic/goldfish/emulator/cmdline",
        "//hardware/generic/goldfish/emulator/crashreport:init",
        "//hardware/generic/goldfish/emulator/tools:aemu_version",
        "//hardware/generic/goldfish/third_party/json",
        "//third_party/qemu:qemu-headers",
        "@abseil-cpp//absl/debugging:failure_signal_handler",
        "@abseil-cpp//absl/debugging:symbolize",
        "@abseil-cpp//absl/flags:flag",
        "@abseil-cpp//absl/flags:parse",
        "@abseil-cpp//absl/log:initialize",
        "@aemu//base:aemu-base",
    ],
)

create_launch_emulator_test(
    name = "can_launch_kernel_with_minigbm",
    params = [
        "-show-kernel",
        "-no-boot-anim",
    ],
    target_log_line = "'Linux version 6\\.6\\.66-android15-8-gb66429556fb8-ab13070261'",
    timeout_seconds = 30,
)

create_launch_emulator_test(
    name = "can_boot_with_minigbm",
    params = [
        "-show-kernel",
        "-no-boot-anim",
    ],
    target_log_line = "'Boot completed in \\d+ ms'",
    timeout_seconds = 180,
)

create_launch_emulator_test(
    # This tests validates that the we receive at least a series frames from the guest.
    name = "emulator_produces_pixels",
    params = [
        "-vmodule",
        "'PixmanDisplay=2'",
    ],
    target_log_line = "'updateSurface Display: 0 \\(1080x2400\\), seq: 25'",
    timeout_seconds = 180,
)

create_launch_emulator_test(
    name = "can_boot_with_minigbm_2x",
    params = [
        "-show-kernel",
        "-no-boot-anim",
    ],
    repeat = 1,
    target_log_line = "'Boot completed in \\d+ ms'",
    timeout_seconds = 180,
)

test_suite(
    name = "boot_tests",
    tags = ["manual"],
    tests = [
        ":can_boot_with_minigbm",
        ":can_boot_with_minigbm_2x",
        ":can_boot_with_minigbm_2x_zip",
        ":can_boot_with_minigbm_zip",
        ":can_launch_kernel_with_minigbm",
        ":can_launch_kernel_with_minigbm_zip",
        ":emulator_produces_pixels",
    ],
)

py_library(
    name = "emulator_lib",
    srcs = ["src/emulator_lib.py"],
    visibility = ["//visibility:__pkg__"],
    deps = ["@rules_python//python/runfiles"],
)

py_binary(
    name = "launch_emulator",
    srcs = ["src/launch_kernel.py"],
    data = [
        ":launcher",
    ] + select({
        "@platforms//os:macos": [
            "//hardware/generic/goldfish/emulator/sdk/system_images/minigbm-arm64-v8a:minigbm",
            "@android_minigbm-arm64-v8a//:system_image",
        ],
        "//conditions:default": [
            "//hardware/generic/goldfish/emulator/sdk/system_images/minigbm-x86_64:minigbm",
            "@android_minigbm-x86_64//:system_image",
        ],
    }) + [
        "//hardware/generic/goldfish/emulator/sdk:sdk-marker-files",
    ],
    main = "src/launch_kernel.py",
    deps = [
        ":emulator_lib",
        "@rules_python//python/runfiles",
    ],
)
