"""Generates a header file by substituting version information into a template.

This rule takes version information from a `PackageVariablesInfo` provider and a
template file, performs substitutions, and writes the result to a specified
output file.  This allows build-related information to be embedded into source
code.
"""

load("@rules_pkg//pkg:providers.bzl", "PackageVariablesInfo")

def _version_info_header_impl(ctx):
    """Implementation function for `version_info_header`.

    Args:
        ctx: The rule context.

    Returns:
       None
    """
    version_info = ctx.attr.version_info[PackageVariablesInfo]
    output_file = ctx.outputs.outs
    ctx.actions.expand_template(
        template = ctx.file.template,
        output = output_file,
        substitutions = {
            "@BUILD_ID@": version_info.values["build_id"],
            "@REVISION@": version_info.values["revision"],
            "@VERSION@": version_info.values["version"],
            "@PRODUCT_NAME@": version_info.values["product_name"],
            "@PLATFORM@": version_info.values["platform"],
            "@TARGET_CPU@": version_info.values["target_cpu"],
            "@COMPILATION_MODE@": version_info.values["compilation_mode"],
        },
    )

version_info_header = rule(
    implementation = _version_info_header_impl,
    attrs = {
        "version_info": attr.label(
            providers = [PackageVariablesInfo],
            doc = "Package variable info with version information.",
        ),
        "template": attr.label(
            default = Label(":version_template.h.in"),
            allow_single_file = True,
            doc = "Template file",
        ),
        "outs": attr.output(
            mandatory = True,
            doc = "The output object file generated by the template substitution.",
        ),
    },
)
