cc_library(
    name = "system",
    srcs = glob(
               [
                   "src/android/base/system/*.cpp",
                   "src/android/base/*.cpp",
               ],
               exclude = ["src/**/Win32*"],
           ) +
           select({
               "@platforms//os:windows": glob(["src/**/Win32*"]),
               "//conditions:default": [],
           }),
    hdrs = [
        "include/android/base/file/file_io.h",
        "include/android/base/system/CStrWrapper.h",
        "include/android/base/system/System.h",
        "include/android/base/system/Win32UnicodeString.h",
        "include/android/base/system/Win32Utils.h",
        "include/android/utils/compiler.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//hardware/google/aemu/base:aemu-base",
        "@com_google_absl//absl/strings",
        "@com_google_absl//absl/strings:str_format",
    ],
)

cc_library(
    name = "test-headers",
    hdrs = glob(["test-headers/**/*.h"]),
    includes = ["test-headers"],
    visibility = ["//visibility:public"],
    deps = [
        ":system",
        "//hardware/generic/goldfish/logging:backend",
        "//hardware/google/aemu/base:aemu-base",
        "@com_google_absl//absl/strings",
    ],
)

cc_test(
    name = "system-unittests",
    srcs = glob(
        [
            "test/**/*_unittest.cpp",
            "test/**/*.h",
        ],
        exclude = ["test/**/Win32*"],
    ) + select({
        "@platforms//os:windows": glob(["test/**/Win32*"]),
        "//conditions:default": [],
    }),
    # copts = ["],
    deps = [
        ":system",
        ":test-headers",
        "@com_google_googletest//:gtest_main",
    ],
)
