load("@goldfish_build//rules:clang_tidy.bzl", "clang_tidy_test")
load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "ev_dev_event",
    hdrs = ["include/android/emulation/control/ev_dev_event.h"],
    includes = ["include"],
)

cc_library(
    name = "slot_registry",
    srcs = ["slot_registry.cc"],
    hdrs = ["slot_registry.h"],
    deps = [
        ":ev_dev_event",
        "//emulator/libs/system:clock",
        "@abseil-cpp//absl/container:flat_hash_map",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:check",
        "@abseil-cpp//absl/time",
        "@qemu//:qemu-headers-exported",
    ],
)

cc_library(
    name = "pointer_event_dispatcher",
    srcs = ["pointer_event_dispatcher.cc"],
    hdrs = ["pointer_event_dispatcher.h"],
    deps = [
        ":ev_dev_event",
        ":slot_registry",
        "//emulator/plugin/display",
        "@abseil-cpp//absl/log",
        "@aemu//protos/services/emulator-controller:emulator_controller_cc_grpc",
        "@qemu//:qemu-headers-exported",
    ],
)

cc_library(
    name = "event_sender",
    srcs = ["event_sender.cc"],
    hdrs = ["include/android/emulation/control/event_sender.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":ev_dev_event",
        ":pointer_event_dispatcher",
        "//emulator/libs/status_macros",
        "//emulator/plugin/avd:info",
        "//emulator/plugin/display",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/status",
        "@aemu//protos/services/emulator-controller:emulator_controller_cc_grpc",
        "@qemu//:qemu-headers-exported",
    ],
)

cc_test(
    name = "slot_registry_test",
    srcs = ["slot_registry_test.cc"],
    visibility = ["//visibility:public"],
    deps = [
        ":slot_registry",
        "//emulator/libs/system:test-headers",
        "//emulator/libs/test:googletest_main",
        "@abseil-cpp//absl/time",
    ],
)

cc_test(
    name = "pointer_event_dispatcher_test",
    srcs = ["pointer_event_dispatcher_test.cc"],
    visibility = ["//visibility:public"],
    deps = [
        ":pointer_event_dispatcher",
        "//emulator/libs/async:async_testing",
        "//emulator/libs/grpc_utils:event-stream",
        "//emulator/libs/system:test-headers",
        "//emulator/libs/test:googletest_main",
        "//emulator/plugin/avd:info-fake",
        "//emulator/plugin/display:test-display",
        "@abseil-cpp//absl/flags:flag",
        "@abseil-cpp//absl/flags:parse",
        "@bazel_tools//tools/cpp/runfiles",
    ],
)

cc_test(
    name = "event_sender_test",
    srcs = ["event_sender_test.cc"],
    visibility = ["//visibility:public"],
    deps = [
        ":event_sender",
        "//emulator/libs/async:async_testing",
        "//emulator/libs/test:googletest_main",
        "//emulator/plugin/avd:info-fake",
        "//emulator/plugin/display:test-display",
        "@grpc",
    ],
)

clang_tidy_test(
    name = "tidy",
    targets = [
        "event_sender",
    ],
    tidy_config_file = "//:clang_tidy_config",
)
