# Copyright (C) 2026 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "capabilities_service",
    srcs = ["discovery/capabilities_service_impl.cc"],
    hdrs = ["discovery/capabilities_service_impl.h"],
    local_defines = select({
        "@platforms//os:windows": ["NOGDI"],
        "//conditions:default": [],
    }),
    deps = [
        "//emulator/plugin/avd:info",
        "@aemu//protos/services_v2/discovery:capabilities_service_cc_grpc",
        "@grpc//:grpc++",
    ],
)

cc_test(
    name = "capabilities_service_test",
    srcs = [
        "discovery/capabilities_service_impl_test.cc",
    ],
    local_defines = select({
        "@platforms//os:windows": ["NOGDI"],
        "//conditions:default": [],
    }),
    deps = [
        ":capabilities_service",
        "//emulator/libs/hardware_config:fake_hardware_config",
        "//emulator/libs/test:googletest_main",
        "//emulator/plugin/avd:info-fake",
        "//emulator/plugin/display:test-display",
        "@googletest//:gtest",
        "@grpc//:grpc++",
    ],
)

cc_library(
    name = "rtc_service",
    srcs = ["webrtc/rtc_service_impl.cc"],
    hdrs = ["webrtc/rtc_service_impl.h"],
    copts = select({
        "@platforms//os:windows": ["/GR-"],
        "//conditions:default": ["-fno-rtti"],
    }),
    includes = ["."],
    deps = [
        "//emulator/libs/grpc_utils:absl_translate",
        "//emulator/videobridge:session_id",
        "//emulator/videobridge:videobridge_core",
        "@abseil-cpp//absl/base:core_headers",
        "@abseil-cpp//absl/cleanup",
        "@abseil-cpp//absl/container:flat_hash_map",
        "@abseil-cpp//absl/container:flat_hash_set",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:check",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/synchronization",
        "@abseil-cpp//absl/time",
        "@aemu//protos/services_v2/webrtc:rtc_service_cc_grpc",
        "@grpc//:grpc++",
    ],
)

cc_test(
    name = "rtc_service_test",
    srcs = ["webrtc/rtc_service_impl_test.cc"],
    copts = select({
        "@platforms//os:windows": ["/GR-"],
        "//conditions:default": ["-fno-rtti"],
    }),
    linkopts = select({
        "@platforms//os:macos": [
            "-Wl,-ObjC",
            "-framework VideoToolbox",
            "-framework CoreMedia",
            "-framework AVFoundation",
            "-framework CoreVideo",
            "-framework Foundation",
        ],
        "@platforms//os:windows": [
            "strmiids.lib",
            "uuid.lib",
            "ole32.lib",
            "oleaut32.lib",
        ],
        "//conditions:default": [],
    }),
    deps = [
        ":rtc_service",
        "//emulator/libs/test:googletest_main",
        "//emulator/videobridge:videobridge_core",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/synchronization",
        "@abseil-cpp//absl/time",
        "@aemu//protos/services_v2/webrtc:rtc_service_cc_grpc",
        "@googletest//:gtest",
        "@grpc//:grpc++",
        "@nlohmann_json//:singleheader-json",
    ],
)

cc_library(
    name = "v2_services",
    srcs = ["v2_services.cc"],
    hdrs = ["include/goldfish/grpc/v2/v2_services.h"],
    includes = ["include"],
    deps = [
        ":capabilities_service",
        "//emulator/libs/async:async_api",
        "//emulator/plugin/avd:info",
        "//emulator/plugin/vminterface",
        "@grpc//:grpc++",
    ],
)
