load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "cable",
    srcs = [
        "cable.cpp",
    ],
    hdrs = [
        "include/goldfish/devices/cable/ErrorPlug.h",
        "include/goldfish/devices/cable/cable.h",
        "include/goldfish/devices/cable/saveload.h",
    ],
    includes = ["include"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//hardware/generic/goldfish/emulator/libs/archive",
    ],
    alwayslink = True,
)

cc_library(
    name = "qemud",
    srcs = [
        "qemud.cpp",
    ],
    hdrs = [
        "include/goldfish/devices/qemud.h",
    ],
    includes = ["include"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        ":cable",
    ],
    alwayslink = True,
)

cc_library(
    name = "PingTopic",
    hdrs = [
        "include/goldfish/devices/PingTopic.h",
    ],
    includes = ["include"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//hardware/generic/goldfish/emulator/libs/broadcasting",
    ],
    alwayslink = True,
)

cc_library(
    name = "devices",
    srcs = [
        "Connector.cpp",
    ],
    hdrs = [
        "include/goldfish/devices/Connector.h",
    ],
    includes = ["include"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        ":PingTopic",
        ":cable",
        ":qemud",
    ],
    alwayslink = True,
)

cc_library(
    name = "connection_awaiter",
    srcs = [
        "connection_awaiter.cpp",
    ],
    hdrs = [
        "include/goldfish/devices/connection_awaiter.h",
    ],
    includes = ["include"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//hardware/generic/goldfish/emulator/devices:cable",
        "@aemu//base:aemu-base",
    ],
)

cc_library(
    name = "connector_registry_hdrs",
    hdrs = [
        "include/goldfish/devices/connector_registry.h",
    ],
    includes = ["include"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        ":devices",
        "//hardware/generic/goldfish/android/async:async_api",
        "//hardware/generic/goldfish/emulator/hal/plug:hal_plug_to_i_plug_adapter",
        "@abseil-cpp//absl/base:no_destructor",
        "@abseil-cpp//absl/container:flat_hash_map",
        "@abseil-cpp//absl/strings",
        "@aemu//base:aemu-base",
        "@aemu//base:event-support",
    ],
)

cc_library(
    name = "connector_registry_impl",
    srcs = [
        "connector_registry.cpp",
    ],
    includes = ["include"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        ":connector_registry_hdrs",
        ":devices",
        "//hardware/generic/goldfish/android/async:async_api",
        "//hardware/generic/goldfish/emulator/hal/plug:hal_plug_friend",
        "//hardware/generic/goldfish/emulator/hal/plug:hal_plug_to_i_plug_adapter",
        "//hardware/generic/goldfish/emulator/hal/plug:marshalling_hal_socket",
        "//hardware/generic/goldfish/emulator/plugin/vsock_goldfish:goldfish_vsock_hdrs",
        "@abseil-cpp//absl/base:no_destructor",
        "@abseil-cpp//absl/container:flat_hash_map",
        "@abseil-cpp//absl/strings",
        "@aemu//base:aemu-base",
    ],
)

cc_test(
    name = "connector_registry_tests",
    size = "small",
    srcs = [
        "test/connector_registry_threading_unittest.cpp",
        "test/connector_registry_unittest.cpp",
    ],
    deps = [
        ":connector_registry_hdrs",
        ":connector_registry_impl",
        "//hardware/generic/goldfish/android/async:libuv_event_loop",
        "//hardware/generic/goldfish/android/system:googletest_main",
    ],
)

cc_test(
    name = "devices_unittests",
    size = "small",
    srcs = [
        "test/Connector_unittests.cpp",
        "test/connection_awaiter_unittest.cpp",
        "test/datasniffer_unittests.cpp",
        "test/qemud_unittests.cpp",
    ],
    deps = [
        ":connection_awaiter",
        ":devices",
        "//hardware/generic/goldfish/android/looper",
        "//hardware/generic/goldfish/android/sockets",
        "//hardware/generic/goldfish/android/system:googletest_main",
        "//hardware/generic/goldfish/emulator/libs/archive:DequeArchive",
    ],
)

cc_library(
    name = "test-helpers",
    srcs = [
        "test/goldfish/devices/test_socket.cpp",
    ],
    hdrs = [
        "include/goldfish/devices/connector_registry.h",
        "test/goldfish/devices/test_connector_registry.h",
        "test/goldfish/devices/test_fake_connector_registry.h",
        "test/goldfish/devices/test_socket.h",
    ],
    includes = [
        "include",
        "test",
    ],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        ":cable",
        ":connector_registry_impl",
        ":devices",
        "//hardware/generic/goldfish/android/looper",
        "//hardware/generic/goldfish/android/sockets",
        "//hardware/generic/goldfish/emulator/hal/bootproperties:test_bootproperties",
        "//hardware/generic/goldfish/emulator/hal/camera:test_camera",
        "//hardware/generic/goldfish/emulator/hal/clipboard:test_clipboard",
        "//hardware/generic/goldfish/emulator/hal/fingerprint:test_fingerprint",
        "//hardware/generic/goldfish/emulator/hal/gps:test_gps",
        "//hardware/generic/goldfish/emulator/hal/guest-status:test_guest-status",
        "//hardware/generic/goldfish/emulator/hal/sensors:test_sensors",
    ],
    alwayslink = True,
)
