copts = select({
    "@platforms//os:windows": [
        "/std:c++20",
    ],
    "//conditions:default": [
        "-std=c++20",
    ],
})

cc_library(
    name = "cable",
    srcs = [
        "cable.cpp",
    ],
    hdrs = [
        "include/goldfish/devices/cable/cable.h",
        "include/goldfish/devices/cable/saveload.h",
    ],
    copts = copts,
    includes = ["include"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//hardware/generic/goldfish/emulator/libs/archive",
    ],
    alwayslink = True,
)

cc_library(
    name = "qemud",
    srcs = [
        "qemud.cpp",
    ],
    hdrs = [
        "include/goldfish/devices/qemud.h",
    ],
    copts = copts,
    includes = ["include"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        ":cable",
    ],
    alwayslink = True,
)

cc_library(
    name = "PingTopic",
    hdrs = [
        "include/goldfish/devices/PingTopic.h",
    ],
    copts = copts,
    includes = ["include"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//hardware/generic/goldfish/emulator/libs/broadcasting",
    ],
    alwayslink = True,
)

cc_library(
    name = "devices",
    srcs = [
        "Connector.cpp",
    ],
    hdrs = [
        "include/goldfish/devices/Connector.h",
    ],
    copts = copts,
    includes = ["include"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        ":PingTopic",
        ":cable",
        ":qemud",
    ],
    alwayslink = True,
)

cc_library(
    name = "connection_awaiter",
    srcs = [
        "connection_awaiter.cpp",
    ],
    hdrs = [
        "include/goldfish/devices/connection_awaiter.h",
    ],
    copts = copts,
    includes = ["include"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//hardware/generic/goldfish/emulator/devices:cable",
        "//hardware/google/aemu/base:aemu-base",
    ],
)

cc_library(
    name = "connector_registry",
    srcs = [
        "connector_registry.cpp",
    ],
    hdrs = [
        "include/goldfish/devices/connector_registry.h",
    ],
    copts = copts,
    includes = ["include"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        ":devices",
        "//hardware/generic/goldfish/emulator/plugin/vsock_goldfish:goldfish_vsock_hdrs",
        "//hardware/google/aemu/base:aemu-base",
        "@com_google_absl//absl/base:no_destructor",
        "@com_google_absl//absl/container:flat_hash_map",
        "@com_google_absl//absl/strings",
    ],
)

cc_test(
    name = "devices_unittests",
    size = "small",
    srcs = glob(
        [
            "test/*.cpp",
        ],
    ),
    copts = copts,
    deps = [
        ":connection_awaiter",
        ":connector_registry",
        ":devices",
        "//hardware/generic/goldfish/android/looper",
        "//hardware/generic/goldfish/android/sockets",
        "//hardware/generic/goldfish/emulator/libs/archive:DequeArchive",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_library(
    name = "test-socket",
    srcs = [
        "test/goldfish/devices/test_socket.cpp",
    ],
    hdrs = [
        "test/goldfish/devices/test_socket.h",
    ],
    copts = copts,
    includes = ["test"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        ":cable",
        "//hardware/generic/goldfish/android/looper",
        "//hardware/generic/goldfish/android/sockets",
    ],
    alwayslink = True,
)
