cc_library(
    name = "cable",
    srcs = [
        "cable.cpp",
    ],
    hdrs = [
        "include/goldfish/devices/cable/cable.h",
        "include/goldfish/devices/cable/saveload.h",
    ],
    includes = ["include"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//hardware/generic/goldfish/emulator/libs/archive",
    ],
    alwayslink = True,
)
