load("@goldfish_build//rules:clang_tidy.bzl", "clang_tidy_test")
load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "debug",
    hdrs = [
        "include/goldfish/debug.h",
    ],
    includes = ["include"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "@abseil-cpp//absl/log",
    ],
)

clang_tidy_test(
    name = "tidy",
    targets = [
        ":debug",
    ],
    tidy_config_file = "//:clang_tidy_config",
)
