load("@goldfish_build//rules:clang_tidy.bzl", "clang_tidy_test")
load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

clang_tidy_test(
    name = "tidy",
    targets = [
        # TODO(whollins): Figure out why these don't work.
        #":uuid",
        #":metrics_reporter",
        #":text_metrics_writer",
    ],
    tidy_config_file = "//:clang_tidy_config",
)

cc_library(
    name = "uuid",
    srcs = ["uuid.cc"],
    hdrs = ["include/goldfish/metrics/uuid.h"],
    includes = ["include"],
    linkopts = select({
        "@platforms//os:windows": [
            "-DEFAULTLIB:Rpcrt4.lib",
        ],
        "//conditions:default": [],
    }),
    deps = [
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
    ] + select({
        "@platforms//os:windows": [],
        "//conditions:default": ["@libuuid"],
    }),
)

cc_test(
    name = "uuid_test",
    srcs = ["uuid_test.cc"],
    deps = [
        ":uuid",
        "//emulator/libs/status_macros:status_matcher_macros",
        "//emulator/libs/test:googletest_main",
    ],
)

cc_library(
    name = "studio_stats_wrapper",
    hdrs = ["include/goldfish/metrics/studio_stats_wrapper.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = ["@studio_stats//:studio_stats_cc_proto"],
)

cc_library(
    name = "metrics_writer",
    hdrs = ["include/goldfish/metrics/metrics_writer.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [":studio_stats_wrapper"],
)

cc_library(
    name = "metrics_reporter",
    srcs = ["metrics_reporter.cc"],
    hdrs = ["include/goldfish/metrics/metrics_reporter.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":metrics_writer",
        ":studio_stats_wrapper",
        ":uuid",
        "//emulator/libs/system",
        "//emulator/tools:aemu_version",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
        "@abseil-cpp//absl/synchronization",
    ],
)

alias(
    name = "metrics",
    actual = ":metrics_reporter",
    visibility = ["//visibility:public"],
)

cc_test(
    name = "metrics_reporter_test",
    srcs = ["metrics_reporter_test.cc"],
    deps = [
        ":metrics_reporter",
        "//emulator/libs/test:googletest_main",
    ],
)

cc_library(
    name = "configure_metrics_writer",
    hdrs = ["include/goldfish/metrics/configure_metrics_writer.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":metrics_reporter",
        ":metrics_writer",
        ":studio_file_metrics_writer",
        ":text_metrics_writer",
        "//emulator/libs/async:async_api",
        "//emulator/libs/file",
    ],
)

cc_library(
    name = "text_metrics_writer",
    srcs = ["text_metrics_writer.cc"],
    hdrs = ["include/goldfish/metrics/text_metrics_writer.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":metrics_writer",
        "@abseil-cpp//absl/log",
        "@protobuf",
    ],
)

cc_test(
    name = "text_metrics_writer_test",
    srcs = ["text_metrics_writer_test.cc"],
    deps = [
        ":text_metrics_writer",
        "//emulator/libs/test:googletest_main",
        "@abseil-cpp//absl/base:log_severity",
        "@abseil-cpp//absl/log:globals",
    ],
)

cc_library(
    name = "cpu_usage",
    hdrs = ["include/goldfish/metrics/cpu_usage.h"],
    includes = ["include"],
    deps = [
        "//emulator/libs/async:async_api",
        "//emulator/libs/system",
    ],
)

cc_library(
    name = "perf_stat_reporter",
    srcs = ["perf_stat_reporter.cc"],
    hdrs = ["include/goldfish/metrics/perf_stat_reporter.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":cpu_usage",
        ":text_metrics_writer",
        "//emulator/libs/hardware_config",
        "//emulator/libs/system",
    ],
)

cc_test(
    name = "perf_stat_reporter_test",
    srcs = ["perf_stat_reporter_test.cc"],
    deps = [
        ":perf_stat_reporter",
        "//emulator/libs/async:async_testing",
        "//emulator/libs/hardware_config:fake_hardware_config",
        "//emulator/libs/system:test-headers",
        "//emulator/libs/test:googletest_main",
    ],
)

cc_library(
    name = "studio_config",
    srcs = ["studio_config.cc"],
    hdrs = ["include/goldfish/metrics/studio_config.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//emulator/libs/file",
        "@nlohmann_json//:singleheader-json",
    ],
)

cc_test(
    name = "studio_config_test",
    srcs = ["studio_config_test.cc"],
    deps = [
        ":studio_config",
        "//emulator/libs/system:test-headers",
        "//emulator/libs/test:googletest_main",
    ],
)

cc_library(
    name = "studio_file_metrics_writer",
    srcs = ["studio_file_metrics_writer.cc"],
    hdrs = ["include/goldfish/metrics/studio_file_metrics_writer.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":metrics_writer",
        "//emulator/libs/async:async_api",
        "//emulator/libs/file",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/strings:str_format",
        "@abseil-cpp//absl/synchronization",
        "@protobuf",
        "@studio_stats//:google_logs_publishing_cc_proto",
    ],
)

cc_test(
    name = "studio_file_metrics_writer_test",
    srcs = ["studio_file_metrics_writer_test.cc"],
    deps = [
        ":studio_file_metrics_writer",
        "//emulator/libs/async:async_testing",
        "//emulator/libs/system:test-headers",
        "//emulator/libs/test:googletest_main",
    ],
)
