load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "filesystems",
    srcs = [
        "src/android/filesystems/ext4_resize.cpp",
        "src/android/filesystems/ext4_utils.cpp",
    ],
    hdrs = [
        "include/android/filesystems/ext4_resize.h",
        "include/android/filesystems/ext4_utils.h",
    ],
    includes = [
        "include",
        "src",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//android/ext4_utils",
        "//android/files",
        "//android/process",
        "//android/system",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:absl_log",
        "@aemu//base:aemu-base",
    ],
)
