load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "headers",
    hdrs = [
        "include/android/goldfish/display/Display.h",
        "include/android/goldfish/display/MultiDisplay.h",
        "include/android/goldfish/display/PixmanDisplay.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//hardware/generic/goldfish/emulator/grpc/event-stream",
        # "//hardware/generic/goldfish/emulator/grpc/services/emulator_controller/proto:emulator_controller_cc_grpc",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/time",
    ],
)

cc_library(
    name = "display",
    srcs = [
        "src/android/goldfish/display/MultiDisplay.cpp",
        "src/android/goldfish/display/NullDisplay.h",
        "src/android/goldfish/display/PixmanDisplay.cpp",
        "src/android/goldfish/display/QemuDisplay.cpp",
        "src/android/goldfish/display/QemuDisplay.h",
        "src/android/goldfish/display/virtio-bridge.c",
        "src/android/goldfish/display/virtio-bridge.h",
    ],
    includes = ["src"],
    linkstatic = False,
    visibility = ["//visibility:public"],
    deps = [
        ":headers",
        "//external/qemu:libmodule-common",
        "//external/qemu:qemu-headers",
        "//hardware/generic/goldfish/emulator/grpc/event-stream",
        "//hardware/generic/goldfish/emulator/hal/sensors",
        "//hardware/generic/goldfish/emulator/plugin/avd:avd_hdrs",
        "@com_google_absl//absl/strings",
        "@pixman//:pixman-1",
        "@pixman//:pixman_simd",
    ],
    alwayslink = True,
)

cc_library(
    name = "test-display",
    testonly = True,
    srcs = [
        "test/FakeMultiDisplay.cpp",
        "test/FakePixmanDisplay.cpp",
        "test/PixmanImageGenerator.cpp",
        "test/QemuStubs.c",
    ],
    hdrs = [
        "test/FakeMultiDisplay.h",
        "test/FakePixmanDisplay.h",
        "test/MockDisplay.h",
        "test/PixmanImageGenerator.h",
    ],
    includes = ["test"],
    visibility = ["//visibility:public"],
    deps = [
        ":display",
        ":headers",
        "//external/qemu:libmodule-common",
        "//external/qemu:qemu-headers",
        "@pixman//:pixman-1",
        "@pixman//:pixman_simd",
    ],
)

cc_test(
    name = "display_unittests",
    srcs = [
        "test/DisplayTest.cpp",
        "test/FakeMultiDisplayTest.cpp",
        "test/FakePixmanDisplayTest.cpp",
        "test/PixmanImageGeneratorTest.cpp",
    ],
    includes = ["test"],
    deps = [
        ":display",
        ":test-display",
        "//hardware/generic/goldfish/android/system:googletest_main",
    ],
)
