load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "headers",
    hdrs = [
        "include/android/goldfish/display/Display.h",
        "include/android/goldfish/display/FpsCalculator.h",
        "include/android/goldfish/display/MultiDisplay.h",
        "include/android/goldfish/display/MultiDisplayCallbacks.h",
        "include/android/goldfish/display/PixmanDisplay.h",
        "include/android/goldfish/display/PixmanImagePtr.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//emulator/libs/base",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/time",
    ],
)

cc_library(
    name = "display",
    srcs = [
        "src/android/goldfish/display/Display.cpp",
        "src/android/goldfish/display/MultiDisplay.cpp",
        "src/android/goldfish/display/NullDisplay.h",
        "src/android/goldfish/display/PixmanDisplay.cpp",
        "src/android/goldfish/display/PixmanFrameManager.cpp",
        "src/android/goldfish/display/QemuDisplay.cpp",
        "src/android/goldfish/display/QemuDisplay.h",
        "src/android/goldfish/display/virtio-bridge.c",
        "src/android/goldfish/display/virtio-bridge.h",
    ],
    hdrs = [
        "include/android/goldfish/display/PixmanFrameManager.h",
    ],
    includes = [
        "include",
        "src",
    ],
    linkstatic = False,
    visibility = ["//visibility:public"],
    deps = [
        ":fps_calculator",
        ":headers",
        "//emulator/hal/sensors",
        "//emulator/plugin/avd:avd_hdrs",
        "@abseil-cpp//absl/strings",
        "@pixman//:pixman-1",
        "@pixman//:pixman_simd",
        "@qemu//:qemu-headers",
    ],
    alwayslink = True,
)

cc_library(
    name = "test-display",
    testonly = True,
    srcs = [
        "test/FakeMultiDisplay.cpp",
        "test/FakePixmanDisplay.cpp",
        "test/PixmanImageGenerator.cpp",
        "test/QemuStubs.c",
    ],
    hdrs = [
        "test/FakeMultiDisplay.h",
        "test/FakePixmanDisplay.h",
        "test/ImageGenerationStrategy.h",
        "test/MockDisplay.h",
        "test/PixmanImageGenerator.h",
    ],
    includes = ["test"],
    visibility = ["//visibility:public"],
    deps = [
        ":display",
        ":headers",
        "@pixman//:pixman-1",
        "@pixman//:pixman_simd",
        "@qemu//:qemu-headers",
    ],
)

cc_test(
    name = "display_unittests",
    srcs = [
        "test/DisplayTest.cpp",
        "test/FakeMultiDisplayTest.cpp",
        "test/FakePixmanDisplayTest.cpp",
        "test/FpsCalculatorTest.cpp",
        "test/ImageGenerationStrategyTest.cpp",
        "test/PixmanFrameManagerTest.cpp",
        "test/PixmanImageGeneratorTest.cpp",
    ],
    includes = ["test"],
    deps = [
        ":display",
        ":test-display",
        "//android/async:libuv_event_loop",
        "//android/async:threaded_event_loop",
        "//android/system:googletest_main",
    ],
)

cc_library(
    name = "fps_calculator",
    srcs = ["src/FpsCalculator.cpp"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":headers",
        "//android/system:clock",
        "@abseil-cpp//absl/time",
    ],
)
