package(default_visibility = ["//visibility:public"])

alias(
    name = "adb_service_proto",
    actual = "@aemu//protos/services/adb:adb_service_proto",
)

alias(
    name = "adb_service_cc_proto",
    actual = "@aemu//protos/services/adb:adb_service_cc_proto",
)

alias(
    name = "adb_service_cc_grpc",
    actual = "@aemu//protos/services/adb:adb_service_cc_grpc",
)
