load("@com_github_grpc_grpc//bazel:cc_grpc_library.bzl", "cc_grpc_library")
load("@com_google_protobuf//bazel:cc_proto_library.bzl", "cc_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

package(default_visibility = ["//hardware/generic/goldfish/emulator/grpc:__subpackages__"])

proto_library(
    name = "emulator_controller_proto",
    srcs = ["emulator_controller.proto"],
    deps = [
        "@com_google_protobuf//:empty_proto",
        "@com_google_protobuf//:wrappers_proto",
    ],
)

cc_proto_library(
    name = "emulator_controller_cc_proto",
    deps = [":emulator_controller_proto"],
)

cc_grpc_library(
    name = "emulator_controller_cc_grpc",
    srcs = [":emulator_controller_proto"],
    grpc_only = True,
    visibility = [
        "//hardware/generic/goldfish/emulator/grpc:__subpackages__",
        "//hardware/generic/goldfish/emulator/plugin/grpc:__subpackages__",
    ],
    deps = [":emulator_controller_cc_proto"],
)
