load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "imaging",
    srcs = [
        "queryInfo.cpp",
        "toVkFormat.cpp",
    ],
    hdrs = [
        "include/goldfish/imaging/AndroidPixelFormat.h",
        "include/goldfish/imaging/ImageFormat.h",
        "include/goldfish/imaging/ImageRef.h",
        "include/goldfish/imaging/Rect.h",
        "include/goldfish/imaging/queryInfo.h",
        "include/goldfish/imaging/toVkFormat.h",
    ],
    includes = ["include"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "@vulkan-headers//:vulkan_headers",
    ],
    alwayslink = True,
)

cc_test(
    name = "imaging_unittests",
    srcs = [
        "test/queryInfo_unittests.cpp",
        "test/toVkFormat_unittests.cpp",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":imaging",
        "//android/system:googletest_main",
    ],
)
