load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "imaging",
    srcs = [
        "query_info.cc",
        "to_vk_format.cc",
    ],
    hdrs = [
        "include/goldfish/imaging/android_pixel_format.h",
        "include/goldfish/imaging/image_ref.h",
        "include/goldfish/imaging/query_info.h",
        "include/goldfish/imaging/rect.h",
        "include/goldfish/imaging/to_vk_format.h",
        "include/image_format.h",
    ],
    includes = ["include"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "@vulkan-headers//:vulkan_headers",
    ],
    alwayslink = True,
)

cc_test(
    name = "imaging_unittests",
    srcs = [
        "query_info_tests.cc",
        "to_vk_format_tests.cc",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":imaging",
        "//android/system:googletest_main",
    ],
)
