load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "virtio-input-android",
    srcs = [
        "src/virtio-input-android.c",
        "src/virtio-input-android.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//hardware/generic/goldfish/android/logging:absl-c-bridge",
        "//third_party/qemu:libmodule-common",
        "//third_party/qemu:qemu-headers",
        "@pixman//:pixman-1",
    ],
    alwayslink = True,
)
