load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "virtio-input-android",
    srcs = [
        "virtio_input_android.c",
        "virtio_input_android_internal.h",
    ],
    hdrs = ["include/goldfish/input/virtio_input_android.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//android/logging:absl_c_bridge",
        "//emulator/libs/base:array_size",
        "@pixman//:pixman-1",
        "@qemu//:qemu-headers",
    ],
    alwayslink = True,
)
