load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "virtio-input-android",
    srcs = [
        "virtio-input-android.c",
        "virtio-input-android-internal.h",
    ],
    hdrs = ["include/goldfish/input/virtio-input-android.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//hardware/generic/goldfish/android/logging:absl-c-bridge",
        "//third_party/qemu:libmodule-common",
        "//third_party/qemu:qemu-headers",
        "@pixman//:pixman-1",
    ],
    alwayslink = True,
)
