load("@goldfish_build//rules:clang_tidy.bzl", "clang_tidy_test")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "async",
    hdrs = [
        "include/android/emulation/control/generic_callback_functions.h",
        "include/android/emulation/control/library.h",
        "include/android/grpc/utils/enum_translate.h",
        "include/android/grpc/utils/simple_async_grpc.h",
        "include/android/grpc/utils/sync_to_async_adapter.h",
    ],
    includes = ["include"],
    deps = ["@grpc//:grpc++"],
)

cc_test(
    name = "async_library_test",
    srcs = ["library_test.cc"],
    visibility = ["//visibility:public"],
    deps = [
        ":async",
        "//android/system:googletest_main",
        "@googletest//:gtest",
    ],
)

clang_tidy_test(
    name = "tidy",
    targets = [
        ":async_library_test",
    ],
    tidy_config_file = "//:clang_tidy_config",
)
