load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

package(default_visibility = ["//emulator/grpc:__subpackages__"])

cc_library(
    name = "async",
    hdrs = [
        "include/android/emulation/control/utils/generic_callback_functions.h",
        "include/android/emulation/control/utils/library.h",
        "include/android/grpc/utils/enum_translate.h",
        "include/android/grpc/utils/simple_async_grpc.h",
        "include/android/grpc/utils/sync_to_async_adapter.h",
    ],
    includes = ["include"],
    deps = ["@grpc//:grpc++"],
)

cc_test(
    name = "async_library_test",
    srcs = ["test/android/emulation/control/utils/library_test.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        ":async",
        "//android/system:googletest_main",
        "@googletest//:gtest",
    ],
)
