load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "user_data_drive",
    srcs = ["user_data_drive.cpp"],
    hdrs = ["user_data_drive.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//hardware/generic/goldfish/android/filesystems",
        "//hardware/generic/goldfish/emulator/adb/secrets",
        "//hardware/generic/goldfish/emulator/config:config_dirs",
        "//hardware/generic/goldfish/emulator/launcher:device",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@aemu//base:aemu-base",
    ],
)

cc_library(
    name = "disk_drive",
    srcs = ["disk_drive.cpp"],
    hdrs = ["disk_drive.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//hardware/generic/goldfish/android/filesystems",
        "//hardware/generic/goldfish/emulator/launcher:device",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@aemu//base:aemu-base",
    ],
)

cc_test(
    name = "disk_drive_test",
    srcs = ["disk_drive_test.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        ":disk_drive",
        "//hardware/generic/goldfish/android/system:googletest_main",
        "//hardware/generic/goldfish/android/system:test-headers",
        "//hardware/generic/goldfish/emulator/launcher/src/android/goldfish/devices:fake_emulator",
        "@abseil-cpp//absl/status:status_matchers",
        "@abseil-cpp//absl/strings",
    ],
)

cc_library(
    name = "configure_drives",
    srcs = ["configure_drives.cpp"],
    hdrs = ["configure_drives.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":disk_drive",
        ":user_data_drive",
        "//hardware/generic/goldfish/android/filesystems",
        "//hardware/generic/goldfish/emulator/launcher:device",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@aemu//base:aemu-base",
    ],
)

cc_test(
    name = "configure_drives_test",
    srcs = ["configure_drives_test.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        ":configure_drives",
        "//hardware/generic/goldfish/android/system:googletest_main",
        "//hardware/generic/goldfish/android/system:test-headers",
        "//hardware/generic/goldfish/emulator/launcher/src/android/goldfish/devices:mock_avd",
        "@abseil-cpp//absl/status:status_matchers",
        "@abseil-cpp//absl/strings",
    ],
)
