load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "looper",
    srcs = [
        "src/android/base/async/DefaultLooper.cpp",
        "src/android/base/async/Looper.cpp",
        "src/android/base/async/ScopedSocketWatch.cpp",
        "src/android/base/async/SocketWaiter.cpp",
        "src/android/base/async/ThreadLooper.cpp",
        "src/android/utils/assert.h",
        "src/android/utils/looper.cpp",
    ],
    hdrs = [
        "include/android/utils/looper.h",
    ],
    copts =
        select({
            "@platforms//os:windows": ["-Wno-microsoft-goto"],
            "//conditions:default": [],
        }),
    defines = ["__STDC_LIMIT_MACROS"],
    includes = [
        "include",
        "src",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//hardware/generic/goldfish/android/sockets",
        "//hardware/generic/goldfish/android/system",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:check",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
        "@aemu//base:aemu-base",
    ],
)

cc_test(
    name = "looper_unittests",
    srcs = [
        "test/ScopedSocket_unittest.cpp",
        "test/SocketWaiter_unittest.cpp",
        "test/android/utils/Looper_unittest.cpp",
    ],
    linkopts = select({
        "@platforms//os:macos": ["-undefined error"],
        "//conditions:default": [],
    }),
    deps = [
        ":looper",
        "//hardware/generic/goldfish/android/logging:backend",
        "//hardware/generic/goldfish/android/memory",
        "//hardware/generic/goldfish/android/sockets",
        "//hardware/generic/goldfish/android/system:googletest_main",
        "//hardware/generic/goldfish/android/system:test-headers",
        "//hardware/generic/goldfish/android/threads",
    ],
)
