load("@rules_python//python:defs.bzl", "py_binary")
load("@rules_shell//shell:sh_test.bzl", "sh_test")

py_binary(
    name = "download_android_resource",
    srcs = ["download_android_resource.py"],
    main = "download_android_resource.py",
    visibility = ["//visibility:__pkg__"],
)

sh_test(
    name = "sdk_test",
    srcs = ["sdk_test.sh"],
    # This will be the root of our image.
    args = ["$(location @android_36_playstore_x64//:phone)"],
    data = [
        "@android_36_playstore_x64//:avd",
        "@android_36_playstore_x64//:phone",
        "@android_36_playstore_x64//:system_image",
    ],
)
