"""Bazel rules for downloading and unpacking Android resources."""

def _system_image_repository_impl(ctx):
    """Implementation for the rule that fetches and prepares a system image repository."""

    # Since we are running during the repository phase we do not yet have a
    # python toolchain configured. Here we are going to grab one from
    # the execution environment
    python_interpreter = ctx.which("python3") or ctx.which("python")
    if not python_interpreter:
        fail("Could not find a python interpreter in the execution environment.")

    # Get the path to the python script source file.
    script_file = ctx.path(ctx.attr._tool)

    output_zip = ctx.path("sysimg.zip")
    args = [
        "sysimg",
        "--api",
        ctx.attr.api,
        "--tag",
        ctx.attr.tag,
        "--abi",
        ctx.attr.abi,
        "--out",
        output_zip,
        "--revision",
        ctx.attr.rev,
    ]

    # Execute the command as "python3 download_android_resource.py [args...]"
    result = ctx.execute([python_interpreter, script_file] + args)

    if result.return_code != 0:
        fail("Failed to download system image: \n" + result.stderr)

    unpacked_dir = "."
    ctx.execute(["unzip", "-o", output_zip, "-d", unpacked_dir])

    build_file_content = """
# This BUILD file is auto-generated by the system_image_repository rule.
package(default_visibility = ["//visibility:public"])
filegroup(
    name = "system_image",
    srcs = glob(["**"]),
)

filegroup(
  name = "avd",
  srcs = [":phone.ini", ":phone.avd/config.ini"]
)


filegroup(
  name = "phone",
  srcs = [":phone.ini"]
)
"""

    phone_content = """
    avd.ini.encoding=UTF-8
    path.rel=avd/phone.avd
    target=android-""" + ctx.attr.api

    phone_config_ini = """
    AvdId = {api}
PlayStore.enabled = true
abi.type = {abi}
avd.ini.displayname = Phone-{api}
avd.ini.encoding = UTF-8
disk.dataPartition.size = 6442450944
fastboot.chosenSnapshotFile =
fastboot.forceChosenSnapshotBoot = no
fastboot.forceColdBoot = no
fastboot.forceFastBoot = yes
hw.accelerometer = yes
hw.arc = false
hw.audioInput = yes
hw.battery = yes
hw.camera.back = virtualscene
hw.camera.front = emulated
hw.cpu.arch = {abi}
hw.cpu.ncore = 4
hw.dPad = no
hw.device.hash2 = MD5:90973dc6b682b7344df33a6250481866
hw.device.manufacturer = Google
hw.device.name = pixel_8
hw.gps = yes
hw.gpu.enabled = yes
hw.gpu.mode = auto
hw.initialOrientation = portrait
hw.keyboard = yes
hw.lcd.density = 420
hw.lcd.height = 2400
hw.lcd.width = 1080
hw.mainKeys = no
hw.ramSize = 2048
hw.sdCard = yes
hw.sensors.orientation = yes
hw.sensors.proximity = yes
hw.trackBall = no
image.sysdir.1 = {abi}/
runtime.network.latency = none
runtime.network.speed = full
sdcard.size = 512M
showDeviceFrame = yes
tag.display = {tag}
tag.displaynames = {tag}
tag.id = {tag}
tag.ids = {tag}
vm.heapSize = 256
    """.format(tag = ctx.attr.tag, abi = ctx.attr.abi, api = ctx.attr.api)

    ctx.file("BUILD.bazel", content = build_file_content)
    ctx.file("WORKSPACE", content = "")
    ctx.file("phone.ini", content = phone_content)
    ctx.file("phone.avd/config.ini", content = phone_config_ini)

system_image_repository = repository_rule(
    implementation = _system_image_repository_impl,
    attrs = {
        "api": attr.string(mandatory = True),
        "tag": attr.string(mandatory = True),
        "abi": attr.string(mandatory = True),
        "rev": attr.string(mandatory = True),
        # Note: The tool is a source file, not an executable target.
        "_tool": attr.label(
            default = Label("//emulator/sdk/system_images:download_android_resource.py"),
            allow_single_file = True,
        ),
    },
)

def _system_image_extension_impl(ctx):
    """Implementation of the system_image module extension."""

    for module_ctx in ctx.modules:
        # Loop through each `system_image.declare` tag from the MODULE.bazel file
        for tag in module_ctx.tags.image:
            # For each tag, instantiate our repository rule.
            system_image_repository(
                name = tag.name,
                api = tag.api,
                tag = tag.tag,
                abi = tag.abi,
                rev = tag.rev,
            )

#
# Images can be created by:
#
# system_image_ext.image(
#    name = "android_36_playstore_x64",
#    api = "36",
#    tag = "google_apis_playstore",
#    abi = "x86_64",
#    rev = "6",
# )
#
# use_repo(system_image_ext, "android_36_playstore_x64"
#
image_tag = tag_class(attrs = {
    "name": attr.string(mandatory = True),
    "api": attr.string(mandatory = True),
    "tag": attr.string(mandatory = True),
    "abi": attr.string(mandatory = True),
    "rev": attr.string(mandatory = True),
})

system_image_extension = module_extension(
    implementation = _system_image_extension_impl,
    tag_classes = {"image": image_tag},
)
