load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "vm_lock",
    srcs = [
        "vm_lock.cc",
        "vm_lock.h",
    ],
    includes = ["src"],
    deps = [
        "@abseil-cpp//absl/synchronization",
        "@qemu//:qemu-headers",
    ],
)

cc_library(
    name = "machine_info",
    srcs = ["qemu_machine_info.c"],
    hdrs = ["src/vm/qemu_machine_info.h"],
    includes = ["src"],
    visibility = ["//visibility:public"],
    deps = ["@qemu//:qemu-headers"],
)

cc_library(
    name = "fake_machine_info",
    srcs = ["fake_machine_info.c"],
    hdrs = ["src/vm/qemu_machine_info.h"],
    includes = ["src"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "vminterface",
    hdrs = ["include/android/goldfish/vm_interface.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = ["@abseil-cpp//absl/strings:str_format"],
)

cc_library(
    name = "vm_ops",
    srcs = ["qemu_vm_operations.cc"],
    visibility = ["//visibility:public"],
    deps = [
        ":machine_info",
        ":vm_lock",
        ":vminterface",
        "@qemu//:qemu-headers",
    ],
)

cc_library(
    name = "vm_ops_with_fake_machine_info",
    srcs = ["qemu_vm_operations.cc"],
    visibility = ["//visibility:public"],
    deps = [
        ":fake_machine_info",
        ":vm_lock",
        ":vminterface",
    ],
)

cc_library(
    name = "vminterface-test",
    testonly = True,
    srcs = [
        "test/TestVmLock.h",
        "test/vm_mock.h",
        "test_vm_lock.cc",
        "vm_mock.c",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":vm_lock",
        ":vm_ops_with_fake_machine_info",
        ":vminterface",
        "@abseil-cpp//absl/synchronization",
    ],
)

cc_test(
    name = "vminterface_unittests",
    testonly = True,
    srcs = ["vm_test.cc"],
    includes = ["test"],
    visibility = ["//visibility:public"],
    deps = [
        ":vminterface-test",
        "//android/system:googletest_main",
        "//android/system:test-headers",
    ],
)

cc_library(
    name = "test_vminterface",
    testonly = True,
    hdrs = ["test/FakeVmOperations.h"],
    includes = ["test"],
    visibility = ["//visibility:public"],
    deps = [":vminterface"],
)
