load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")
load("//emulator/tools:plugins.bzl", "collect_plugins")

cc_library(
    name = "vm_lock",
    srcs = [
        "vm_lock.cc",
        "vm_lock.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@abseil-cpp//absl/synchronization",
        "@qemu//:qemu-headers-exported",
    ],
)

cc_library(
    name = "machine_info",
    srcs = [
        "qemu_machine_info.c",
        "qemu_machine_info.h",
    ],
    visibility = ["//visibility:public"],
    deps = ["@qemu//:qemu-headers-exported"],
)

cc_library(
    name = "fake_machine_info",
    srcs = [
        "fake_machine_info.c",
        "qemu_machine_info.h",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "vminterface",
    hdrs = ["include/android/goldfish/vm_interface.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = ["@abseil-cpp//absl/strings:str_format"],
)

cc_library(
    name = "vm_ops",
    srcs = ["qemu_vm_operations.cc"],
    visibility = ["//visibility:public"],
    deps = [
        ":machine_info",
        ":vm_lock",
        ":vminterface",
        "@abseil-cpp//absl/status",
        "@qemu//:qemu-headers-exported",
    ],
)

cc_library(
    name = "vm_ops_with_fake_machine_info",
    srcs = ["qemu_vm_operations.cc"],
    visibility = ["//visibility:public"],
    deps = [
        ":fake_machine_info",
        ":vm_lock",
        ":vminterface",
        "@abseil-cpp//absl/status",
    ],
)

cc_library(
    name = "vminterface-test",
    testonly = True,
    srcs = [
        "test/test_vm_lock.h",
        "test/vm_mock.h",
        "test_vm_lock.cc",
        "vm_mock.c",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":vm_lock",
        ":vm_ops_with_fake_machine_info",
        ":vminterface",
        "@abseil-cpp//absl/synchronization",
    ],
)

collect_plugins(
    name = "binplace",
    output_dir = ".",
    plugins = [
        "@glib//glib:glib_shared",
        "@glib//gmodule:gmodule_shared",
    ],
)

cc_test(
    name = "vminterface_unittests",
    testonly = True,
    srcs = ["vm_test.cc"],
    data = [":binplace"],
    dynamic_deps = [
        "@glib//glib:glib_shared",
        "@glib//gmodule:gmodule_shared",
    ],
    includes = ["test"],
    visibility = ["//visibility:public"],
    deps = [
        ":vminterface-test",
        "//emulator/libs/system:test-headers",
        "//emulator/libs/test:googletest_main",
        "@glib//glib:glib_import",
        "@glib//gmodule:gmodule_import",
    ],
)

cc_library(
    name = "test_vminterface",
    testonly = True,
    hdrs = ["test/fake_vm_operations.h"],
    includes = ["test"],
    visibility = ["//visibility:public"],
    deps = [":vminterface"],
)
