load("@goldfish_build//rules:clang_tidy.bzl", "clang_tidy_test")
load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

# It's an older code sir but it checks out
cc_library(
    name = "file_system_watcher",
    srcs = ["file_system_watcher.cc"] + select({
        "@platforms//os:windows": ["file_system_watcher_windows.cc"],
        "@platforms//os:macos": ["file_system_watcher_darwin.cc"],
        "@platforms//os:linux": ["file_system_watcher_posix.cc"],
    }),
    hdrs = ["include/android/base/file_system_watcher.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//android/system",
        "//emulator/libs/base",
        "//emulator/libs/process",
        "@abseil-cpp//absl/synchronization",
    ] + select({
        "@platforms//os:windows": ["//android/system:win32_utils"],
        "//conditions:default": [],
    }),
)

cc_test(
    name = "file_system_watcher_test",
    size = "medium",
    srcs = ["file_system_watcher_test.cc"],
    visibility = ["//visibility:public"],
    deps = [
        ":file_system_watcher",
        "//android/system",
        "//android/system:googletest_main",
        "//android/system:test-headers",
        "//emulator/libs/base",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/random",
    ],
)

cc_library(
    name = "ini_file",
    srcs = ["ini_file.cc"],
    hdrs = ["include/android/goldfish/ini_file.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = ["//android/system"],
)

cc_test(
    name = "ini_file_test",
    size = "medium",
    srcs = ["ini_file_test.cc"],
    visibility = ["//visibility:public"],
    deps = [
        ":ini_file",
        "//android/system",
        "//android/system:googletest_main",
        "//android/system:test-headers",
        "@abseil-cpp//absl/log",
    ],
)

clang_tidy_test(
    name = "tidy",
    targets = [
        ":file_system_watcher",
        ":ini_file",
    ],
    tidy_config_file = "//:clang_tidy_config",
)
