load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

# It's an older code sir but it checks out
cc_library(
    name = "files",
    srcs = [
        "src/aemu/base/files/FileShareOpen.cpp",
        "src/aemu/base/files/FileSystemWatcher.cpp",
        "src/aemu/base/files/IniFile.cpp",
    ] + select({
        "@platforms//os:windows": ["src/aemu/base/files/FileSystemWatcherWindows.cpp"],
        "@platforms//os:macos": ["src/aemu/base/files/FileSystemWatcherDarwin.cpp"],
        "@platforms//os:linux": ["src/aemu/base/files/FileSystemWatcherPosix.cpp"],
    }),
    hdrs = [
        "include/aemu/base/files/FileSystemWatcher.h",
        "include/aemu/base/files/IniFile.h",
    ],
    defines = [
        "__STDC_LIMIT_MACROS=1",
        "__STDC_FORMAT_MACROS=1",
    ],
    includes = [
        "include",
        "src",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//android/logging:absl-c-bridge",
        "//android/process",
        "//android/system",
        "@aemu//base:aemu-base",
    ] + select({
        "@platforms//os:windows": [
            "//android/windows/posix:compat",
        ],
        "//conditions:default": [],
    }),
)

cc_test(
    name = "files_unittests",
    size = "medium",
    srcs = [
        "test/FileSystemWatcher_unittest.cpp",
        "test/aemu/base/files/FileShareOpen_unittest.cpp",
        "test/aemu/base/files/IniFile_unittest.cpp",
    ],
    includes = ["test"],
    linkopts = select({
        "@platforms//os:macos": ["-undefined error"],
        "//conditions:default": [],
    }),
    deps = [
        ":files",
        "//android/logging:backend",
        "//android/system",
        "//android/system:googletest_main",
        "//android/system:test-headers",
        "@abseil-cpp//absl/log",
        "@aemu//base:aemu-base",
    ] + select({
        "@platforms//os:windows": [
            "//android/windows/posix:compat",
        ],
        "//conditions:default": [],
    }),
)
