load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

# It's an older code sir but it checks out
cc_library(
    name = "files",
    srcs = [
        "src/aemu/base/files/FileShareOpen.cpp",
        "src/aemu/base/files/FileSystemWatcher.cpp",
        "src/aemu/base/files/IniFile.cpp",
        "src/android/utils/assert.h",
        "src/android/utils/bufprint.c",
        "src/android/utils/bufprint.h",
        "src/android/utils/bufprint_system.cpp",
        "src/android/utils/dirscanner.cpp",
        "src/android/utils/dirscanner.h",
        "src/android/utils/dll.c",
        "src/android/utils/file_data.c",
        "src/android/utils/filelock.cpp",
        "src/android/utils/lock.cpp",
        "src/android/utils/lock.h",
        "src/android/utils/path.cpp",
        "src/android/utils/path.h",
        "src/android/utils/path_system.cpp",
        "src/android/utils/system.c",
        "src/android/utils/tempfile.c",
    ] + select({
        "@platforms//os:windows": ["src/aemu/base/files/FileSystemWatcherWindows.cpp"],
        "@platforms//os:macos": ["src/aemu/base/files/FileSystemWatcherDarwin.cpp"],
        "@platforms//os:linux": ["src/aemu/base/files/FileSystemWatcherPosix.cpp"],
    }),
    hdrs = [
        "include/aemu/base/files/IniFile.h",
        "include/android/utils/dll.h",
        "include/android/utils/file_data.h",
        "include/android/utils/filelock.h",
        "include/android/utils/system.h",
        "include/android/utils/tempfile.h",
    ],
    defines = [
        "__STDC_LIMIT_MACROS=1",
        "__STDC_FORMAT_MACROS=1",
    ],
    includes = [
        "include",
        "src",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//hardware/generic/goldfish/android/logging:absl-c-bridge",
        "//hardware/generic/goldfish/android/process",
        "//hardware/generic/goldfish/android/system",
        "@aemu//base:aemu-base",
    ] + select({
        "@platforms//os:windows": [
            "//hardware/generic/goldfish/android/windows/posix:compat",
        ],
        "//conditions:default": [],
    }),
)

cc_test(
    name = "files_unittests",
    size = "small",
    srcs = [
        "test/aemu/base/files/FileShareOpen_unittest.cpp",
        "test/aemu/base/files/IniFile_unittest.cpp",
        "test/android/utils/bufprint_system.cpp",
        "test/android/utils/bufprint_unittest.cpp",
        "test/android/utils/custom_gmain.cpp",
        "test/android/utils/dirscanner_unittest.cpp",
        "test/android/utils/file_data_unittest.cpp",
        "test/android/utils/filelock_test.h",
        "test/android/utils/filelock_unittest.cpp",
        "test/android/utils/tempfile_unittest.cpp",
    ],
    includes = ["test"],
    linkopts = select({
        "@platforms//os:macos": ["-undefined error"],
        "//conditions:default": [],
    }),
    deps = [
        ":files",
        "//hardware/generic/goldfish/android/logging:backend",
        "//hardware/generic/goldfish/android/system",
        "//hardware/generic/goldfish/android/system:test-headers",
        "@aemu//base:aemu-base",
        "@com_google_absl//absl/log",
        "@com_google_googletest//:gtest",
    ] + select({
        "@platforms//os:windows": [
            "//hardware/generic/goldfish/android/windows/posix:compat",
        ],
        "//conditions:default": [],
    }),
)
