cc_library(
    name = "files",
    srcs = glob([
        "src/android/**/*.cpp",
        "src/**/*.h",
    ]),
    hdrs = glob([
        "include/android/goldfish/*.h",
        "include/android/goldfish/avd/*.h",
    ]),
    includes = [
        "include",
        "src",
    ],
    # linkopts = ["-undefined error"],
    visibility = ["//visibility:public"],
    deps = [
        "//hardware/generic/goldfish/logging:backend",
        "//hardware/generic/goldfish/system",
        "//hardware/google/aemu/base:aemu-base",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings",
        "@com_google_absl//absl/strings:str_format",
    ],
)

cc_test(
    name = "files_unittests",
    srcs = glob(
        [
            "test/**/*.cpp",
            "test/include/**/*.h",
        ],
        exclude = ["test/**/Win32"],
    ),
    linkopts = ["-undefined error"],
    deps = [
        ":files",
        "//hardware/generic/goldfish/logging:backend",
        "//hardware/generic/goldfish/system:test-headers",
        "@com_google_googletest//:gtest_main",
    ],
)
