load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "webcam",
    srcs = [
        "webcam.cc",
    ],
    hdrs = [
        "include/android/camera/image_providers/webcam.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//emulator/plugin/hal/camera:image_provider_api",
        "@abseil-cpp//absl/log",
    ],
    alwayslink = True,
)

cc_test(
    name = "webcam_unittests",
    srcs = [
        "todo.cc",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":webcam",
        "//emulator/libs/test:googletest_main",
    ],
)
