load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "guest-status",
    srcs = [
        "src/misc/GuestStatusDevice.cpp",
    ],
    hdrs = [
        "include/android/misc/GuestStatusDevice.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//android/async:async_api",
        "//android/system",
        "//emulator/hal/common:emulator_reset",
        "//emulator/hal/connector:connector_registry",
        "//emulator/hal/connector:qemud",
        "//emulator/libs/avd_universe:guest_status",
        "//emulator/plugin/vminterface",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:check",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
        "@abseil-cpp//absl/synchronization",
        "@aemu//base:aemu-base",
        "@aemu//base:event-support",
    ],
    alwayslink = True,
)

cc_test(
    name = "guest-status_unittests",
    srcs = [
        "test/misc/GuestStatusDevice_unittest.cpp",
    ],
    includes = ["test"],
    visibility = ["//visibility:public"],
    deps = [
        ":guest-status",
        "//android/async:async_testing",
        "//android/system:googletest_main",
        "//android/system:test-headers",
        "//emulator/hal/connector:test-helpers",
        "//emulator/hal/plug:fake_vsock",
        "//emulator/plugin/vminterface:vminterface-test",
    ],
)
