cc_library(
    name = "headers",
    hdrs = [
        "include/android/misc/GuestStatusDevice.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//hardware/generic/goldfish/emulator/devices:connector_registry_hdrs",
        "@com_google_absl//absl/log",
        "@com_google_absl//absl/log:check",
        "@com_google_absl//absl/strings",
        "@com_google_absl//absl/strings:str_format",
    ],
)

cc_library(
    name = "guest-status",
    srcs = [
        "src/misc/GuestStatusDevice.cpp",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":headers",
        "//hardware/generic/goldfish/android/event-support",
        "//hardware/generic/goldfish/android/system",
        "//hardware/generic/goldfish/emulator/config",
        "//hardware/generic/goldfish/emulator/devices:PingTopic",
        "//hardware/generic/goldfish/emulator/devices:cable",
        "//hardware/generic/goldfish/emulator/devices:qemud",
        "//hardware/google/aemu/base:aemu-base",
        "@com_google_absl//absl/log",
        "@com_google_absl//absl/log:check",
        "@com_google_absl//absl/strings",
        "@com_google_absl//absl/strings:str_format",
        "@com_google_absl//absl/synchronization",
    ],
    alwayslink = True,
)

cc_test(
    name = "guest-status_unittests",
    srcs = [
        "test/misc/GuestStatusDevice_unittest.cpp",
    ],
    includes = ["test"],
    deps = [
        ":guest-status",
        "//hardware/generic/goldfish/android/system:test-headers",
        "//hardware/generic/goldfish/emulator/config:avd-test",
        "//hardware/generic/goldfish/emulator/devices:test-socket",
        "//hardware/google/aemu:aemu-host-common-test-headers",
        "//hardware/google/aemu/base:aemu-base",
        "//hardware/google/aemu/base:aemu-base-headers",
        "//hardware/google/aemu/base:test-matchers",
        "@com_google_googletest//:gtest_main",
        "@com_google_protobuf//:protobuf",
    ],
)
