load("@goldfish_build//rules:clang_tidy.bzl", "clang_tidy_test")
load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "emulator-access",
    srcs = ["data/emulator_access.json"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "unsecure-emulator-access",
    srcs = ["testdata/test_allow_list.json"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "grpc_security",
    srcs = [
        "allow_list.cc",
        "auth_error_factory.cc",
        "basic_token_auth.cc",
        "jwk_directory_observer.cc",
        "jwk_key_loader.cc",
        "jwt_token_auth.cc",
    ],
    hdrs = [
        "include/android/emulation/control/allow_list.h",
        "include/android/emulation/control/auth_error_factory.h",
        "include/android/emulation/control/basic_token_auth.h",
        "include/android/emulation/control/jwk_directory_observer.h",
        "include/android/emulation/control/jwk_key_loader.h",
        "include/android/emulation/control/jwt_token_auth.h",
    ],
    includes = ["include"],
    deps = [
        "//emulator/libs/file_system_watcher",
        "//emulator/libs/grpc_utils:async",
        "//emulator/libs/system",
        "@grpc//:grpc++",
        "@nlohmann_json//:singleheader-json",
        "@re2",
        "@tink_cc//tink:tink_cc",
        "@tink_cc//tink/jwt:jwk_set_converter",
        "@tink_cc//tink/jwt:jwt_public_key_verify",
        "@tink_cc//tink/jwt:jwt_signature_config",
    ],
)

cc_test(
    name = "grpc_security_test",
    size = "small",
    timeout = "short",
    srcs = [
        "allow_list_test.cc",
        "auth_error_factory_test.cc",
        "jwk_directory_observer_test.cc",
        "jwk_key_loader_test.cc",
        "jwt_token_auth_test.cc",
    ],
    copts = ["-Wno-deprecated-declarations"],
    data = [":emulator-access"],
    visibility = ["//visibility:public"],
    deps = [
        ":grpc_security",
        "//emulator/libs/system",
        "//emulator/libs/system:test-headers",
        "//emulator/libs/test:googletest_main",
        "@abseil-cpp//absl/status:status_matchers",
        "@googletest//:gtest",
        "@tink_cc//tink/jwt:jwt_key_templates",
    ],
)

clang_tidy_test(
    name = "tidy",
    targets = [
        ":grpc_security",
        ":grpc_security_test",
    ],
    tidy_config_file = "//:clang_tidy_config",
)
