package(default_visibility = ["//hardware/generic/goldfish/emulator/grpc:__subpackages__"])

test_suite(
    name = "grpc-unit-tests",
    tests = [
        "//hardware/generic/goldfish/emulator/grpc/async:async_library_test",
        "//hardware/generic/goldfish/emulator/grpc/interceptors:interceptors_test",
        "//hardware/generic/goldfish/emulator/grpc/security:security-test",
    ],
    visibility = ["//visibility:public"],
)
