load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "emulator_catalog",
    srcs = ["emulator_catalog.cc"],
    hdrs = ["include/goldfish/emulator_catalog.h"],
    includes = ["include"],
    deps = [
        "//android/files",
        "//emulator/config:config_dirs",
        "//emulator/config:emulator_advertisement",
        "@abseil-cpp//absl/strings",
        "@aemu//base:aemu-base",
        "@aemu//base:event-support",
    ],
)

cc_test(
    name = "emulator_catalog_unittest",
    srcs = ["emulator_catalog_test.cc"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":emulator_catalog",
        "//android/system:googletest_main",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
        "@aemu//base:aemu-base",
        "@aemu//base:event-support",
    ],
)
