load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "keyconversion",
    srcs = [
        "src/KeyConversion.cpp",
        "src/dom_key.h",
        "src/dom_key_data.inc",
        "src/keycode_converter_data.inc",
    ],
    hdrs = [
        "include/android/emulation/control/keyboard/key_conversion.h",
    ],
    includes = [
        "include",
        "src",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//hardware/generic/goldfish/android/async:async_api",
        "//third_party/qemu:qemu-headers",
    ],
)

cc_library(
    name = "keyboard",
    srcs = [
        "src/KeyEventSender.cpp",
    ],
    hdrs = [
        "include/android/emulation/control/keyboard/KeyEventSender.h",
    ],
    includes = [
        "include",
        "src",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":keyconversion",
        "//hardware/generic/goldfish/android/async:async_api",
        "//hardware/generic/goldfish/emulator/grpc/services/emulator_controller/proto:emulator_controller_cc_grpc",
        "//third_party/qemu:qemu-headers",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@aemu//base:aemu-base",
    ],
)

cc_test(
    name = "keyboard_unittests",
    srcs = ["test/key_converter_unittest.cpp"],
    deps = [
        ":keyconversion",
        "//hardware/generic/goldfish/android/system:googletest_main",
        "//hardware/generic/goldfish/android/system:test-headers",
    ],
)
