load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "clipboard",
    hdrs = ["include/goldfish/avd_universe/clipboard/clipboard_data.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = ["//emulator/libs/eventing"],
)

cc_library(
    name = "fingerprint",
    hdrs = ["include/goldfish/avd_universe/fingerprint/fingerprint_sensor.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = ["//emulator/libs/eventing"],
)

cc_library(
    name = "grpc_notification",
    hdrs = ["include/goldfish/avd_universe/grpc/grpc_notification_channel.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//emulator/libs/eventing",
        "@aemu//protos/services/emulator-controller:emulator_controller_cc_grpc",
    ],
)

cc_library(
    name = "guest_status",
    srcs = ["guest_status.cc"],
    hdrs = ["include/goldfish/avd_universe/guest_status/guest_status.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//emulator/libs/archive:time",
        "//emulator/libs/eventing",
        "@abseil-cpp//absl/time",
    ],
)

cc_library(
    name = "location",
    srcs = ["location.cc"],
    hdrs = ["include/goldfish/avd_universe/gps/location.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = ["//emulator/libs/eventing"],
)

cc_library(
    name = "battery",
    srcs = ["battery_state.cc"],
    hdrs = [
        "include/goldfish/avd_universe/battery/battery_state.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//emulator/libs/archive",
        "//emulator/libs/eventing",
        "//emulator/libs/status_macros",
        "@abseil-cpp//absl/strings:str_format",
    ],
)

cc_library(
    name = "avd_universe",
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":battery",
        ":clipboard",
        ":fingerprint",
        ":grpc_notification",
        ":guest_status",
        ":location",
    ],
)
