load("@goldfish_build//rules:clang_tidy.bzl", "clang_tidy_test")
load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "snapshottable",
    hdrs = [
        "include/goldfish/snapshottable/snapshottable.h",
    ],
    includes = ["include"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//emulator/libs/archive",
        "@abseil-cpp//absl/status",
    ],
)

clang_tidy_test(
    name = "tidy",
    targets = [
        ":snapshottable",
    ],
    tidy_config_file = "//:clang_tidy_config",
)
