package(default_visibility = ["//visibility:public"])

alias(
    name = "emulator_controller_proto",
    actual = "@aemu//protos/services/emulator-controller:emulator_controller_proto",
)

alias(
    name = "emulator_controller_cc_proto",
    actual = "@aemu//protos/services/emulator-controller:emulator_controller_cc_proto",
)

alias(
    name = "emulator_controller_cc_grpc",
    actual = "@aemu//protos/services/emulator-controller:emulator_controller_cc_grpc",
)
