load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "gvk",
    srcs = [
        "build_device_queue_create_info.cc",
        "device_dispatch.cc",
        "device_resources.cc",
        "get_memory_type_index.cc",
        "include/goldfish/gvk/goldfish_gvk_populate_member_pfn_visitor.h",
        "include/goldfish/gvk/util/get_pfn.h",
        "include/goldfish/gvk/util/init_pfn.h",
        "instance_dispatch.cc",
        "log_vk_result.cc",
        "select_physical_device.cc",
        "staging_buffers.cc",
        "system_meta_loader.cc",
    ],
    hdrs = [
        "include/goldfish/gvk/device_dispatch.h",
        "include/goldfish/gvk/device_queue_location.h",
        "include/goldfish/gvk/device_resources.h",
        "include/goldfish/gvk/goldfish/gvk/util/staging_buffers.h",
        "include/goldfish/gvk/i_meta_loader.h",
        "include/goldfish/gvk/instance_dispatch.h",
        "include/goldfish/gvk/system_meta_loader.h",
        "include/goldfish/gvk/util/build_device_queue_create_info.h",
        "include/goldfish/gvk/util/get_memory_type_index.h",
        "include/goldfish/gvk/util/log_vk_result.h",
        "include/goldfish/gvk/util/select_physical_device.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//emulator/libs/base:array_size",
        "//emulator/libs/debug",
        "//emulator/libs/os",
        "@abseil-cpp//absl/log",
        "@vulkan-headers//:vulkan_headers",
    ],
    alwayslink = True,
)

cc_test(
    name = "gvk_unittests",
    srcs = [
        "build_device_queue_create_info_test.cc",
        "get_memory_type_index_test.cc",
    ],
    includes = ["test"],
    visibility = ["//visibility:public"],
    deps = [
        ":gvk",
        "//android/system:googletest_main",
        "@gfxstream//third_party/glm",
    ],
)
