load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")

cc_library(
    name = "process",
    srcs = [
        "command.cc",
        "exec.cc",
        "exec.h",
    ] + select({
        "@platforms//os:windows": [
            "command_windows.cc",
        ],
        "//conditions:default": [
            "command_posix.cc",
        ],
    }),
    copts = select({
        "@platforms//os:windows": [
            "-Wno-vla-cxx-extension",
        ],
        "//conditions:default": [],
    }),
    includes = ["src"],
    visibility = ["//visibility:public"],
    deps = select({
        "@platforms//os:windows": [
            "//android/system",
        ],
        "//conditions:default": [],
    }) + [
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@aemu//base:aemu-base",
    ],
)

cc_binary(
    name = "sleep_emu",
    srcs = ["sleep.cc"],
    deps = [
        "@abseil-cpp//absl/flags:flag",
        "@abseil-cpp//absl/flags:parse",
    ],
)

cc_test(
    name = "process_unittests",
    srcs = ["command_test.cc"],
    data = [":sleep_emu"],
    linkopts = select({
        "@platforms//os:macos": ["-undefined error"],
        "//conditions:default": [],
    }),
    visibility = ["//visibility:public"],
    deps = [
        ":process",
        "//android/files",
        "//android/system",
        "//android/system:googletest_main",
        "//android/system:test-headers",
        "@abseil-cpp//absl/flags:flag",
        "@abseil-cpp//absl/flags:parse",
    ],
)
