cc_library(
    name = "process",
    srcs = [
        "src/android/base/process/Command.cpp",
        "src/android/base/process/exec.cpp",
        "src/android/base/process/exec.h",
    ] + select({
        "@platforms//os:windows": [
            "src/android/base/process/Command_Windows.cpp",
        ],
        "//conditions:default": [
            "src/android/base/process/Command_Posix.cpp",
        ],
    }),
    copts = select({
        "@platforms//os:windows": [
            "-Wno-vla-cxx-extension",
        ],
        "//conditions:default": [],
    }),
    includes = ["src"],
    visibility = ["//visibility:public"],
    deps = [
        "//hardware/generic/goldfish/android/streams",
        "//hardware/google/aemu/base:aemu-base",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings",
    ] + select({
        "@platforms//os:windows": [
            "//hardware/generic/goldfish/android/windows/posix:compat",
        ],
        "//conditions:default": [],
    }),
)

cc_binary(
    name = "sleep_emu",
    srcs = ["test/android/base/process/sleep.cpp"],
    deps = [
        "@com_google_absl//absl/flags:flag",
        "@com_google_absl//absl/flags:parse",
    ],
)

cc_test(
    name = "process_unittests",
    srcs = glob(
        [
            "test/**/*_unittest.cpp",
            "test/include/**/*.h",
        ],
        exclude = ["test/**/Win32"],
    ),
    data = [":sleep_emu"],
    linkopts = select({
        "@platforms//os:macos": ["-undefined error"],
        "//conditions:default": [],
    }),
    deps = [
        ":process",
        "//hardware/generic/goldfish/android/files",
        "//hardware/generic/goldfish/android/logging:backend",
        "//hardware/generic/goldfish/android/system:test-headers",
        "@bazel_tools//tools/cpp/runfiles",
        "@com_google_absl//absl/flags:flag",
        "@com_google_absl//absl/flags:parse",
        "@com_google_googletest//:gtest_main",
    ],
)
