load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")

cc_library(
    name = "process",
    srcs = [
        "src/android/base/process/Command.cpp",
        "src/android/base/process/exec.cpp",
        "src/android/base/process/exec.h",
    ] + select({
        "@platforms//os:windows": [
            "src/android/base/process/Command_Windows.cpp",
        ],
        "//conditions:default": [
            "src/android/base/process/Command_Posix.cpp",
        ],
    }),
    copts = select({
        "@platforms//os:windows": [
            "-Wno-vla-cxx-extension",
        ],
        "//conditions:default": [],
    }),
    includes = ["src"],
    visibility = ["//visibility:public"],
    deps = [
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@aemu//base:aemu-base",
    ] + select({
        "@platforms//os:windows": [
            "//hardware/generic/goldfish/android/windows/posix:compat",
        ],
        "//conditions:default": [],
    }),
)

cc_binary(
    name = "sleep_emu",
    srcs = ["test/android/base/process/sleep.cpp"],
    deps = [
        "@abseil-cpp//absl/flags:flag",
        "@abseil-cpp//absl/flags:parse",
    ],
)

cc_test(
    name = "process_unittests",
    srcs = ["test/android/base/process/Command_unittest.cpp"],
    data = [":sleep_emu"],
    linkopts = select({
        "@platforms//os:macos": ["-undefined error"],
        "//conditions:default": [],
    }),
    deps = [
        ":process",
        "//hardware/generic/goldfish/android/files",
        "//hardware/generic/goldfish/android/logging:backend",
        "//hardware/generic/goldfish/android/system:googletest_main",
        "//hardware/generic/goldfish/android/system:test-headers",
        "@abseil-cpp//absl/flags:flag",
        "@abseil-cpp//absl/flags:parse",
        "@bazel_tools//tools/cpp/runfiles",
    ],
)
