test_suite(
    name = "hal_unittests",
    tests = [
        "//hardware/generic/goldfish/emulator/hal/bootproperties:bootproperties_unittests",
        "//hardware/generic/goldfish/emulator/hal/camera:camera_unittests",
        "//hardware/generic/goldfish/emulator/hal/clipboard:clipboard_unittests",
        "//hardware/generic/goldfish/emulator/hal/display:display_unittests",
        "//hardware/generic/goldfish/emulator/hal/fingerprint:fingerprint_unittests",
        "//hardware/generic/goldfish/emulator/hal/gps:gps_unittests",
        "//hardware/generic/goldfish/emulator/hal/guest-status:guest-status_unittests",
        "//hardware/generic/goldfish/emulator/hal/plug:hal_plug_adapter_unittests",
        "//hardware/generic/goldfish/emulator/hal/sensors:sensors_unittests",
        "//hardware/generic/goldfish/emulator/hal/vminterface:vminterface_unittests",
    ],
)
