load("@goldfish_build//rules:clang_tidy.bzl", "clang_tidy_test")

clang_tidy_test(
    name = "tidy",
    tags = ["manual"],
    targets = [
        # "//emulator/libs/QEMUBH:QEMUBH",
        "//emulator/libs/SocketBuffer:SocketBuffer",
        "//emulator/libs/UniqueIdAllocator:UniqueIdAllocator",
        "//emulator/libs/archive:DequeArchive",
        "//emulator/libs/archive:QEMUFileArchive",
        "//emulator/libs/archive:archive",
        "//emulator/libs/archive:zigzag",
        # "//emulator/libs/avd_universe:avd_universe",
        # "//emulator/libs/avd_universe:clipboard",
        # "//emulator/libs/avd_universe:fingerprint",
        # "//emulator/libs/avd_universe:grpc_notification",
        # "//emulator/libs/avd_universe:guest_status",
        # "//emulator/libs/avd_universe:location",
        "//emulator/libs/base:base",
        "//emulator/libs/broadcasting:broadcasting",
        "//emulator/libs/debug:debug",
        # "//emulator/libs/display:base",
        # "//emulator/libs/display:display",
        # "//emulator/libs/display:test-display",
        # "//emulator/libs/eventing:eventing",
        "//emulator/libs/fps_calculator:fps_calculator",
        # "//emulator/libs/gvk:gvk",
        # "//emulator/libs/imaging:imaging",
        # "//emulator/libs/network:network",
        "//emulator/libs/os:os",
        # "//emulator/libs/parsing:parsing",
        # "//emulator/libs/physics:glm_helpers",
        # "//emulator/libs/physics:physics",
        # "//emulator/libs/sensors:physical_model",
    ],
    tidy_config_file = "//:clang_tidy_config",
)
