test_suite(
    name = "libs_unittests",
    tests = [
        "//hardware/generic/goldfish/emulator/libs/SocketBuffer:SocketBuffer_unittests",
        "//hardware/generic/goldfish/emulator/libs/UniqueIdAllocator:UniqueIdAllocator_unittests",
        "//hardware/generic/goldfish/emulator/libs/archive:archive_unittests",
        "//hardware/generic/goldfish/emulator/libs/broadcasting:broadcasting_unittests",
        "//hardware/generic/goldfish/emulator/libs/imaging:imaging_unittests",
        "//hardware/generic/goldfish/emulator/libs/parsing:parsing_unittests",
    ],
)
