load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//hardware/generic/goldfish/emulator/android-grpc:__subpackages__"])

cc_library(
    name = "adb-service",
    srcs = ["src/android/emulation/control/adb/AdbService.cpp"],
    hdrs = ["include/android/emulation/control/adb/AdbService.h"],
    includes = ["include"],
    deps = [
        "//hardware/generic/goldfish/emulator/adb/secrets",
        "//hardware/generic/goldfish/emulator/android-grpc/async",
        "//hardware/generic/goldfish/emulator/android-grpc/services/adb/proto:adb_service_cc_grpc",
        "@aemu//base:aemu-base",
    ],
)
