load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "netsim_transport",
    srcs = ["netsim_transport.cc"],
    hdrs = ["NetsimTransport.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//emulator/grpc/client:emulator_grpc_client",
        "//emulator/plugin/avd:impl",
        "//emulator/tools:aemu_version",
        "@abseil-cpp//absl/log",
        "@grpc//:grpc++",
        "@netsim//:netsimd_cc_grpc",
        "@qemu//:qemu-headers",
    ],
)

cc_library(
    name = "netsim-netdev",
    srcs = ["netsim_netdev.cc"],
    hdrs = ["include/goldfish/netsim/netsim_netdev.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":netsim_transport",
        "//emulator/libs/network",
        "@abseil-cpp//absl/log",
        "@qemu//:qemu-headers",
    ],
)

cc_library(
    name = "netsim-chardev",
    srcs = [
        "h4_parser.cc",
        "h4_parser.h",
        "netsim_chardev.cc",
    ],
    hdrs = ["include/goldfish/netsim/netsim_chardev.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":netsim_transport",
        "@abseil-cpp//absl/log",
        "@qemu//:qemu-headers",
    ],
)
