load("@goldfish_build//rules:clang_tidy.bzl", "clang_tidy_test")
load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test", "objc_library")

cc_library(
    name = "clock",
    srcs = [
        "abseil_clock.cc",
        "clock.cc",
    ],
    hdrs = [
        "include/android/base/abseil_clock.h",
        "include/android/base/clock.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/time",
    ],
)

cc_library(
    name = "eintr_wrapper",
    hdrs = ["include/android/base/eintr_wrapper.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = ["@abseil-cpp//absl/log"],
)

objc_library(
    name = "system-darwin",
    srcs = ["system-native-mac.mm"],
    copts = ["-std=c++20"],
    sdk_frameworks = [
        "IOKit",
        "AppKit",
    ],
    target_compatible_with = [
        "@platforms//os:macos",
    ],
    alwayslink = True,
)

cc_library(
    name = "system",
    srcs = ["system.cc"],
    hdrs = [
        "include/android/base/c_str_wrapper.h",
        "include/android/base/cpu_time.h",
        "include/android/base/memory.h",
        "include/android/base/no_sigalarm.h",
        "include/android/base/system.h",
        "include/android/utils/compiler.h",
    ],
    includes = ["include"],
    linkopts = select({
        "@platforms//os:windows": [
            "-DEFAULTLIB:Shell32.lib",
            "-DEFAULTLIB:User32.lib",
        ],
        "//conditions:default": [],
    }),
    tags = ["no-tidy"],
    visibility = ["//visibility:public"],
    deps = [
        ":clock",
        ":eintr_wrapper",
        "//emulator/libs/file",
        "//emulator/libs/process",
        "@abseil-cpp//absl/algorithm:container",
        "@abseil-cpp//absl/base",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings:str_format",
        "@bazel_tools//tools/cpp/runfiles",
    ] + select({
        "@platforms//os:windows": [
            "//emulator/libs/windows:scoped_reg_key",
            "//emulator/libs/windows:win32_utils",
            "@aemu//windows:compat",
            "@glib//glib/dirent",
        ],
        "@platforms//os:macos": [
            ":system-darwin",
        ],
        "//conditions:default": [],
    }),
)

cc_library(
    name = "bazel_info",
    srcs = ["bazel_info.cc"],
    hdrs = ["include/android/base/bazel_info.h"],
    implementation_deps = [":system"],
    includes = ["include"],
    tags = ["no-tidy"],
    visibility = ["//visibility:public"],
    deps = [
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings:str_format",
        "@bazel_tools//tools/cpp/runfiles",
    ],
)

cc_library(
    name = "test-headers",
    testonly = True,
    srcs = ["test_file_util_bazel.cc"],
    hdrs = [
        "test-headers/android/base/testing/TestClock.h",
        "test-headers/android/base/testing/TestSystem.h",
        "test-headers/android/base/testing/TestTempDir.h",
        "test-headers/android/base/testing/TestThread.h",
        "test-headers/android/base/testing/needs_winsock.h",
        "test-headers/android/base/testing/test_event.h",
        "test-headers/android/base/testing/test_file_util.h",
    ],
    includes = ["test-headers"],
    visibility = ["//visibility:public"],
    deps = [
        ":system",
        "@abseil-cpp//absl/log:absl_log",
        "@abseil-cpp//absl/strings",
        "@bazel_tools//tools/cpp/runfiles",
    ],
)

cc_test(
    name = "system_test",
    srcs = ["system_test.cc"],
    visibility = ["//visibility:public"],
    deps = [
        ":system",
        ":test-headers",
        "//emulator/libs/test:googletest_main",
        "@abseil-cpp//absl/status:status_matchers",
    ],
)

cc_test(
    name = "bazel_info_test",
    srcs = ["bazel_info_test.cc"],
    data = ["testdata/info.txt"],
    visibility = ["//visibility:public"],
    deps = [
        ":bazel_info",
        ":test-headers",
        "//emulator/libs/test:googletest_main",
        "@abseil-cpp//absl/status:status_matchers",
    ],
)

cc_binary(
    name = "clock_perf",
    testonly = True,
    srcs = ["bm_clock.cc"],
    copts = [
        "-Wno-deprecated-declarations",
        "-Wno-unused-result",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":clock",
        ":system",
        "@google_benchmark//:benchmark",
    ],
)

clang_tidy_test(
    name = "tidy",
    targets = [
    ],
    tidy_config_file = "//:clang_tidy_config",
)
