load("@goldfish_build//rules:clang_tidy.bzl", "clang_tidy_test")
load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")

cc_library(
    name = "color_log_sink",
    srcs = ["color_log_sink.cc"],
    hdrs = ["include/android/base/color_log_sink.h"],
    includes = ["include"],
    local_defines = ["LOGGING_API_SHARED"],
    visibility = ["//visibility:public"],
    deps = [
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:globals",
        "@abseil-cpp//absl/log:initialize",
        "@abseil-cpp//absl/log:log_sink_registry",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
    ],
)

cc_test(
    name = "color_log_sink_test",
    srcs = ["color_log_sink_test.cc"],
    copts = ["-Wno-deprecated-declarations"],
    visibility = ["//visibility:public"],
    deps = [
        ":color_log_sink",
        "//emulator/libs/test:googletest_main",
    ],
)

cc_library(
    name = "absl_c_bridge",
    srcs = ["abseil_log_bridge.cc"],
    hdrs = ["include/android/base/logging/abseil_log_bridge.h"],
    includes = ["include"],
    local_defines = ["LOGGING_API_SHARED"],
    visibility = ["//visibility:public"],
    deps = [
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:absl_log",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
    ],
)

cc_test(
    name = "absl_c_bridge_test",
    srcs = [
        "abseil_log_bridge_test.c",
        "abseil_log_bridge_test.cc",
        "abseil_log_bridge_test2.c",
        "test/android/base/logging/abseil_log_c_test.h",
    ],
    copts = ["-Wno-deprecated-declarations"],
    visibility = ["//visibility:public"],
    deps = [
        ":absl_c_bridge",
        "//emulator/libs/test:googletest_main",
    ],
)

cc_binary(
    name = "log_bridge_perf",
    srcs = ["abseil_log_bridge_perf.cc"],
    copts = ["-Wno-deprecated-declarations"],
    visibility = ["//visibility:public"],
    deps = [
        ":absl_c_bridge",
        "@google_benchmark//:benchmark",
    ],
)

clang_tidy_test(
    name = "tidy",
    targets = [
        ":color_log_sink",
        ":absl_c_bridge",
    ],
    tidy_config_file = "//:clang_tidy_config",
)
