load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "parsing",
    srcs = [
        "getKeyValueStr.cpp",
        "split2.cpp",
    ],
    hdrs = [
        "include/goldfish/parsing/fromChars.h",
        "include/goldfish/parsing/getKeyValueStr.h",
        "include/goldfish/parsing/split2.h",
    ],
    includes = ["include"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "@abseil-cpp//absl/strings",
    ],
)

cc_test(
    name = "parsing_unittests",
    size = "small",
    srcs = [
        "test/getKeyValueStr_test.cpp",
        "test/split2_test.cpp",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":parsing",
        "//android/system:googletest_main",
    ],
)
