load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "parsing",
    srcs = [
        "arg_stream.cc",
        "get_key_value_str.cc",
        "split2.cc",
    ],
    hdrs = [
        "include/goldfish/parsing/arg_stream.h",
        "include/goldfish/parsing/from_chars.h",
        "include/goldfish/parsing/get_key_value_str.h",
        "include/goldfish/parsing/parameter_binder.h",
        "include/goldfish/parsing/split2.h",
    ],
    includes = ["include"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:check",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
    ],
)

cc_test(
    name = "parsing_unittests",
    size = "small",
    srcs = [
        "arg_stream_test.cc",
        "get_key_value_str_test.cc",
        "parameter_binder_test.cc",
        "split2_test.cc",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":parsing",
        "//emulator/libs/test:googletest_main",
    ],
)
