load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")

cc_library(
    name = "init",
    srcs = ["src/android/crashreport/CrashSytemInit.cpp"],
    hdrs = [
        "include/android/crashreport/CrashConsent.h",
        "include/android/crashreport/CrashSystem.h",
        "include/android/crashreport/crash-initializer.h",
    ],
    data = ["@com_google_crashpad//handler:crashpad_handler"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":always_consent",
        ":crash_reporter",
        ":uploader",
        "//hardware/generic/goldfish/android/process",
        "@com_google_crashpad//client",
        "@com_google_crashpad//handler",
        "@com_google_crashpad//snapshot",
    ],
)

cc_library(
    name = "hang_detector",
    srcs = ["src/android/crashreport/HangDetector.cpp"],
    hdrs = ["include/android/crashreport/HangDetector.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//hardware/generic/goldfish/android/async:async_api",
        "//hardware/generic/goldfish/android/system",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/strings",
    ],
)

cc_library(
    name = "crash_reporter",
    srcs = [
        "include/android/crashreport/AnnotationStreambuf.h",
        "include/android/crashreport/SimpleStringAnnotation.h",
        "include/android/crashreport/crash-handler.h",
        "src/android/crashreport/CrashReporter.cpp",
    ],
    hdrs = ["include/android/crashreport/CrashReporter.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":hang_detector",
        "//hardware/generic/goldfish/android/system",
        "//hardware/generic/goldfish/emulator/tools:aemu_version",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/strings",
        "@aemu//base:aemu-base",
        "@com_google_crashpad//client",
        "@com_google_crashpad//handler",
        "@com_google_crashpad//snapshot",
        "@com_google_crashpad//third_party/mini_chromium:base",
    ],
)

cc_library(
    name = "breadcrumb",
    srcs = [
        "include/android/crashreport/AnnotationCircularStreambuf.h",
        "src/android/crashreport/Breadcrumb.cpp",
    ],
    hdrs = [
        "include/android/crashreport/Breadcrumb.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/strings",
        "@com_google_crashpad//client",
    ],
)

cc_library(
    name = "detectors",
    srcs = [
        "src/android/crashreport/detectors/CrashDetectors.cpp",
        "src/android/crashreport/detectors/TimeoutMonitor.cpp",
    ],
    hdrs = [
        "include/android/crashreport/detectors/CrashDetectors.h",
        "include/android/crashreport/detectors/TimeoutMonitor.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":crash_reporter",
        ":hang_detector",
        "//hardware/generic/goldfish/android/system",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/strings",
        "@aemu//base:aemu-base",
    ],
)

cc_library(
    name = "uploader",
    srcs = [
        "include/android/crashreport/Uploader.h",
        "src/android/crashreport/CrashUploader.cpp",
    ],
    defines = ["AEMU_CRASH_SHARED"],
    includes = ["include"],
    local_defines = ["AEMU_CRASH_EXPORTS"],
    visibility = ["//hardware/generic/goldfish/emulator/crashreport/tool:__subpackages__"],
    deps = [
        ":always_consent",
        "@com_google_crashpad//client",
        "@com_google_crashpad//handler",
        "@com_google_crashpad//snapshot",
    ],
)

cc_library(
    name = "always_consent",
    srcs = ["src/android/crashreport/CrashConsentAlways.cpp"],
    hdrs = [
        "include/android/crashreport/CrashConsent.h",
        "include/android/crashreport/crash-export.h",
    ],
    defines = ["AEMU_CRASH_SHARED"],
    includes = ["include"],
    local_defines = ["AEMU_CRASH_EXPORTS"],
    visibility = ["//hardware/generic/goldfish/emulator/crashreport/tool:__subpackages__"],
    deps = [
        "@abseil-cpp//absl/log",
        "@com_google_crashpad//client",
    ],
)

alias(
    name = "crashreport",
    actual = "//hardware/generic/goldfish/emulator/crashreport/tool:crashreport",
    visibility = ["//visibility:public"],
)

cc_test(
    name = "crashreport_test",
    srcs = [
        "test/android/crashreport/AnnotationBuffer_unittest.cpp",
        "test/android/crashreport/CrashDump_unittest.cpp",
        # Disabled until the hangdetector is migrated to the new event loop
        # See b/444728681
        # "test/android/crashreport/HangDetector_unittest.cpp",
        "test/android/crashreport/detectors/CrashDetectors_unittest.cpp",
        "test/android/crashreport/detectors/TimeoutMonitor_unittest.cpp",
    ],
    data = [
        ":crash-me",
        "@com_google_crashpad//handler:crashpad_handler",
    ],
    linkopts = select({
        "@platforms//os:macos": ["-undefined error"],
        "//conditions:default": [],
    }),
    deps = [
        ":always_consent",
        ":breadcrumb",
        ":detectors",
        ":init",
        "//hardware/generic/goldfish/android/system",
        "//hardware/generic/goldfish/android/system:googletest_main",
        "//hardware/generic/goldfish/android/system:test-headers",
        "@abseil-cpp//absl/strings",
        "@aemu//base:aemu-base",
        "@com_google_breakpad//src/processor",
        "@com_google_crashpad//client",
    ],
)

cc_binary(
    name = "crash-me",
    srcs = [
        "test/android/crashreport/testing/main-test-crasher.cpp",
    ],
    data = ["@com_google_crashpad//handler:crashpad_handler"],
    linkopts = select({
        "@platforms//os:macos": ["-undefined error"],
        "//conditions:default": [],
    }),
    deps = [
        ":always_consent",
        ":breadcrumb",
        ":init",
        "@abseil-cpp//absl/flags:flag",
        "@abseil-cpp//absl/flags:parse",
        "@abseil-cpp//absl/log:initialize",
    ],
)
