load("@goldfish_build//rules:clang_tidy.bzl", "clang_tidy_test")
load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")

config_setting(
    name = "opt",
    values = {"compilation_mode": "opt"},
)

# Select crash report upload URL based on build type. Staging URL is used by default,
# and production URL is used for release (opt) builds.
CRASHURL_DEFINES = select({
    ":opt": [
        'CRASHURL=\\"https://clients2.google.com/cr/report\\"',
    ],
    "//conditions:default": [
        'CRASHURL=\\"https://clients2.google.com/cr/staging_report\\"',
    ],
})

cc_library(
    name = "debug",
    srcs = ["debug.cc"],
    hdrs = ["debug.h"],
    deps = ["//emulator/libs/base:array_size"],
)

cc_library(
    name = "hang_detector",
    srcs = ["hang_detector.cc"],
    hdrs = ["include/android/crashreport/hang_detector.h"],
    includes = ["include"],
    deps = [
        ":debug",
        "//android/async:async_api",
        "//android/system",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/strings",
    ],
)

cc_test(
    name = "hang_detector_test",
    size = "small",
    srcs = ["hang_detector_test.cc"],
    deps = [
        ":debug",
        ":hang_detector",
        "//android/async:async_testing",
        "//android/async:libuv_event_loop",
        "//android/async:threaded_event_loop",
        "//android/system:googletest_main",
        "//android/system:test-headers",
        "@abseil-cpp//absl/status:status_matchers",
        "@abseil-cpp//absl/strings",
    ],
)

cc_library(
    name = "crash_uploader",
    srcs = ["crash_uploader.cc"],
    hdrs = ["include/android/crashreport/crash_uploader.h"],
    includes = ["include"],
    local_defines = CRASHURL_DEFINES,
    visibility = ["//emulator/crashreport:__subpackages__"],
    deps = [
        "@crashpad//client",
        "@crashpad//handler",
        "@crashpad//snapshot",
    ],
)

cc_library(
    name = "crash_reporter",
    srcs = [
        "annotation_streambuf.h",
        "crash_reporter.cc",
        "simple_string_annotation.h",
    ],
    hdrs = ["include/android/crashreport/crash_reporter.h"],
    includes = ["include"],
    visibility = ["//emulator/plugin:__subpackages__"],
    deps = [
        ":hang_detector",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/strings",
        "@crashpad//client",
        "@crashpad//handler",
        "@crashpad//snapshot",
        "@crashpad//third_party/mini_chromium:base",
    ],
)

cc_library(
    name = "crash_system",
    srcs = ["crash_system.cc"],
    hdrs = ["include/android/crashreport/crash_system.h"],
    data = ["@crashpad//handler:crashpad_handler"],
    includes = ["include"],
    local_defines = CRASHURL_DEFINES,
    visibility = ["//visibility:public"],
    deps = [
        ":crash_reporter",
        ":crash_uploader",
        "//android/system",
        "//emulator/tools:aemu_version",
        "@crashpad//client",
        "@crashpad//handler",
        "@crashpad//snapshot",
    ],
)

cc_library(
    name = "breadcrumb",
    srcs = [
        "annotation_circular_streambuf.h",
        "breadcrumb.cc",
    ],
    hdrs = ["include/android/crashreport/breadcrumb.h"],
    includes = ["include"],
    deps = [
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/strings",
        "@crashpad//client",
    ],
)

cc_library(
    name = "detectors",
    srcs = [
        "crash_detectors.cc",
        "timeout_monitor.cc",
    ],
    hdrs = [
        "include/android/crashreport/crash_detectors.h",
        "include/android/crashreport/timeout_monitor.h",
    ],
    includes = ["include"],
    deps = [
        ":crash_reporter",
        ":hang_detector",
        "//android/system",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/strings",
    ],
)

alias(
    name = "crashreport",
    actual = "//emulator/crashreport/tool:crashreport",
    visibility = ["//visibility:public"],
)

cc_test(
    name = "crashreport_test",
    srcs = [
        "annotation_buffer_test.cc",
        "crash_detectors_test.cc",
        "crash_dump_test.cc",
        "timeout_monitor_test.cc",
    ],
    data = [
        ":crash-me",
        "@crashpad//handler:crashpad_handler",
    ],
    linkopts = select({
        "@platforms//os:macos": ["-undefined error"],
        "//conditions:default": [],
    }),
    visibility = ["//visibility:public"],
    deps = [
        ":breadcrumb",
        ":crash_system",
        ":detectors",
        "//android/process",
        "//android/system",
        "//android/system:googletest_main",
        "//android/system:test-headers",
        "@abseil-cpp//absl/strings",
        "@breakpad//src/processor",
        "@crashpad//client",
    ],
)

cc_binary(
    name = "crash-me",
    srcs = ["main_test_crasher.cc"],
    data = ["@crashpad//handler:crashpad_handler"],
    linkopts = select({
        "@platforms//os:macos": ["-undefined error"],
        "//conditions:default": [],
    }),
    visibility = ["//visibility:public"],
    deps = [
        ":breadcrumb",
        ":crash_system",
        "//android/process",
        "@abseil-cpp//absl/flags:flag",
        "@abseil-cpp//absl/flags:parse",
        "@abseil-cpp//absl/log:initialize",
    ],
)

clang_tidy_test(
    name = "tidy",
    targets = [
        "hang_detector",
        "crash_reporter",
        "breadcrumb",
        "crash_system",
    ],
    tidy_config_file = "//:clang_tidy_config",
)
