load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "SocketBuffer",
    srcs = [
        "socket_buffer.cc",
    ],
    hdrs = [
        "include/goldfish/socket_buffer.h",
    ],
    includes = ["include"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//emulator/libs/archive",
        "//emulator/libs/debug",
    ],
)

cc_test(
    name = "SocketBuffer_unittests",
    size = "small",
    srcs = [
        "socket_buffer_tests.cc",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":SocketBuffer",
        "//emulator/libs/archive:DequeArchive",
        "//emulator/libs/test:googletest_main",
    ],
)
