load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "sensors",
    srcs = ["sensor_device.cc"],
    hdrs = ["include/android/base/goldfish/devices/sensor/sensor_device.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//emulator/hal/connector:connector_registry",
        "//emulator/hal/connector:qemud",
        "//emulator/hal/plug:hal_plug",
        "//emulator/libs/eventing",
        "//emulator/libs/hardware_config",
        "//emulator/libs/hardware_config:device_type",
        "//emulator/libs/physics",
        "//emulator/libs/sensors:physical_model",
        "//emulator/libs/system",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:check",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
        "@gfxstream//third_party/glm",
    ],
    alwayslink = True,
)

cc_test(
    name = "sensors_unittests",
    srcs = ["sensor_device_test.cc"],
    includes = ["test"],
    visibility = ["//visibility:public"],
    deps = [
        ":sensors",
        "//emulator/hal/connector:test-helpers",
        "//emulator/hal/plug:fake_vsock",
        "//emulator/libs/hardware_config:fake_hardware_config",
        "//emulator/libs/system:test-headers",
        "//emulator/libs/test:googletest_main",
    ],
)
