load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "sensors",
    srcs = [
        "FoldableModel.cpp",
        "PhysicalModel.cpp",
        "SensorDevice.cpp",
        "include/goldfish/devices/sensor/AndroidSensor.h",
        "include/goldfish/devices/sensor/Foldable.h",
        "include/goldfish/devices/sensor/FoldableModel.h",
        "include/goldfish/devices/sensor/GOLDFISH_PHYSICAL_PARAMETERS_LIST.h",
        "include/goldfish/devices/sensor/GOLDFISH_SENSORS_LIST.h",
        "include/goldfish/devices/sensor/PhysicalModel.h",
        "include/goldfish/devices/sensor/PhysicalParameter.h",
        "include/goldfish/devices/sensor/Sensors.h",
    ],
    hdrs = [
        "include/goldfish/devices/sensor/SensorDevice.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//hardware/generic/goldfish/android/logging:absl-c-bridge",
        "//hardware/generic/goldfish/android/system",
        "//hardware/generic/goldfish/emulator/config:device_type",
        "//hardware/generic/goldfish/emulator/config:hardware_config",
        "//hardware/generic/goldfish/emulator/hal/connector:connector_registry_hdrs",
        "//hardware/generic/goldfish/emulator/hal/connector:qemud",
        "//hardware/generic/goldfish/emulator/hal/plug:hal_plug",
        "//hardware/generic/goldfish/emulator/libs/physics",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:check",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
        "@aemu//base:aemu-base",
        "@aemu//base:event-support",
        "@gfxstream//third_party/glm",
    ],
    alwayslink = True,
)

cc_test(
    name = "sensors_unittests",
    srcs = [
        "test/physics/PhysicalModel_unittest.cpp",
        "test/physics/SensorDevice_unittest.cpp",
    ],
    includes = ["test"],
    deps = [
        ":sensors",
        "//hardware/generic/goldfish/android/system:googletest_main",
        "//hardware/generic/goldfish/android/system:test-headers",
        "//hardware/generic/goldfish/emulator/config:avd-test",
        "//hardware/generic/goldfish/emulator/hal/connector:test-helpers",
        "//hardware/generic/goldfish/emulator/hal/plug:fake_vsock",
    ],
)

cc_library(
    name = "test_sensors",
    hdrs = [
        "test/FakeSensorDevice.h",
    ],
    includes = ["test"],
    visibility = ["//visibility:public"],
    deps = [
        ":sensors",
    ],
)
