load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "sensors",
    srcs = [
        "include/android/physics/Foldable.h",
        "include/android/physics/FoldableModel.h",
        "include/android/physics/PhysicalModel.h",
        "include/android/physics/SensorDevice.h",
        "include/android/physics/Sensors.h",
        "src/physics/FoldableModel.cpp",
        "src/physics/PhysicalModel.cpp",
        "src/physics/SensorDevice.cpp",
    ],
    hdrs = [
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//hardware/generic/goldfish/android/event-support",
        "//hardware/generic/goldfish/android/logging:absl-c-bridge",
        "//hardware/generic/goldfish/android/system",
        "//hardware/generic/goldfish/emulator/agents",
        "//hardware/generic/goldfish/emulator/config",
        "//hardware/generic/goldfish/emulator/devices:PingTopic",
        "//hardware/generic/goldfish/emulator/devices:cable",
        "//hardware/generic/goldfish/emulator/devices:connector_registry_hdrs",
        "//hardware/generic/goldfish/emulator/devices:qemud",
        "//hardware/generic/goldfish/emulator/libs/physics",
        "@aemu//base:aemu-base",
        "@com_google_absl//absl/log",
        "@com_google_absl//absl/log:check",
        "@com_google_absl//absl/strings",
        "@com_google_absl//absl/strings:str_format",
        "@gfxstream//third_party/glm",
    ],
    alwayslink = True,
)

cc_test(
    name = "sensors_unittests",
    srcs = [
        "test/physics/PhysicalModel_unittest.cpp",
        "test/physics/SensorDevice_unittest.cpp",
    ],
    includes = ["test"],
    deps = [
        ":sensors",
        "//hardware/generic/goldfish/android/system:googletest_main",
        "//hardware/generic/goldfish/android/system:test-headers",
        "//hardware/generic/goldfish/emulator/config:avd-test",
        "//hardware/generic/goldfish/emulator/devices:test-socket",
        "@aemu//:aemu-host-common-test-headers",
        "@aemu//base:aemu-base",
        "@aemu//base:aemu-base-headers",
        "@com_google_protobuf//:protobuf",
    ],
)
