load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")

cc_library(
    name = "absl-c-bridge",
    srcs = [
        "src/android/base/logging/AbseilLogBridge.cpp",
    ],
    hdrs = ["include/android/base/logging/AbseilLogBridge.h"],
    includes = ["include"],
    local_defines = ["LOGGING_API_SHARED"],
    visibility = ["//visibility:public"],
    deps = [
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:absl_log",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
    ] + select({
        "@platforms//os:windows": [
            "//android/windows/posix:compat",
        ],
        "//conditions:default": [],
    }),
)

cc_library(
    name = "backend",
    testonly = True,
    srcs = [
        "src/android/base/logging/AbseilLogBridge.cpp",
        "src/android/base/logging/ColorLogSink.cpp",
        "src/android/base/logging/Log.cpp",
        "src/android/base/logging/LogConfiguration.cpp",
        "src/android/base/logging/LogFormatter.cpp",
    ],
    hdrs = [
        "include/android/base/logging/AbseilLogBridge.h",
        "include/android/base/logging/ColorLogSink.h",
        "include/android/base/logging/LoggingApi.h",
    ],
    includes = ["include"],
    local_defines = ["LOGGING_API_SHARED"],
    visibility = ["//visibility:public"],
    deps = [
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:absl_log",
        "@abseil-cpp//absl/log:globals",
        "@abseil-cpp//absl/log:initialize",
        "@abseil-cpp//absl/log:log_sink_registry",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
        "@aemu//base:aemu-base-logging",
    ] + select({
        "@platforms//os:windows": [
            "//android/windows/posix:compat",
        ],
        "//conditions:default": [],
    }),
)

cc_test(
    name = "backend_unittests",
    srcs = [
        "test/android/base/logging/AbseilLogBridge_unittest.c",
        "test/android/base/logging/AbseilLogBridge_unittest.cpp",
        "test/android/base/logging/AbseilLogBridge_unittest2.c",
        "test/android/base/logging/ColorLogSink_unittest.cpp",
        "test/android/base/logging/LogFormatter_unittest.cpp",
        "test/android/base/logging/Log_unittest.cpp",
        "test/android/base/logging/abseil_log_c_test.h",
    ],
    copts = ["-Wno-deprecated-declarations"],
    linkopts = select({
        "@platforms//os:macos": ["-undefined error"],
        "//conditions:default": [],
    }),
    deps = [
        ":absl-c-bridge",
        ":backend",
        "//android/system:googletest_main",
        "@aemu//base:aemu-base",
    ],
)

cc_binary(
    name = "log_bridge_perf",
    srcs = ["test/android/base/logging/AbseilLogBridge_perf.cpp"],
    copts = ["-Wno-deprecated-declarations"],
    deps = [
        ":absl-c-bridge",
        "@google_benchmark//:benchmark",
    ],
)
