load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "absl-c-bridge",
    srcs = [
        "src/android/base/logging/AbseilLogBridge.cpp",
    ],
    hdrs = ["include/android/base/logging/AbseilLogBridge.h"],
    includes = ["include"],
    local_defines = ["LOGGING_API_SHARED"],
    visibility = ["//visibility:public"],
    deps = [
        "@com_google_absl//absl/log",
        "@com_google_absl//absl/log:absl_log",
        "@com_google_absl//absl/strings",
        "@com_google_absl//absl/strings:str_format",
    ] + select({
        "@platforms//os:windows": [
            "//hardware/generic/goldfish/android/windows/posix:compat",
        ],
        "//conditions:default": [],
    }),
)

cc_library(
    name = "backend",
    testonly = True,
    srcs = [
        "src/android/base/logging/AbseilLogBridge.cpp",
        "src/android/base/logging/ColorLogSink.cpp",
        "src/android/base/logging/Log.cpp",
        "src/android/base/logging/LogConfiguration.cpp",
        "src/android/base/logging/LogFormatter.cpp",
    ],
    hdrs = glob(["include/android/base/logging/*.h"]),
    includes = ["include"],
    local_defines = ["LOGGING_API_SHARED"],
    visibility = ["//visibility:public"],
    deps = [
        "//hardware/google/aemu/base:aemu-base-logging",
        "@com_google_absl//absl/log",
        "@com_google_absl//absl/log:absl_log",
        "@com_google_absl//absl/log:globals",
        "@com_google_absl//absl/log:initialize",
        "@com_google_absl//absl/log:log_sink_registry",
        "@com_google_absl//absl/strings",
        "@com_google_absl//absl/strings:str_format",
    ] + select({
        "@platforms//os:windows": [
            "//hardware/generic/goldfish/android/windows/posix:compat",
        ],
        "//conditions:default": [],
    }),
)

cc_test(
    name = "backend_unittests",
    srcs = [
        "test/android/base/logging/AbseilLogBridge_unittest.c",
        "test/android/base/logging/AbseilLogBridge_unittest.cpp",
        "test/android/base/logging/AbseilLogBridge_unittest2.c",
        "test/android/base/logging/ColorLogSink_unittest.cpp",
        "test/android/base/logging/LogFormatter_unittest.cpp",
        "test/android/base/logging/Log_unittest.cpp",
        "test/android/base/logging/abseil_log_c_test.h",
    ],
    copts = ["-Wno-deprecated-declarations"],
    linkopts = select({
        "@platforms//os:macos": ["-undefined error"],
        "//conditions:default": [],
    }),
    deps = [
        ":absl-c-bridge",
        ":backend",
        "//hardware/google/aemu/base:aemu-base",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "log_bridge_perf",
    size = "small",
    srcs = ["test/android/base/logging/AbseilLogBridge_perf.cpp"],
    copts = ["-Wno-deprecated-declarations"],
    deps = [
        ":absl-c-bridge",
        "@com_github_google_benchmark//:benchmark",
    ],
)
