load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")
load("@rules_python//python:defs.bzl", "py_binary")

py_binary(
    name = "gen-hw-config",
    srcs = ["tools/gen-hw-config.py"],
)

genrule(
    name = "hw-config-gen",
    srcs = ["data/hardware-properties.ini"],
    outs = ["include/avd/hw-config-defs.h"],
    cmd = "$(location :gen-hw-config) $(location data/hardware-properties.ini) $(location include/avd/hw-config-defs.h)",
    tools = [":gen-hw-config"],
)

cc_library(
    name = "hardware_config",
    srcs = [
        "hardware_config.cc",
        "memory_config.cc",
        ":hw-config-gen",
    ],
    hdrs = [
        "include/android/goldfish/hardware_config.h",
        "include/android/goldfish/memory_config.h",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//emulator/libs/host-common",
        "//emulator/libs/ini_file",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/strings",
    ],
)

cc_library(
    name = "fake_hardware_config",
    testonly = True,
    hdrs = ["test/android/goldfish/fake_hardware_config.h"],
    includes = ["test"],
    visibility = ["//visibility:public"],
    deps = [":hardware_config"],
)

cc_library(
    name = "device_type",
    hdrs = ["include/android/goldfish/device_type.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "memory_config_test",
    srcs = ["memory_config_test.cc"],
    deps = [
        ":hardware_config",
        "@abseil-cpp//absl/status",
        "@googletest//:gtest_main",
    ],
)
