cc_library(
    name = "threads",
    srcs = [
        "src/android/base/threads/Async.cpp",
        "src/android/base/threads/FunctorThread.cpp",
        "src/android/base/threads/ThreadStore.cpp",
        "src/android/base/threads/internal/ParallelTaskBase.cpp",
        "src/android/base/threads/internal/ParallelTaskBase.h",
    ],
    hdrs = glob([
        "include/android/utils/*.h",
    ]),
    copts =
        select({
            "@platforms//os:windows": ["-Wno-microsoft-goto"],
            "//conditions:default": [],
        }),
    includes = [
        "include",
        "src",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//hardware/generic/goldfish/android/logging:backend",
        "//hardware/generic/goldfish/android/system",
        "//hardware/google/aemu/base:aemu-base",
        "@com_google_absl//absl/log",
        "@com_google_absl//absl/log:absl_check",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings",
        "@com_google_absl//absl/strings:str_format",
    ],
)

cc_test(
    name = "threads_unittests",
    srcs = glob(
        [
            "test/**/*.cpp",
            "test/**/*.h",
        ],
        exclude = ["test/**/Win32"],
    ),
    linkopts = select({
        "@platforms//os:macos": ["-undefined error"],
        "//conditions:default": [],
    }),
    deps = [
        ":threads",
        "//hardware/generic/goldfish/android/logging:backend",
        "//hardware/generic/goldfish/android/looper",
        "//hardware/generic/goldfish/android/memory",
        "//hardware/generic/goldfish/android/sockets",
        "//hardware/generic/goldfish/android/system:test-headers",
        "@com_google_googletest//:gtest_main",
    ],
)
