load("@rules_license//rules:license.bzl", "license")
load("@rules_license//rules:license_kind.bzl", "license_kind")
load("@rules_python//python:defs.bzl", "py_binary")

package(
    default_applicable_licenses = [":license"],
    default_visibility = ["//visibility:public"],
)

license(
    name = "license",
    license_kinds = [
        ":SPDX-license-identifier-Apache-2.0",
    ],
    license_text = "LICENSE-APACHE",
    visibility = [":__subpackages__"],
)

license_kind(
    name = "SPDX-license-identifier-Apache-2.0",
    conditions = ["notice"],
    url = "https://spdx.org/licenses/Apache-2.0.html",
)

py_binary(
    name = "extract-cc",
    srcs = [
        "src/aemu/converter/apple_converter.py",
        "src/aemu/converter/clang_converter.py",
        "src/aemu/converter/compiler_converter.py",
        "src/aemu/converter/converter.py",
        "src/aemu/filters/argument_filter.py",
        "src/aemu/filters/normalizer.py",
        "src/aemu/log.py",
        "src/aemu/process/bazel.py",
        "src/aemu/process/runner.py",
        "src/extract.py",
    ],
    main = "extract.py",
    visibility = ["//visibility:public"],
)
