load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "socket_utils_impl",
    srcs =
        [
            "src/android/base/sockets/SocketUtils.cpp",
        ],
    copts = select({
        "@platforms//os:windows": [
            "-Wno-microsoft-goto",
            "-Wno-macro-redefined",
        ],
        "//conditions:default": [],
    }),
    includes =
        [
            "include",
            "src",
        ],
    linkopts = select({
        "@platforms//os:windows": [
            "-DEFAULTLIB:Rpcrt4.lib",
            "-DEFAULTLIB:Ws2_32.lib",
        ],
        "//conditions:default": [],
    }),
    visibility = ["//visibility:public"],
    deps =
        [
            "//hardware/generic/goldfish/android/system",
            "@abseil-cpp//absl/log",
            "@abseil-cpp//absl/log:check",
            "@aemu//base:aemu-base",
        ],
)

alias(
    name = "sockets",
    actual = ":socket_utils_impl",
    visibility = ["//visibility:public"],
)

cc_test(
    name = "sockets_unittests",
    srcs = [
        "test/android/base/sockets/SocketUtils_unittest.cpp",
    ],
    linkopts = select({
        "@platforms//os:macos": ["-undefined error"],
        "//conditions:default": [],
    }),
    deps = [
        ":sockets",
        "//hardware/generic/goldfish/android/system:googletest_main",
    ],
)
