load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "sockets",
    srcs =
        [
            "src/android/base/sockets/AsyncSocket.cpp",
            "src/android/base/sockets/AsyncSocketServer.cpp",
            "src/android/base/sockets/AsyncWriter.cpp",
            "src/android/base/sockets/ScopedSocketWatch.cpp",
            "src/android/base/sockets/SocketDrainer.cpp",
            "src/android/base/sockets/SocketUtils.cpp",
            "src/android/base/sockets/SocketWaiter.cpp",
            "src/android/utils/eintr_wrapper.c",
            "src/android/utils/eintr_wrapper.h",
            "src/android/utils/misc.c",
            "src/android/utils/misc.h",
            "src/android/utils/socket_drainer.cpp",
            "src/android/utils/socket_drainer.h",
            "src/android/utils/sockets.c",
            "src/android/utils/sockets.h",
            "src/android/utils/stralloc.c",
            "src/android/utils/stralloc.h",
        ],
    hdrs = glob([
        "include/android/**/*.h",
    ]),
    copts = select({
        "@platforms//os:windows": [
            "-Wno-microsoft-goto",
            "-Wno-macro-redefined",
        ],
        "//conditions:default": [],
    }),
    includes =
        [
            "include",
            "src",
        ],
    linkopts = select({
        "@platforms//os:windows": [
            "-DEFAULTLIB:Rpcrt4.lib",
            "-DEFAULTLIB:Ws2_32.lib",
        ],
        "//conditions:default": [],
    }),
    visibility = ["//visibility:public"],
    deps =
        [
            "//hardware/generic/goldfish/android/files",
            "//hardware/generic/goldfish/android/looper",
            "//hardware/generic/goldfish/android/memory",
            "//hardware/generic/goldfish/android/system",
            "//hardware/generic/goldfish/android/threads",
            "@aemu//base:aemu-base",
            "@com_google_absl//absl/log",
            "@com_google_absl//absl/log:check",
        ],
)

cc_library(
    name = "test-sockets",
    srcs = [
        "test/android/base/sockets/ChecksumSocket.cpp",
        "test/android/base/sockets/SimpleTestServer.cpp",
        "test/android/base/sockets/SimpleThreadLooper.cpp",
    ],
    hdrs = glob(["test/include/android/**/*.h"]),
    includes = ["test/include"],
    visibility = ["//visibility:public"],
    deps = [
        ":sockets",
        "@com_google_absl//absl/log",
        "@com_google_absl//absl/log:check",
    ],
)

cc_test(
    name = "sockets_unittests",
    srcs = glob(
        [
            "test/**/*test.cpp",
            "test/**/*.h",
        ],
        exclude = ["test/**/Win32"],
    ),
    linkopts = select({
        "@platforms//os:macos": ["-undefined error"],
        "//conditions:default": [],
    }),
    deps = [
        ":sockets",
        ":test-sockets",
        "//hardware/generic/goldfish/android/files",
        "//hardware/generic/goldfish/android/logging:backend",
        "//hardware/generic/goldfish/android/looper",
        "//hardware/generic/goldfish/android/memory",
        "//hardware/generic/goldfish/android/system",
        "//hardware/generic/goldfish/android/system:test-headers",
        "//hardware/generic/goldfish/android/threads",
        "@aemu//base:aemu-base",
        "@com_google_absl//absl/log",
        "@com_google_absl//absl/log:absl_check",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "async_socket_perf",
    size = "small",
    srcs = ["test/android/base/sockets/AsyncSocket_perf.cpp"] + glob([
        "test/**/*.h",
    ]),
    copts = ["-Wno-deprecated-declarations"],
    includes = ["test"],
    deps = [
        ":test-sockets",
        "@com_github_google_benchmark//:benchmark",
    ],
)
