load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "sockets",
    srcs = ["src/SocketUtils.cpp"],
    copts = select({
        "@platforms//os:windows": [
            "-Wno-microsoft-goto",
            "-Wno-macro-redefined",
        ],
        "//conditions:default": [],
    }),
    includes = ["include"],
    linkopts = select({
        "@platforms//os:windows": [
            "-DEFAULTLIB:Rpcrt4.lib",
            "-DEFAULTLIB:Ws2_32.lib",
        ],
        "//conditions:default": [],
    }),
    visibility = ["//visibility:public"],
    deps = [
        "//hardware/generic/goldfish/android/system",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:check",
        "@aemu//base:aemu-base",
    ],
)

cc_test(
    name = "sockets_unittests",
    srcs = ["test/SocketUtils_unittest.cpp"],
    linkopts = select({
        "@platforms//os:macos": ["-undefined error"],
        "//conditions:default": [],
    }),
    deps = [
        ":sockets",
        "//hardware/generic/goldfish/android/system:googletest_main",
    ],
)
